// dungeons.js
//


top.dungeons = [




{"title": "d6 Cet endroit est un...",  "id": "d6thisplaceisa_elementalwaterdungeon",  "roll": [
    "Grotte marine.",
    "Série de tunnels inondés en profondeur sous terre.",
    "Forteresse construite par des êtres aquatiques.",
    "Temple dédié à un dieu de l'eau.",
    "Palais construit par un seigneur élémentaire de l'eau.",
    "Égouts qui ont mal tourné."
  ]},
{"title": "d6 Niveau d'eau Les chambres de cet endroit...",  "id": "d6waterlevelthechambersinthisplace_elementalwaterdungeon",  "roll": [
    "Sont toujours inondées jusqu'au plafond.",
    "Sont toujours inondées dans les niveaux inférieurs.",
    "Sont toujours inondées jusqu'à la taille.",
    "Se remplissent d'eau à marée haute.",
    "Se remplissent d'eau selon les saisons.",
    "Se remplissent d'eau selon les caprices d'un seigneur élémentaire."
  ]},
{"title": "d6 Élément majeur Vous voyez un/une...", "id": "d6majorfeatureyouseeaan_elementalwaterdungeon", "roll": [
  "Poche d'air.",
  "Autel dédié à un dieu de l'eau.",
  "Coffre lourd.",
  "Râtelier de harpons et/ou de lances.",
  "Squelette d’un mort noyé.",
  "Récif grouillant de vie."
]},
{"title": "d6 Élément mineur Vous voyez un/une...", "id": "d6minorfeatureyouseea_elementalwaterdungeon", "roll": [
  "Petit filet de bulles.",
  "Icône d’un dieu de l’eau.",
  "Débris d’un bateau brisé.",
  "Banc de poissons.",
  "Morceau de tissu en lambeaux.",
  "Poche d’eau fraîche."
]},

{"title": "d6 PNJ Vous rencontrez un/une…", "id": "d6npcyoumeetaan…_elementalwaterdungeon", "roll": [
  "Fantôme de contrebandier.",
  "Sirène curieuse.",
  "Elfe marin méfiant.",
  "Chasseur de trésors excentrique.",
  "Cultiste élémentaire à moitié fou.",
  "Change-bête reclus (lancez sur la table des bêtes)."
]},
{"title": "d6 Bête Vous rencontrez un/une…", "id": "d6beastyoumeetaan…_elementalwaterdungeon", "roll": [
  "Dauphin.",
  "Palourde géante.",
  "Homard.",
  "Poulpe.",
  "Phoque.",
  "Requin."
]},
{"title": "d6 Monstre secondaire Vous tombez sur un/une…", "id": "d6secondarymonsteryoucomeuponaan…_elementalwaterdungeon", "roll": [
  "Bête marine aberrante (lancez sur la table des bêtes).",
  "Nuée de crabes ou de poissons carnivores.",
  "Kuo-toa.",
  "Sahuagin.",
  "Sorcière marine.",
  "Élémentaire d’eau."
]},
{"title": "d6 Monstre principal Ce lieu est actuellement dirigé par un/une…", "id": "d6primarymonsterthisplaceiscurrentlyruledbya…_elementalwaterdungeon", "roll": [
  "Aboleth.",
  "Dragon bleu.",
  "Kraken.",
  "Prince maridan.",
  "Géant des tempêtes.",
  "Sorcier des tempêtes."
]},

{"title": "d6 Pièges/dangers Vous devez survivre à…", "id": "d6trapshazardyoumustsurvivethe…_elementalwaterdungeon", "roll": [
  "Murènes électriques.",
  "Méduses venimeuses.",
  "Piège à fléchettes empoisonnées.",
  "Piège de sas inondant.",
  "Courants tourbillonnants.",
  "Malédiction de mort putréfiée."
]},
{"title": "d6 Récompense/trésor Si vous survivez, vous pourriez trouver...", "id": "d6rewardtreasureifyousurviveyoumayfind_elementalwaterdungeon", "roll": [
  "Trésor d’un capitaine pirate.",
  "Bâton de puissance élémentaire.",
  "Arme ancienne forgée en corail.",
  "Pierre légendaire perdue en mer.",
  "Clé ouvrant un portail vers un autre royaume.",
  "Princesse sirène captive."
]},
  

{"title": "d6 Cet endroit est un...", "id": "d6thisplaceisa_elementalfiredungeon", "roll": [
  "Montagne volcanique.",
  "Série de bouches géothermiques en profondeur sous terre.",
  "Forteresse construite par des êtres de flammes.",
  "Temple dédié à un dieu du feu.",
  "Palais construit par un seigneur élémentaire du feu.",
  "Forge ou armurerie gigantesque ayant mal tourné."
]},
{"title": "d6 Qualité de l'air L'air dans les chambres ici est…", "id": "d6airqualitytheairinthechambersinhereis…_elementalfiredungeon", "roll": [
  "Rempli de cendres étouffantes.",
  "Rempli de cendres brûlantes.",
  "Rempli de fumée étouffante.",
  "Rempli de fumée noire.",
  "Inconfortablement chaud.",
  "Rempli de gaz toxique."
]},
{"title": "d6 Élément majeur Vous voyez un/une...", "id": "d6majorfeatureyouseeaan_elementalfiredungeon", "roll": [
  "Brasero surdimensionné.",
  "Grande sculpture en fer.",
  "Autel dédié à un dieu du feu.",
  "Râtelier de lances en fer ou de cimeterres en acier.",
  "Squelette calciné d’un mortel.",
  "Fontaine de fumée et de flammes."
]},
{"title": "d6 Élément mineur Vous remarquez un/une...", "id": "d6minorfeatureyounoticeaan_elementalfiredungeon", "roll": [
  "Volute de fumée.",
  "Odeur de soufre.",
  "Icône d’un dieu du feu.",
  "Objet en bois carbonisé.",
  "Traces de brûlure sur le mur.",
  "Applique murale en fer avec une torche."
]},
{"title": "d6 PNJ Vous rencontrez un/une…", "id": "d6npcyoumeetaan…_elementalfiredungeon", "roll": [
  "Cultiste élémentaire à moitié fou.",
  "Esclave mortel en fuite.",
  "Prospecteur nain intrépide.",
  "Sorcier renégat.",
  "Moine ermite.",
  "Érudit semi-démoniaque."
]},
{"title": "d6 Bête Vous rencontrez un/une…", "id": "d6beastyoumeeta…_elementalfiredungeon", "roll": [
  "Chauve-souris de feu.",
  "Nuée de scarabées de feu.",
  "Drakéide de flammes.",
  "Hyène démoniaque.",
  "Serpent de flammes.",
  "Stirge démoniaque."
]},
{"title": "d6 Monstre secondaire Vous tombez sur un/une…", "id": "d6secondarymonsteryoucomeuponaan…_elementalfiredungeon", "roll": [
  "Azer.",
  "Gnoll.",
  "Élémentaire de feu.",
  "Chien infernal.",
  "Salamandre.",
  "Squelette en flammes."
]},
{"title": "d6 Monstre principal Ce lieu est actuellement dirigé par un/une…", "id": "d6primarymonsterthisplaceiscurrentlyruledbyaan…_elementalfiredungeon", "roll": [
  "Diable intrigant.",
  "Prince efreet.",
  "Démon de feu.",
  "Géant du feu.",
  "Pyromancien maléfique.",
  "Dragon rouge."
]},
{"title": "d6 Pièges/dangers Vous devez survivre à…", "id": "d6trapshazardyoumustsurvivethe…_elementalfiredungeon", "roll": [
  "Chambre scellée qui se remplit de gaz toxique.",
  "Murs de flammes soudains et sporadiques.",
  "Plafond qui s’effondre.",
  "Explosions de feu et de roche.",
  "Piège de faux plancher.",
  "Piège de lames tourbillonnantes."
]},
{"title": "d6 Récompense/trésor Si vous survivez, vous pourriez trouver un/une...", "id": "d6rewardtreasureifyousurviveyoumayfindaan_elementalfiredungeon", "roll": [
  "Trésor d’un bandit notoire.",
  "Baguette de puissance élémentaire.",
  "Arme ancienne forgée de feu et d’acier.",
  "Cristal offrant des aperçus du futur.",
  "Génie lié à une lampe.",
  "Phénix captif."
]},


{"title": "d6 Cet endroit est un...", "id": "d6thisplaceisa_elementalearthdungeon", "roll": [
  "Palais construit par un seigneur élémentaire de la terre.",
  "Temple dédié à un dieu de la terre.",
  "Forteresse construite par des êtres de terre élémentaire.",
  "Série de tunnels instables profondément sous terre.",
  "Labyrinthe de roche solide.",
  "Exploitation minière ayant mal tourné."
]},
{"title": "d6 Sol/terrain Vous marchez souvent sur...", "id": "d6floorterrainyoufrequentlystepon_elementalearthdungeon", "roll": [
  "Poussière glissante.",
  "Boue qui aspire les bottes.",
  "Gravats instables.",
  "Gravier lisse.",
  "Rochers tranchants.",
  "Pointes métalliques acérées."
]},
{"title": "d6 Élément majeur Vous voyez un/une...", "id": "d6majorfeatureyouseeaan_elementalearthdungeon", "roll": [
  "Monolithe de pierre.",
  "Autel dédié à un dieu de la terre.",
  "Statue d’une figure faite de pierre ou de fer.",
  "Pont naturel en pierre.",
  "Série de colonnes de pierre.",
  "Gouffre profond."
]},
{"title": "d6 Élément mineur Vous remarquez un/une...", "id": "d6minorfeatureyounoticeaan_elementalearthdungeon", "roll": [
  "Petite statue de pierre.",
  "Icône d’un dieu de la terre.",
  "Stalactite.",
  "Tremblement bref.",
  "Grondement lointain.",
  "Tourbillon de poussière."
]},
{"title": "d6 PNJ Vous rencontrez un/une…", "id": "d6npcyoumeetaan…_elementalearthdungeon", "roll": [
  "Fantôme d’un chasseur de trésors malchanceux.",
  "Cultiste élémentaire à moitié fou.",
  "Prospecteur nain.",
  "Moine taciturne.",
  "Elfe noir vagabond.",
  "Inventeur d’un engin de forage."
]},
{"title": "d6 Bête Vous rencontrez un/une…", "id": "d6beastyoumeetaan…_elementalearthdungeon", "roll": [
  "Taupe géante.",
  "Nuée de rats.",
  "Mille-pattes géant.",
  "Fourmi géante.",
  "Ver de terre géant.",
  "Gelée boueuse."
]},
{"title": "d6 Monstre secondaire Vous tombez sur un/une…", "id": "d6secondarymonsteryoucomeuponaan…_elementalearthdungeon", "roll": [
  "Élémentaire de terre.",
  "Monstre rouilleur.",
  "Xorn.",
  "Galeb duhr.",
  "Zombie.",
  "Otyugh."
]},
{"title": "d6 Monstre principal Ce lieu est actuellement dirigé par un/une…", "id": "d6primarymonsterthisplaceiscurrentlyruledbyaan…_elementalearthdungeon", "roll": [
  "Prince dao.",
  "Géant de pierre.",
  "Dragon ancestral.",
  "Géomancien puissant.",
  "Liche.",
  "Grick alpha."
]},
{"title": "d6 Pièges/dangers Vous devez survivre à…", "id": "d6trapshazardyoumustsurvivethe…_elementalearthdungeon", "roll": [
  "Fosses de boue nauséabonde.",
  "Piège aux murs écrasants.",
  "Piège des vierges embrassantes.",
  "Piège de lances surgissant du sol.",
  "Ponts et arches en ruine.",
  "Plafonds qui s’effondrent."
]},
{"title": "d6 Récompense/trésor Si vous survivez, vous pourriez trouver un/une...", "id": "d6rewardtreasureifyousurviveyoumayfindaan_elementalearthdungeon", "roll": [
  "Grimoire d’un nécromancien notoire.",
  "Orbe de puissance élémentaire.",
  "Filon légendaire de minerai précieux (or, platine, adamantium ou mithral).",
  "Diamant issu de la légende naine.",
  "Marteau manié par un guerrier quasi divin.",
  "Démon captif."
]},


{"title": "d6 Cet endroit est un...", "id": "d6thisplaceisa_elementalairdungeon", "roll": [
  "Palais construit par un seigneur élémentaire de l’air.",
  "Série de grottes dans un îlot flottant de terre.",
  "Série de tunnels profonds balayés par un vent hurlant constant.",
  "Forteresse construite par des êtres d’air élémentaire.",
  "Temple dédié à un dieu du vent.",
  "Labyrinthe de nuages semi-solides."
]},
{"title": "d6 Sons ambiants Vous entendez un/une...", "id": "d6ambientsoundsyouhearaan_elementalairdungeon", "roll": [
  "Hurlement constant du vent.",
  "Flux d’air continu.",
  "Sifflement monotone constant.",
  "Suite étrange et changeante d’accords musicaux.",
  "Claquement de tonnerre intermittent.",
  "Flûte jouant quelque part."
]},
{"title": "d6 Élément majeur Vous voyez un/une...", "id": "d6majorfeatureyouseeaan_elementalairdungeon", "roll": [
  "Intersection aux vents changeants rapides.",
  "Grande sculpture de nuages.",
  "Brume étrange et scintillante.",
  "Tonneau de flèches emplumées.",
  "Autel dédié à un dieu du vent.",
  "Immense haricot magique ou escalier descendant bien en dessous de là où vous vous tenez."
]},
{"title": "d6 Élément mineur Vous remarquez un/une...", "id": "d6minorfeatureyounoticeaan_elementalairdungeon", "roll": [
  "Petit nuage en forme d’animal.",
  "Lampe flottante.",
  "Icône d’un dieu du vent.",
  "Bouffée d’air frais.",
  "Sifflement aigu soudain au loin.",
  "Tourbillon de poussière."
]},
{"title": "d6 PNJ Vous rencontrez un/une…", "id": "d6npcyoumeetaan…_elementalairdungeon", "roll": [
  "Fantôme d’un explorateur malchanceux.",
  "Cultiste élémentaire à moitié fou.",
  "Change-bête nerveux (lancez sur la table des bêtes).",
  "Moine contemplatif.",
  "Voyageur interplanaire.",
  "Inventeur avec un engin volant."
]},
{"title": "d6 Bête Vous rencontrez un/une…", "id": "d6beastyoumeetaan…_elementalairdungeon", "roll": [
  "Corbeau.",
  "Chauve-souris.",
  "Faucon.",
  "Abeille géante.",
  "Ptérodactyle.",
  "Nuée de papillons de nuit."
]},
{"title": "d6 Monstre secondaire Vous tombez sur un/une…", "id": "d6secondarymonsteryoucomeuponaan…_elementalairdungeon", "roll": [
  "Élémentaire d’air.",
  "Faucon-flèche.",
  "Traqueur invisible.",
  "Vouivre.",
  "Spectre.",
  "Roc."
]},
{"title": "d6 Monstre principal Ce lieu est actuellement dirigé par un/une…", "id": "d6primarymonsterthisplaceiscurrentlyruledbyaan…_elementalairdungeon", "roll": [
  "Prince djinn.",
  "Géant des nuages.",
  "Aigle géant.",
  "Entropomancien maléfique.",
  "Observateur.",
  "Spectre."
]},
{"title": "d6 Pièges/dangers Vous devez survivre à…", "id": "d6trapshazardyoumustsurvivethe…_elementalairdungeon", "roll": [
  "Trappe menant à une chute vertigineuse.",
  "Piège à fléchettes empoisonnées.",
  "Piège de tourelle à arbalète magique.",
  "Runes qui explosent en décharges de foudre.",
  "Chambre scellée qui devient un vide.",
  "Malédiction de lassitude."
]},
{"title": "d6 Récompense/trésor Si vous survivez, vous pourriez trouver un/une...", "id": "d6rewardtreasureifyousurviveyoumayfindaan_elementalairdungeon", "roll": [
  "Trésor d’un géant infâme.",
  "Épave d’un dirigeable légendaire.",
  "Sceptre de puissance élémentaire.",
  "Arc ayant appartenu à un héros ancien.",
  "Grimoire perdu d’un puissant magicien.",
  "Dragon emprisonné."
]},


{"title": "d20 Courants d'air", "id": "d20aircurrents_randomdugeonfeatures", "roll": [
  "brise, légère, humide.",
  "brise, en rafales.",
  "courant froid.",
  "courant descendant, léger.",
  "courant descendant, fort.",
  "immobile.",
  "immobile.",
  "immobile.",
  "immobile.",
  "immobile.",
  "immobile.",
  "immobile.",
  "immobile, très froid.",
  "immobile, tiède (ou chaud).",
  "courant ascendant, léger.",
  "courant ascendant, fort.",
  "vent, fort.",
  "vent, fort, en rafales.",
  "vent, fort, mugissant."
]},
{"title": "d20 Odeurs", "id": "d20odors_randomdugeonfeatures", "roll": [
  "odeur de chlore.",
  "odeur de moisi et d’humidité.",
  "odeur de moisi et d’humidité.",
  "odeur de moisi et d’humidité.",
  "odeur de moisi et d’humidité.",
  "odeur de moisi et d’humidité.",
  "odeur de moisi et d’humidité.",
  "odeur terreuse.",
  "odeur de fumier.",
  "odeur métallique.",
  "odeur d’ozone.",
  "odeur putride.",
  "odeur de végétation en décomposition.",
  "odeur salée et humide.",
  "odeur de fumée.",
  "odeur rance et fétide.",
  "odeur sulfureuse.",
  "odeur d’urine.",
  "odeur de moisi et d’humidité."
]},
{"title": "d10 Air", "id": "d10air_randomdugeonfeatures", "roll": [
  "clair.",
  "clair.",
  "clair.",
  "clair.",
  "clair.",
  "brumeux (ou vaporeux).",
  "brumeux près du sol (ou vaporeux).",
  "voilé (poussière).",
  "embrumé."
]},
{"title": "d100 Éléments généraux", "id": "d100generalfeatures_randomdugeonfeatures", "roll": [
  "cendres.",
  "cendres.",
  "cendres.",
  "os.",
  "os.",
  "bouteille, cassée.",
  "chaîne, corrodée.",
  "matraque, éclatée.",
  "toiles d’araignée.",
  "toiles d’araignée.",
  "toiles d’araignée.",
  "toiles d’araignée.",
  "toiles d’araignée.",
  "toiles d’araignée.",
  "toiles d’araignée.",
  "toiles d’araignée.",
  "toiles d’araignée.",
  "toiles d’araignée.",
  "pièce de cuivre (pliée).",
  "fissures au plafond.",
  "fissures au plafond.",
  "fissures au sol.",
  "fissures au sol.",
  "fissures sur le mur.",
  "fissures sur le mur.",
  "poignée de dague.",
  "humidité au plafond.",
  "humidité au plafond.",
  "humidité sur le mur.",
  "humidité sur le mur.",
  "humidité sur le mur.",
  "humidité sur le mur.",
  "gouttes d’eau.",
  "gouttes d’eau.",
  "gouttes d’eau.",
  "gouttes d’eau.",
  "gouttes d’eau.",
  "gouttes d’eau.",
  "gouttes d’eau.",
  "sang séché.",
  "crottin.",
  "crottin.",
  "crottin.",
  "poussière.",
  "poussière.",
  "poussière.",
  "poussière.",
  "poussière.",
  "flasque, fêlée.",
  "restes de nourriture.",
  "champignons communs.",
  "guano.",
  "guano.",
  "guano.",
  "mèches de poils ou cheveux.",
  "tête de marteau, fêlée.",
  "casque, très cabossé.",
  "barre de fer, tordue et rouillée.",
  "pointe de javelot, émoussée.",
  "botte en cuir.",
  "feuilles sèches et brindilles.",
  "feuilles sèches et brindilles.",
  "feuilles sèches et brindilles.",
  "moisissure (commune).",
  "moisissure (commune).",
  "moisissure (commune).",
  "moisissure (commune).",
  "manche de pioche.",
  "perche, brisée.",
  "éclats de poterie.",
  "chiffons.",
  "chiffons.",
  "corde, pourrie.",
  "gravats et terre.",
  "gravats et terre.",
  "sac, déchiré.",
  "revêtement visqueux au plafond.",
  "revêtement visqueux au sol.",
  "revêtement visqueux sur le mur.",
  "pointe, rouillée.",
  "bâtons.",
  "bâtons.",
  "pierres, petites.",
  "paille.",
  "lame d’épée, brisée.",
  "dents/crocs, éparpillés.",
  "morceau de torche.",
  "morceau de torche.",
  "griffures sur les murs.",
  "griffures sur les murs.",
  "eau, petite flaque.",
  "eau, petite flaque.",
  "eau, grande flaque.",
  "eau, grande flaque.",
  "eau, filet d’eau.",
  "goutte de cire (reste de bougie).",
  "morceaux de bois, pourrissants.",
  "morceaux de bois, pourrissants.",
  "morceaux de bois, pourrissants."
]},
{"title": "d100 Bruits inexpliqués et sons étranges", "id": "d100unexplainedsoundsandstrangenoises_randomdugeonfeatures", "roll": [
  "fracas, claquement.",
  "fracas, claquement.",
  "fracas, claquement.",
  "fracas, claquement.",
  "beuglement.",
  "bong.",
  "bourdonnement.",
  "chant.",
  "chant.",
  "carillon.",
  "piaillement.",
  "cliquetis métallique.",
  "bruit de choc.",
  "clics.",
  "toux.",
  "grincement.",
  "grincement.",
  "tambourinement.",
  "pas (devant).",
  "pas (devant).",
  "pas (devant).",
  "pas (devant).",
  "pas (qui approchent).",
  "pas (qui approchent).",
  "pas (qui approchent).",
  "pas (derrière).",
  "pas (derrière).",
  "pas (derrière).",
  "pas (qui s’éloignent).",
  "pas (qui s’éloignent).",
  "pas (sur le côté).",
  "pas (sur le côté).",
  "gloussements (faibles).",
  "gloussements (faibles).",
  "gong.",
  "raclement.",
  "raclement.",
  "raclement.",
  "gémissement.",
  "gémissement.",
  "grognement.",
  "sifflement.",
  "sifflement.",
  "hulullement.",
  "cor ou trompette.",
  "hurlement.",
  "fredonnement.",
  "tintement.",
  "frappement.",
  "frappement.",
  "frappement.",
  "frappement.",
  "rire.",
  "rire.",
  "gémissement long.",
  "gémissement long.",
  "murmure.",
  "murmure.",
  "murmure.",
  "musique.",
  "cliquetis.",
  "sonnerie.",
  "rugissement.",
  "bruissement.",
  "bruissement.",
  "bruissement.",
  "bruissement.",
  "griffures/grattements.",
  "griffures/grattements.",
  "griffures/grattements.",
  "griffures/grattements.",
  "cri/hurlement.",
  "cri/hurlement.",
  "cavalcade (rapide).",
  "cavalcade (rapide).",
  "cavalcade (rapide).",
  "bruit de traînement.",
  "coulissement.",
  "coulissement.",
  "claquement sec.",
  "éternuement.",
  "sanglots.",
  "éclaboussement.",
  "éclatement.",
  "couinement.",
  "couinement.",
  "hurlement aigu.",
  "tapotement.",
  "tapotement.",
  "bruit sourd.",
  "bruit sourd.",
  "battement lourd.",
  "battement lourd.",
  "tintement léger.",
  "vibration de corde.",
  "gémissement plaintif.",
  "chuchotement.",
  "sifflement.",
  "sifflement."
]},
{"title": "d100 Mobilier et Aménagements – Général", "id": "d100furnishingandappointmentsgeneral_randomdugeonfeatures", "roll": [
  "fauteuil.",
  "armoire.",
  "flèches.",
  "sac.",
  "baril.",
  "lit.",
  "lit.",
  "banc.",
  "couverture.",
  "boîte (grande).",
  "brasero et charbon.",
  "seau.",
  "buffet.",
  "couchettes.",
  "tonneau (gros).",
  "placard.",
  "chandelier à branches.",
  "tapis (grand).",
  "tonneau.",
  "lustre.",
  "charbon.",
  "chaise.",
  "chaise.",
  "chaise rembourrée.",
  "chaise rembourrée avec accoudoirs.",
  "coffre, grand.",
  "coffre, moyen.",
  "commode.",
  "garde-robe.",
  "charbon.",
  "canapé.",
  "canapé.",
  "caisse.",
  "flambeau mural.",
  "placard.",
  "coussin.",
  "bureau.",
  "bureau.",
  "cheminée et bois.",
  "cheminée et bois.",
  "cheminée et bois.",
  "cheminée avec manteau.",
  "petit tonnelet.",
  "fontaine.",
  "fresque.",
  "meule.",
  "panier.",
  "pouf.",
  "barrique.",
  "idole (grande).",
  "tonneau (petit).",
  "métier à tisser.",
  "tapis de sol.",
  "matelas.",
  "seau à anse.",
  "peinture.",
  "paillasse.",
  "paillasse.",
  "paillasse.",
  "piédestal.",
  "crochets muraux.",
  "crochets muraux.",
  "crochets muraux.",
  "oreiller.",
  "tonneau de grande taille.",
  "édredon.",
  "tapis (petit).",
  "tapis (moyen).",
  "tapis (grand).",
  "joncs au sol.",
  "sac.",
  "applique murale.",
  "paravent.",
  "drap.",
  "étagère.",
  "étagère.",
  "autel ou sanctuaire.",
  "buffet bas.",
  "sofa.",
  "bâton, ordinaire.",
  "porte-support.",
  "statue.",
  "tabouret haut.",
  "tabouret ordinaire.",
  "table, grande.",
  "table, longue.",
  "table, basse.",
  "table, ronde.",
  "table, petite.",
  "table à tréteaux.",
  "tapisserie.",
  "trône.",
  "malle.",
  "baquet.",
  "tonneau (très grand).",
  "urne.",
  "bassin mural et bénitier.",
  "bûches de bois.",
  "établi."
]},
{"title": "d100 Objets et ameublements religieux", "id": "d100religiousarticlesandfurnishings_randomdugeonfeatures", "roll": [
  "autel.",
  "autel.",
  "autel.",
  "autel.",
  "cloche(s).",
  "cloche(s).",
  "cloche(s).",
  "brasero(s).",
  "brasero(s).",
  "brasero(s).",
  "chandeliers à branches.",
  "bougies.",
  "bougies.",
  "bougeoirs.",
  "chapes/robes liturgiques.",
  "carillon(s).",
  "linge d’autel.",
  "linge d’autel.",
  "colonnes/piliers.",
  "colonnes/piliers.",
  "colonnes/piliers.",
  "colonnes/piliers.",
  "rideau/tapisserie.",
  "tambour.",
  "bénitier.",
  "bénitier.",
  "gong.",
  "gong.",
  "symbole sacré/profane.",
  "symbole sacré/profane.",
  "symbole sacré/profane.",
  "symbole sacré/profane.",
  "symbole sacré/profane.",
  "symbole sacré/profane.",
  "écrits sacrés/profanes.",
  "écrits sacrés/profanes.",
  "idole(s).",
  "idole(s).",
  "idole(s).",
  "idole(s).",
  "idole(s).",
  "idole(s).",
  "brûle-encens.",
  "brûle-encens.",
  "brûle-encens.",
  "brûle-encens.",
  "brûle-encens.",
  "banc de prière.",
  "lampe(s).",
  "lampe(s).",
  "lampe(s).",
  "lampe(s).",
  "lutrin.",
  "mosaïques.",
  "contenant à offrandes.",
  "contenant à offrandes.",
  "contenant à offrandes.",
  "peintures/fresques.",
  "bancs.",
  "bancs.",
  "flûtes/pipes (instruments).",
  "tapis de prière.",
  "chaire.",
  "rampe.",
  "robes rituelles.",
  "robes rituelles.",
  "sanctuaire.",
  "sanctuaire.",
  "paravent.",
  "paravent.",
  "reliquaire.",
  "reliquaire.",
  "reliquaire.",
  "reliquaire.",
  "reliquaire.",
  "chaise(s) latérale(s).",
  "porte-support.",
  "porte-support.",
  "statue(s).",
  "statue(s).",
  "statue(s).",
  "trône.",
  "encensoir.",
  "encensoir.",
  "trépied.",
  "trépied.",
  "trépied.",
  "sacristie.",
  "sacristie.",
  "ornements religieux.",
  "ornements religieux.",
  "ornements religieux.",
  "ornements religieux.",
  "ornements religieux.",
  "ornements religieux.",
  "ornements religieux.",
  "lumière votive.",
  "lumière votive.",
  "lumière votive."
]},
{"title": "d100 Mobilier de chambre de torture", "id": "d100torturechamberfurnishings_randomdugeonfeatures", "roll": [
  "bastonnades.",
  "cloche (énorme).",
  "banc.",
  "banc.",
  "banc.",
  "bottes (en fer).",
  "bottes (en fer).",
  "bottes (en fer).",
  "bottes (en fer).",
  "fers à marquer.",
  "fers à marquer.",
  "fers à marquer.",
  "fers à marquer.",
  "fers à marquer.",
  "brasero.",
  "brasero.",
  "brasero.",
  "brasero.",
  "brasero.",
  "cage.",
  "cage.",
  "chaînes.",
  "chaînes.",
  "chaînes.",
  "chaînes.",
  "chaise avec sangles.",
  "pinces de serrage.",
  "flambeaux muraux.",
  "flambeaux muraux.",
  "flambeaux muraux.",
  "entraves.",
  "fosse à feu.",
  "fosse à feu.",
  "fosse à feu.",
  "gril.",
  "crochets.",
  "crochets.",
  "vierge de fer.",
  "vierge de fer.",
  "vierge de fer.",
  "vierge de fer.",
  "vierge de fer.",
  "couteaux.",
  "menottes.",
  "oubliette.",
  "huile (tonneau d’).",
  "huile (tonneau d’).",
  "pilori.",
  "pilori.",
  "pinces.",
  "pinces.",
  "pinces.",
  "pinces.",
  "pince multiprise.",
  "pince multiprise.",
  "chaudron (énorme).",
  "chaudron (énorme).",
  "chevalet.",
  "chevalet.",
  "chevalet.",
  "chevalet.",
  "chevalet.",
  "chevalet.",
  "chevalet.",
  "chevalet.",
  "cordes.",
  "cordes.",
  "cage à cou.",
  "tabouret.",
  "tabouret.",
  "strappado.",
  "strappado.",
  "strappado.",
  "strappado.",
  "paille.",
  "paille.",
  "paille.",
  "table.",
  "table.",
  "lanières.",
  "vis à pouces.",
  "vis à pouces.",
  "vis à pouces.",
  "vis à pouces.",
  "torches.",
  "torches.",
  "torches.",
  "chevalet en U.",
  "chevalet en U.",
  "étau.",
  "puits.",
  "puits.",
  "roue.",
  "roue.",
  "roue.",
  "fouets.",
  "fouets.",
  "fouets.",
  "fouets."
]},
{"title": "d100 Mobilier d'utilisateur de la magie", "id": "d100magic-userfurnishings_randomdugeonfeatures", "roll": [
  "alambic.",
  "alambic.",
  "balance et poids.",
  "balance et poids.",
  "bécher.",
  "bécher.",
  "bécher.",
  "bécher.",
  "soufflet.",
  "vessie.",
  "bouteille.",
  "bouteille.",
  "livre.",
  "livre.",
  "livre.",
  "bol.",
  "boîte.",
  "brasero.",
  "brasero.",
  "brasero.",
  "brasero.",
  "cage.",
  "chaudron.",
  "chaudron.",
  "bougie.",
  "bougeoir.",
  "carafe.",
  "craie.",
  "craie.",
  "creuset.",
  "flaconnet.",
  "boule de cristal.",
  "carafe à décanter.",
  "bureau.",
  "plat.",
  "flasque.",
  "flasque.",
  "entonnoir.",
  "fourneau.",
  "herbes.",
  "herbes.",
  "herbes.",
  "herbes.",
  "corne.",
  "sablier.",
  "bocal.",
  "bocal.",
  "cruche.",
  "bouilloire.",
  "louche.",
  "lampe.",
  "lentille (concave, convexe, etc...).",
  "cercle magique.",
  "mortier et pilon.",
  "poêle.",
  "parchemin.",
  "parchemin.",
  "pentacle.",
  "pentagramme.",
  "fiole.",
  "pipette.",
  "pot.",
  "prisme.",
  "plume.",
  "cornue.",
  "cornue.",
  "cornue.",
  "bâton de mélange.",
  "parchemin.",
  "parchemin.",
  "tube à parchemin.",
  "feuille.",
  "peau.",
  "crâne.",
  "spatule.",
  "cuillère doseuse.",
  "support.",
  "tabouret.",
  "animal empaillé.",
  "cuve (récipient).",
  "pinces.",
  "trépied.",
  "tube (récipient).",
  "tube (tuyauterie).",
  "tube (tuyauterie).",
  "pincettes.",
  "fiolule.",
  "fiolule.",
  "fiolule.",
  "clepsydre.",
  "fil de fer.",
  "établi.",
  "établi.",
  "établi.",
  "établi.",
  "établi.",
  "établi.",
  "établi.",
  "établi."
]},
{"title": "d30 Description générale du contenu d’un conteneur", "id": "d30generaldescriptionofcontainercontents_randomdugeonfeatures", "roll": [
  "écorce.",
  "os.",
  "os.",
  "morceaux.",
  "cendres.",
  "cristaux.",
  "poussière.",
  "fibres.",
  "fibres.",
  "gélatine.",
  "globules.",
  "grains.",
  "gras.",
  "enveloppes.",
  "feuilles.",
  "liquide.",
  "motte(s).",
  "huileux.",
  "pâte.",
  "granulés.",
  "poudre.",
  "semi-liquide.",
  "semi-liquide.",
  "peau/cuir.",
  "échardes.",
  "tiges.",
  "brins.",
  "bandes.",
  "visqueux."
]},
{"title": "d100 Ustensiles divers et objets personnels", "id": "d100miscellaneousutensilsandpersonalitems_randomdugeonfeatures", "roll": [
  "bandages.",
  "bassin.",
  "panier.",
  "panier.",
  "batteur.",
  "livre.",
  "bouteille.",
  "bouteille.",
  "bol.",
  "boîte (petite).",
  "brosse.",
  "brosse.",
  "bougie.",
  "éteignoir à bougie.",
  "bougeoir.",
  "canne (bâton de marche).",
  "étui.",
  "coffret (petit).",
  "hachoir.",
  "coffre.",
  "eau de Cologne.",
  "peigne.",
  "tasse.",
  "carafe à décanter.",
  "louchette.",
  "assiette.",
  "cure-oreille.",
  "aiguière.",
  "flacon.",
  "flasque.",
  "nourriture.",
  "fourchette.",
  "râpe.",
  "moulin.",
  "sablier.",
  "chope (récipient).",
  "bocal.",
  "cruche.",
  "bouilloire.",
  "couteau.",
  "osselets.",
  "louche.",
  "lampe/lanterne.",
  "lampe/lanterne.",
  "pilon.",
  "miroir.",
  "chope.",
  "aiguille(s).",
  "huile de cuisson (ou combustible).",
  "huile (combustible).",
  "huile parfumée.",
  "poêle.",
  "parchemin.",
  "pichet.",
  "flûte (instrument).",
  "pipe (à fumer).",
  "assiette.",
  "plateau.",
  "pot.",
  "bourse.",
  "houppette.",
  "plume.",
  "rasoir.",
  "corde.",
  "onguent.",
  "soucoupe.",
  "racloir.",
  "parchemin.",
  "poivrier/salière.",
  "tamis.",
  "savon.",
  "robinet.",
  "cuillère.",
  "bouchon.",
  "statuette/figurine.",
  "passoire.",
  "chope en métal.",
  "lanières.",
  "fil.",
  "boîte à amadou (avec silex et acier).",
  "boîte à amadou (avec silex et acier).",
  "boîte à amadou (avec silex et acier).",
  "boîte à amadou (avec silex et acier).",
  "serviette.",
  "serviette.",
  "plateau.",
  "trépied.",
  "soupière.",
  "ficelle.",
  "ficelle.",
  "pommade.",
  "vase.",
  "fiole.",
  "portefeuille.",
  "gant de toilette.",
  "pierre à aiguiser.",
  "perruque.",
  "laine.",
  "fil de laine."
]},
{"title": "d100 Vêtements et chaussures", "id": "d100clothingandfootwear_randomdugeonfeatures", "roll": [
  "tablier.",
  "ceinture.",
  "ceinture.",
  "blouse.",
  "bottes.",
  "bottes.",
  "bottes.",
  "brodequins.",
  "bonnet.",
  "bonnet.",
  "cape.",
  "cape.",
  "manteau.",
  "manteau.",
  "manteau.",
  "veste.",
  "veste.",
  "coiffe.",
  "pourpoint.",
  "robe.",
  "robe.",
  "tablier/fichu.",
  "tablier/fichu.",
  "gantelets.",
  "gantelets.",
  "cordon.",
  "cordon.",
  "gants.",
  "toilette longue.",
  "toilette longue.",
  "chapeau.",
  "chapeau.",
  "chapeau.",
  "habit.",
  "capuche.",
  "capuche.",
  "capuche.",
  "capuche.",
  "chausses.",
  "chausses.",
  "gilet court.",
  "gilet court.",
  "jupon.",
  "foulard.",
  "foulard.",
  "cotte.",
  "cotte.",
  "jambières.",
  "jambières.",
  "linge (caleçon).",
  "linge (caleçon).",
  "linge (caleçon).",
  "linge (caleçon).",
  "linge (chemise).",
  "linge (chemise).",
  "linge (chemise).",
  "linge (chemise).",
  "mante.",
  "pantalon bouffant.",
  "jupon.",
  "jupon.",
  "bourse/porte-monnaie.",
  "bourse/porte-monnaie.",
  "bourse/porte-monnaie.",
  "bourse/porte-monnaie.",
  "robe.",
  "robe.",
  "robe.",
  "robe.",
  "sandales.",
  "sandales.",
  "sandales.",
  "sandales.",
  "écharpe.",
  "écharpe.",
  "châle.",
  "chemise de nuit.",
  "chemise de nuit.",
  "chaussons.",
  "chaussons.",
  "chaussons.",
  "chaussons.",
  "chemise ample.",
  "chemise ample.",
  "chemise ample.",
  "bas.",
  "bas.",
  "bas.",
  "surcot.",
  "toge.",
  "pantalon.",
  "pantalon.",
  "pantalon.",
  "tunique.",
  "tunique.",
  "voile.",
  "gilet.",
  "portefeuille.",
  "robe de chambre."
]},




{"title": "d10 Le maître de cette tour est...", "id": "d10themasterofthistoweris_magetower", "roll": [
  "Une envoûteuse elfe.",
  "Une sorcière terrifiante.",
  "Un nécromancien inquiétant.",
  "Un voyant mystique.",
  "Un sage à la longue barbe.",
  "Un élémentaliste à moitié fou.",
  "Un invocateur légendaire.",
  "Un explorateur à la retraite.",
  "Le chef d’un cabale de sorcières rusées.",
  "Le dirigeant d’une société secrète de magiciens."
]},

{"title": "d10 La forme de la tour est approximativement celle d...", "id": "d10thetowersshapeisapproximatelythatof_magetower", "roll": [
  "Un cylindre.",
  "Une pyramide.",
  "Une pyramide à degrés.",
  "Un cône.",
  "Un prisme triangulaire.",
  "Un prisme rectangulaire.",
  "Un prisme pentagonal.",
  "Un prisme hexagonal.",
  "Un prisme octogonal.",
  "Un icosaèdre."
]},
{"title": "d10 La tour est construite en...", "id": "d10thetowerisbuiltof_magetower", "roll": [
  "Briques d’argile.",
  "Calcaire.",
  "Grès.",
  "Marbre.",
  "Obsidienne.",
  "Bois enchanté.",
  "Cristal.",
  "Ossements.",
  "Granit.",
  "Or massif."
]},
{"title": "d10 L’extérieur de la tour présente...", "id": "d10theexteriorofthetowerfeatures_magetower", "roll": [
  "Des toiles d’araignées.",
  "De la gelée.",
  "Des vignes portant des fruits.",
  "Des lianes épineuses.",
  "D’importantes réparations.",
  "D’anciens hiéroglyphes.",
  "Des runes arcaniques.",
  "Des plaques d’acier.",
  "Des marques de brûlure.",
  "Des traces de griffures."
]},
{"title": "d10 L’entrée de la tour est gardée par...", "id": "d10thetowersentranceisguardedby_magetower", "roll": [
  "Un dragon de mauvaise humeur.",
  "Un golem vigilant (d6) : 1. osseux ; 2. en chaînes ; 3. d’argile ; 4. de chair ; 5. de fer ; 6. de pierre.",
  "Un géant en colère (d6) : 1. funeste ; 2. de feu ; 3. de givre ; 4. d’ombre ; 5. de pierre ; 6. des nuages.",
  "De cruels gargouilles.",
  "Des élémentaires terrifiants (d6) : 1. air ; 2. terre ; 3. feu ; 4. glace ; 5. tempête ; 6. eau.",
  "Des morts-vivants serviteurs (d6) : 1. fantômes ; 2. goules ; 3. guerriers spectraux ; 4. spectres ; 5. revenants ; 6. zombies.",
  "Des pièges retors.",
  "Un sphinx rusé.",
  "Une bête féroce et parlante (d6) : 1. ours ; 2. griffon ; 3. aigle ; 4. lion ; 5. serpent ; 6. loup.",
  "Une bête menaçante aux tentacules."
]},
{"title": "d10 La pièce la mieux protégée de la tour est...", "id": "d10themostwell-protectedroominthetoweris_magetower", "roll": [
  "Le laboratoire du mage.",
  "La bibliothèque du mage.",
  "La chambre du mage.",
  "La cave à vin du mage.",
  "La salle au trésor du mage.",
  "Une salle spécialement aménagée pour les rituels de divination.",
  "Une salle spécialement aménagée pour les rituels d’invocation.",
  "Une salle spécialement aménagée pour les duels magiques.",
  "Une prison dont nul ne peut s’échapper.",
  "La crypte de quelqu’un d’important pour le mage (d6) : 1. maître ; 2. mentor ; 3. enfant ; 4. parent ; 5. amant ; 6. rival vaincu."
]},
{"title": "d10 La pièce est protégée par...", "id": "d10theroomisprotectedby_magetower", "roll": [
  "Une série de pièges mécaniques redoutables.",
  "Une série de pièges magiques sophistiqués.",
  "Une rune explosive.",
  "Un puissant charme qui pousse à l’ignorer.",
  "Un puissant charme qui empêche les intrus d’ouvrir la porte.",
  "Des illusions qui rendent la porte difficile à trouver.",
  "Une puissante malédiction qui effraie ceux qui approchent de la porte.",
  "Une puissante malédiction qui provoque une douleur chez ceux qui approchent de la porte.",
  "Un automate infatigable.",
  "Un gardien asservi (d6) : 1. diable ; 2. démon ; 3. élémentaire ; 4. bête enchantée ; 5. troll ; 6. spectre."
]},
{"title": "d10 On raconte que dans les murs de la tour, le mage garde...", "id": "d10rumorhasitthatwithinthewallsofthetowerthemagekeeps_magetower", "roll": [
  "L’arme d’un héros légendaire.",
  "Le bâton d’un sorcier ou nécromancien tristement célèbre.",
  "La baguette d’une célèbre sorcière ou d’un fameux magicien.",
  "Le grimoire d’un lanceur de sorts notoire.",
  "Les artefacts d’un héros elfe.",
  "Des monstruosités issues de la propre création du mage.",
  "Une pierre, un miroir ou un bassin légendaire servant à observer le monde à distance.",
  "Un livre fabuleux de savoirs dangereux (d6) : 1. démonologie ; 2. malédictions de non-mort ; 3. voyage onirique ; 4. amour et guerre ; 5. portails planaires ; 6. ténèbres impies.",
  "Une entité d’un pouvoir terrifiant emprisonnée (d6) : 1. abomination ; 2. diable ; 3. démon ; 4. djinn ; 5. éfrit ; 6. seigneur vampire.",
  "Une princesse captive."
]},




{"title": "d10 Cet endroit est (ou était)...", "id": "d10thisplaceisorwasa_dungeondetails", "roll": [
  "Une forteresse.",
  "Un temple.",
  "Une tombe.",
  "Une prison.",
  "Une mine.",
  "Un repaire.",
  "Un palais.",
  "Une chambre forte.",
  "Un égout.",
  "Un labyrinthe."
]},
{"title": "d12 ...construit par...", "id": "d12builtby_dungeondetails", "roll": [
  "Un ancien clan de nains.",
  "Un prince elfe d’autrefois.",
  "Un puissant magicien.",
  "Une sorcière noire.",
  "Un empire étranger.",
  "Une reine ambitieuse d’antan.",
  "Des marchands prospères.",
  "Une puissante famille noble.",
  "Des fanatiques religieux.",
  "Une race ancienne de géants.",
  "Un roi tyrannique d’autrefois.",
  "Personne ; c’est une grotte naturelle."
]},
{"title": "d12 ...et situé...", "id": "d12andlocated_dungeondetails", "roll": [
  "Sous une montagne glacée.",
  "Sous une montagne enflammée.",
  "Près d’un col de montagne très fréquenté.",
  "Au cœur d’une forêt.",
  "Au cœur d’un désert.",
  "Au bord de la mer.",
  "Sur une île.",
  "Sous une ville animée.",
  "Sous les ruines d’une cité antique.",
  "Sous un château ou un monastère bien connu.",
  "Sous les ruines d’un vieux château ou monastère.",
  "Dans un lieu accessible uniquement par magie."
]},
{"title": "d12 L’endroit est actuellement occupé par...", "id": "d12theplaceiscurrentlyoccupiedby_dungeondetails", "roll": [
  "Un hors-la-loi dangereux.",
  "Un seigneur élémentaire.",
  "Un vampire.",
  "Une liche.",
  "Un démon.",
  "Un diable.",
  "Un chef de guerre orc.",
  "Un commandant hobgobelin.",
  "Une présence aberrante.",
  "Une sorcière.",
  "Un géant.",
  "Un dragon."
]},
{"title": "d12 ...et quelques...", "id": "d12andsome_dungeondetails", "roll": [
  "Voleurs.",
  "Gobelins.",
  "Zombies.",
  "Squelettes.",
  "Chauves-souris.",
  "Rats.",
  "Araignées.",
  "Gelées.",
  "Kobolds.",
  "Cultistes.",
  "Troglodytes.",
  "Ogres."
]},
{"title": "d12 Si vous survivez aux...", "id": "d12ifyousurvivethe_dungeondetails", "roll": [
  "Pièges mécaniques redoutables.",
  "Puissantes protections magiques.",
  "Gardiens golems.",
  "Gardiens élémentaires.",
  "Gaz nocif.",
  "Moisissure toxique.",
  "Horrible malédiction.",
  "Plafonds instables.",
  "Salles inondables.",
  "Gouffres.",
  "Jets de vapeur et coulées de lave.",
  "Sol glissant."
]},
{"title": "d12 ...vous pourriez mettre la main sur...", "id": "d12youmightrecoverthe_dungeondetails", "roll": [
  "L’arme d’un guerrier légendaire.",
  "La baguette d’une célèbre sorcière ou d’un grand magicien.",
  "Le grimoire d’un mage notoire.",
  "Le trésor d’un pirate renommé.",
  "Le butin d’un vieux dragon.",
  "Le trésor d’un ancien royaume nain.",
  "Les artefacts d’un héros elfe.",
  "Les reliques d’un prêtre vénéré.",
  "Des coffres d’argent transportés par un navire ou une caravane perdue.",
  "Les joyaux de la couronne d’une reine depuis longtemps disparue.",
  "Le plus gros diamant jamais trouvé dans cette région du monde.",
  "Le bâton d’un sorcier ou nécromancien tristement célèbre."
]},



{"title": "d10 Le château se dresse...", "id": "d10thecastlesits", "roll": [
  "Au sommet d’une montagne.",
  "Sur une colline surplombant une vaste plaine.",
  "À la fourche d’une rivière.",
  "Sur une péninsule rocheuse et étroite.",
  "Au-dessus d’une falaise en bord de mer.",
  "Sur une colline dominant une vallée fluviale.",
  "Sur une colline émergeant d’un marécage.",
  "Sur une colline surplombant une forêt.",
  "Au bord d’une oasis ou d’une source naturelle dans le désert.",
  "Sur une crête dominant une plaine glacée."
]},
{"title": "d12 Le château a été construit par...", "id": "d12thecastlewasbuiltby", "roll": [
  "Un roi ou une reine sage.",
  "Un seigneur ou une dame ambitieux(se).",
  "Un tyran maléfique.",
  "Un puissant guerrier ou chef de guerre.",
  "Un aventurier à la retraite.",
  "Un héros de guerre célébré.",
  "Un roi ou une reine sans scrupules.",
  "Un seigneur ou une dame vaniteux(se).",
  "Une puissante sorcière ou un puissant magicien.",
  "Un souverain bien-aimé.",
  "Un marchand prospère.",
  "Un membre d’une ancienne maison noble."
]},
{"title": "d4 Le château a été construit...", "id": "d4thecastlewasbuilt", "roll": [
  "À une époque révolue.",
  "Il y a plusieurs centaines d’années.",
  "Il y a quelques décennies.",
  "Au cours de la dernière décennie."
]},
{"title": "d6 Actuellement, l’état du château est...", "id": "d6currentlythecastlesconditionis", "roll": [
  "Parfait ; l’entretien a été méticuleux.",
  "Bon ; il a été bien entretenu.",
  "Correct ; quelques fissures dans les murs, mais le château peut encore supporter un siège.",
  "Passable ; le château a connu de meilleurs jours.",
  "Mauvais ; les murs et les tours ont grand besoin de réparations.",
  "Délabré ; le lieu est pratiquement en ruines."
]},
{"title": "d12 Actuellement, le château est occupé par...", "id": "d12presentlythecastleisoccupiedby", "roll": [
  "Un membre de la famille royale.",
  "Un seigneur ou une dame ambitieux(se).",
  "Un tyran maléfique.",
  "Un seigneur ou une dame âgé(e).",
  "Un jeune seigneur ou une jeune dame impulsif(ve).",
  "Une compagnie de mercenaires.",
  "Un chef de guerre redouté ou un mercenaire à la retraite.",
  "Un marchand fortuné.",
  "Un pirate ou un voleur à la retraite.",
  "Un ancien aventurier.",
  "Un noble absentéiste.",
  "La Couronne, bien que le roi ou la reine y séjourne rarement."
]},
{"title": "d12 La position ou le territoire vaut la peine d’être défendu parce que...", "id": "d12thepositionorterritoryisworthdefendingbecause", "roll": [
  "Les terres environnantes sont excellentes pour la culture.",
  "Les mines proches sont riches en minerais ou en gemmes.",
  "Les terres avoisinantes sont idéales pour l’élevage du bétail.",
  "Le col voisin est le passage le plus facile à travers les montagnes.",
  "Le port proche est essentiel au commerce.",
  "La rivière voisine est un axe commercial important.",
  "La source d’eau douce proche est précieuse dans cette région.",
  "Les terres sauvages au-delà sont pleines de menaces.",
  "Les terres environnantes font l’objet d’un vieux conflit territorial.",
  "Les terres environnantes sont considérées comme sacrées.",
  "Les environs abritent une herbe, un arbre ou une créature rare aux usages magiques."
]},
{"title": "d10 Les défenses extérieures du château comprennent...", "id": "d10thecastlesouterdefensesinclude", "roll": [
  "Des murs de pierre très hauts.",
  "Des murs de pierre incroyablement épais.",
  "Une série de courtines et de portes fortifiées.",
  "Une montée traîtresse pour atteindre les murs du château.",
  "Un fossé rempli d’eau putride.",
  "Un fossé rempli de boue épaisse qui aspire les bottes.",
  "Un fossé garni de pointes acérées.",
  "Un fossé abritant une ou plusieurs bêtes aquatiques dangereuses.",
  "Un immense barbacane.",
  "Une passerelle étroite menant à la poterne."
]},
{"title": "d6 Les défenses du donjon intérieur comprennent...", "id": "d6theinnerkeepsdefensesinclude", "roll": [
  "Des centaines de meurtrières.",
  "L’un des plus grands systèmes de double herse au monde.",
  "Une montée sinueuse pour atteindre l’entrée.",
  "Plusieurs parapets couverts avec des mâchicoulis sous lesquels les intrus doivent passer.",
  "Une large cour intérieure entourée de tours flanquantes intégrées à la courtine.",
  "Un moyen d’entrée inhabituel ou dissimulé."
]},
{"title": "d8 Le château peut être défendu efficacement par au moins...", "id": "d8thecastlecanbeheldeffectivelybyasfewas", "roll": [
  "5 soldats et 20 archers.",
  "20 soldats, 5 chevaliers et 20 archers.",
  "50 soldats, 10 chevaliers et 40 archers.",
  "20 chevaliers, 20 archers et 5 mages de guerre.",
  "100 soldats, 50 archers et 5 mages de guerre.",
  "100 soldats, 20 chevaliers et 50 archers.",
  "200 soldats, 50 chevaliers et 100 archers.",
  "200 soldats, 100 chevaliers et 200 archers."
]},
{"title": "d6 En plus de sa garnison, le château peut stocker suffisamment de vivres pour résister à un siège de trois mois pour...", "id": "d6inadditiontoitsgarrisonthecastlecanholdfoodstorestowithstandathreemonthsiegeforupto", "roll": [
  "50 personnes.",
  "100 personnes.",
  "200 personnes.",
  "500 personnes.",
  "1 000 personnes.",
  "2 000 personnes."
]},
{"title": "d12 Le château est connu pour...", "id": "d12thecastleisknownfor", "roll": [
  "Avoir résisté à un siège long et éprouvant.",
  "Avoir subi un immense incendie.",
  "Avoir changé de mains plusieurs fois au cours d’une même guerre.",
  "Porter malheur à ceux qui le possèdent.",
  "Être hanté par un ancien occupant.",
  "N’avoir jamais été pris lors d’un siège.",
  "Accueillir les voyageurs en quête de refuge.",
  "Refuser l’entrée aux voyageurs en quête de refuge.",
  "Son style architectural inhabituel.",
  "Ses magnifiques tapisseries historiques.",
  "Sa chapelle d’une beauté à couper le souffle.",
  "La qualité de ses repas."
]},
{"title": "d12 Ce que l’on dit être caché dans le château...", "id": "d12whatisrumoredtobehiddeninthecastle", "roll": [
  "Un tunnel souterrain servant de voie d’évasion de la dernière chance.",
  "L’arme d’un héros mort depuis longtemps.",
  "La tête conservée d’un ancien vilain.",
  "Un artefact religieux perdu de longue date.",
  "Un seigneur ou une dame porté(e) disparu(e).",
  "Un livre de malédictions infâmes.",
  "Un livre de secrets sombres et anciens.",
  "Un trésor maudit.",
  "La dernière bouteille d’un millésime de vin célèbre.",
  "Une œuvre perdue d’un artiste renommé.",
  "La crypte d’un ancien souverain.",
  "Un œuf de dragon non éclos."
]},
{"title": "d20 Pièces : Cette salle est...", "id": "d20roomsthischamberis", "roll": [
  "Une antichambre ou salle d’attente.",
  "Une armurerie.",
  "Une volière, colombier, chouetterie ou corbeautière.",
  "Une salle de banquet.",
  "La caserne.",
  "Un bain ou des latrines.",
  "Une chambre (d3) : 1. simple ; 2. confortable ; 3. luxueuse.",
  "Une chapelle ou un sanctuaire.",
  "Une crypte.",
  "Une salle à manger intime ou informelle.",
  "Un dressing.",
  "Une galerie (d6) : 1. armures et armes ; 2. peintures ; 3. sculptures ; 4. tapisseries ; 5. trophées de chasse ; 6. trophées de guerre.",
  "Une salle de garde.",
  "Un chenil, une ménagerie ou une écurie.",
  "La cuisine.",
  "Une bibliothèque ou un bureau.",
  "Un garde-manger.",
  "Un débarras pour les provisions courantes ou une citerne d’eau potable.",
  "La salle du trône.",
  "Une chambre forte (probablement cachée et/ou piégée)."
]},
{"title": "d20 Éléments : Vous remarquez...", "id": "castled20featuresyounotice", "roll": [
  "Un fauteuil flanqué de deux appliques murales.",
  "Une grande armoire ou un buffet.",
  "Un banc avec un coussin.",
  "Un brasero.",
  "Un candélabre sur une grande table.",
  "Une chaise simple près d’une fenêtre.",
  "Un lourd coffre en bois.",
  "Une commode avec une couverture posée dessus.",
  "Un bureau avec quelques plumes et parchemins.",
  "Une cheminée avec une tablette de cheminée.",
  "Une cheminée avec un petit tas de bois.",
  "Une fresque avec un fauteuil rembourré en dessous.",
  "Le portrait d’un noble.",
  "Une peinture de paysage ou de scène marine.",
  "Un buste sur un piédestal.",
  "Une étagère contenant des livres ou bibelots.",
  "Une table basse devant un petit canapé.",
  "Une grande table sous un lustre.",
  "Une tapisserie ornée.",
  "Un petit bassin mural avec une fontaine."
]},
{"title": "d10 En état de siège : Vous tombez sur...", "id": "d10undersiegeyoucomeupon", "roll": [
  "Une escouade d’archers montant précipitamment un escalier.",
  "Une patrouille de gardes brandissant leurs armes.",
  "Un garde criant des instructions.",
  "Un chevalier se hâtant vers les écuries.",
  "Un domestique recroquevillé dans une cachette.",
  "Un enfant curieux regardant par une fenêtre.",
  "Un domestique agenouillé en prière.",
  "Un noble rédigeant à la hâte une lettre.",
  "Un écuyer aidant un chevalier à enfiler son armure.",
  "Un guérisseur vérifiant ses potions."
]},
{"title": "d10 En temps de paix : Vous tombez sur...", "id": "d10inpeaceyoucomeupon", "roll": [
  "Le veneur nettoyant une prise récente.",
  "Le maître-chenil menant un chien en laisse.",
  "Le palefrenier instruisant un jeune cavalier.",
  "L’armurier réprimandant un apprenti.",
  "Une servante s’affairant autour de la robe de sa dame.",
  "Le précepteur ou le sage plongé dans un livre.",
  "Le chapelain chuchotant avec une servante.",
  "Une servante astiquant un bouclier ornemental.",
  "Un domestique portant un plateau de nourriture.",
  "Plusieurs archers s’entraînant dans la cour."
]},
{"title": "d6 Le donjon est situé...", "id": "d6thedungeonislocated", "roll": [
  "Dans une tour séparée du château principal.",
  "Sous le donjon.",
  "Dans une tour flanquante du château.",
  "Sous une tour flanquante du château.",
  "Dans une tour d’angle du château.",
  "Sous la tour d’angle."
]},
{"title": "d4 Le donjon a été construit...", "id": "d4thedungeonwasbuilt", "roll":[
  "Dans le cadre de la construction originale du château.",
  "Ajouté plus tard.",
  "Initialement pour un tout autre usage.",
  "Bien avant la majeure partie du château."
]},
{"title": "d8 Le donjon est...", "id": "d8thedungeonis", "roll":[
  "Un labyrinthe tentaculaire de couloirs sinueux.",
  "Un labyrinthe tentaculaire de passages étroits.",
  "Organisé en petites rangées soignées de cellules ou de fosses.",
  "Organisé autour d’un grand bloc cellulaire central ou d’une fosse.",
  "Composé de seulement quelques pièces.",
  "Une suite interminable de longs couloirs.",
  "Une suite interminable de petites pièces et d’escaliers.",
  "Une série de couloirs aux plafonds très bas."
]},
{"title": "d10 Les prisonniers sont enfermés dans...", "id": "d10prisonersareheldwithin", "roll":[
  "Des cellules individuelles, en isolement complet.",
  "Des cellules individuelles, mais ils peuvent voir et entendre d’autres prisonniers.",
  "Des cellules individuelles, mais ils peuvent entendre d’autres prisonniers.",
  "Des cellules pouvant accueillir jusqu’à deux prisonniers.",
  "Des cellules pouvant accueillir jusqu’à deux prisonniers, chacun enchaîné au mur.",
  "Des cellules pouvant accueillir jusqu’à quatre prisonniers.",
  "Des cellules pouvant accueillir jusqu’à quatre prisonniers, chacun enchaîné au mur.",
  "Une grande salle avec de nombreux autres prisonniers, tous enchaînés au mur.",
  "Des puits ou fosses individuels, ouverts par le haut.",
  "Une ou plusieurs fosses immenses avec de nombreux autres prisonniers."
]},
{"title": "d4 L’état des cellules (ou des fosses) est...", "id":"d4thecellsorpitsconditionis", "roll":[
  "Bien entretenu ; les murs sont solides.",
  "Vieux mais robustes ; les murs présentent quelques fissures.",
  "Décrépits ; les murs s’effritent.",
  "Tellement sombre qu’il est difficile de dire."
]},
{"title": "d4 Les prisonniers sont traités...", "id":"d4prisonersaretreated", "roll":[
  "Humainement ; ils reçoivent des repas décents, un peu d’exercice et des soins si nécessaire.",
  "Comme des chiens ; ils reçoivent des repas de mauvaise qualité et juste assez de soins pour survivre.",
  "Comme des rats ; ils mangent très mal et sont rongés par la maladie.",
  "Comme s’ils n’existaient pas ; parfois, on leur donne à manger."
]},
{"title": "d10 La prison est connue pour...", "id":"d10thedungeonisknownfor", "roll":[
  "La mort de nombreux prisonniers à cause d’une terrible épidémie.",
  "Une évasion massive dans le passé.",
  "L’évasion d’un criminel célèbre.",
  "Avoir été le dernier lieu de détention d’un criminel célèbre.",
  "Avoir été le dernier lieu de repos d’un héros légendaire.",
  "Être hantée par des fantômes vengeurs.",
  "Ses fosses de torture horribles.",
  "N’avoir jamais subi d’évasion réussie.",
  "Son geôlier excentrique.",
  "La qualité de ses repas."
]},
{"title": "d8 Selon la rumeur, dans le donjon du château se trouve...", "id":"d8accordingtorumorwithinthecastlesdungeonlies", "roll":[
  "Un tunnel secret menant vers l’extérieur.",
  "Les ossements d’un héros disparu depuis longtemps.",
  "La tête conservée d’un ancien scélérat.",
  "Une terrible bête à laquelle on donne les prisonniers en pâture.",
  "Un seigneur ou une dame porté disparu.",
  "Un joyau célèbre caché par un prisonnier notoire.",
  "Un dispositif de torture unique et épouvantable.",
  "Les ossements d’un roi ou d’une reine déchu(e)."
]},
{"title": "d10 Pièces : Cette salle est...", "id":"castledungeond10roomsthischamberis", "roll":[
  "Une cellule de donjon.",
  "Une autre cellule de donjon.",
  "Un passage reliant les blocs cellulaires.",
  "Une salle de garde.",
  "La caserne.",
  "Les quartiers du geôlier.",
  "Une cour ou un grand espace intérieur pour l’exercice.",
  "Une petite salle à manger.",
  "Une salle d’interrogatoire.",
  "Une salle de torture.",
]},
{"title": "d20 Éléments : Vous remarquez...", "id":"castledungeond20featuresyounotice", "roll":[
  "Une porte en bois renforcée de bandes d'acier.",
  "Des barreaux d'acier là où vous attendiez un mur de pierre.",
  "Des menottes vides le long du mur.",
  "Un support vide pour torche.",
  "Une lumière de torche au loin.",
  "Le sol est irrégulier.",
  "Une fissure dans le sol de pierre.",
  "Une souris qui file sous vos pieds.",
  "La puanteur de chair en décomposition.",
  "L'odeur d'urine stagnante.",
  "Une odeur putride.",
  "Une odeur humide et moisie.",
  "Un gémissement inconfortable.",
  "Un léger bruit de grattement.",
  "Un étrange bruit de tapotement.",
  "Des couinements de rats.",
  "Des cris lointains.",
  "Des hurlements d’agonie.",
  "Des hurlements horrifiques.",
  "Le cliquetis de chaînes.",
]},
{"title": "d12 Rencontres en Fuite : Vous tombez sur...", "id":"d12escapeencountersyoucomeupon", "roll":[
  "Un garde ou geôlier en train de somnoler.",
  "Une paire de gardes en patrouille.",
  "Un groupe de quatre gardes jouant aux cartes ou aux dés pendant leur pause.",
  "Une meute de chiens de chasse entraînés, dirigée par un garde haut gradé alerté de la tentative d’évasion.",
  "Un inquisiteur présent pour interroger un autre prisonnier dans une affaire sans lien.",
  "Un hurlement perçant d’une servante.",
  "Une large cour bien éclairée à traverser, sous la surveillance de gardes dans les tours.",
  "Un mur élevé bloquant directement le chemin de fuite.",
  "Une fenêtre grillagée sur le trajet de fuite.",
  "Les cuisines infestées de rats.",
  "Un noble emprisonné qui propose de vous aider si vous l’aidez à s’échapper.",
  "Un voleur emprisonné assoiffé de vengeance."
]},
{"title": "d10 Entrée : L’ouverture de la caverne est...", "id": "d10entrancelouverturedelacaverneest", "roll": [
  "Large et haute, laissant entrer beaucoup de lumière du jour dans la salle d’entrée.",
  "Un large gouffre.",
  "Un passage étroit facile à repérer.",
  "Un tunnel en pente raide et glissante.",
  "Un tunnel d’origine artificielle.",
  "Un tunnel effondré, infranchissable sans excavation.",
  "Marquée de plusieurs panneaux d’avertissement.",
  "Cachée par le terrain (d4) : 1. quelques rochers ; 2. une cascade ; 3. un surplomb rocheux ; 4. une butte.",
  "Cachée par la végétation (d4) : 1. un buisson d’épines ; 2. un rideau de mousse ; 3. d’énormes racines d’arbre ; 4. des lianes envahissantes.",
  "Difficile d’accès (d4) : 1. en haut ou en bas d’une falaise ; 2. au fond d’un trou profond ; 3. dans un tunnel sous-marin ; 4. derrière un mur ou rocher illusoire."
]},
{"title": "d50 Créatures : Qui vit dans la caverne ?", "id":"d50creaturesquivitsdanslacaverne", "roll": [
  "Bullywug.",
  "Rampe-charogne.",
  "Chuul.",
  "Voileur.",
  "Griffe rampante.",
  "Cyclope.",
  "Mante des ténèbres.",
  "Dragon d’ombre.",
  "Drider.",
  "Duergar.",
  "Elfes noirs.",
  "Ettin.",
  "Fomorien.",
  "Champignons.",
  "Galeb duhr.",
  "Gargouille.",
  "Fantôme.",
  "Goule.",
  "Géant des collines.",
  "Géant de pierre.",
  "Bavemur.",
  "Gobelins.",
  "Grell.",
  "Grick.",
  "Grimlock.",
  "Hobgobelins.",
  "Horreur à crochets.",
  "Kobolds.",
  "Méphites.",
  "Mimique.",
  "Myconides.",
  "Ogres.",
  "Limon.",
  "Orques.",
  "Otyugh.",
  "Piqueur.",
  "Ver pourpre.",
  "Agrippeur.",
  "Monstre rouilleur.",
  "Ombre.",
  "Squelette.",
  "Spectre.",
  "Stirge.",
  "Troglodyte.",
  "Troll.",
  "Hulk ombreux.",
  "Revenant.",
  "Xorn.",
  "Yuan-ti.",
  "Zombies."
]},
{"title": "d10 Écologie : La créature est...", "id":"d10ecologielacreatureest", "roll": [
  "Un prédateur ou un chasseur.",
  "Une source de nourriture pour d'autres habitants.",
  "Un squatteur ou envahisseur récemment arrivé.",
  "Un résident de longue date.",
  "Un parasite ou un charognard.",
  "Un hôte ou l'espèce dominante.",
  "Anormalement abondante.",
  "Vivante dans un isolement délibéré.",
  "Vivante dans un isolement involontaire.",
  "Totalement déplacée dans cette caverne."
]},
{"title": "d20 Point remarquable : Vous voyez...", "id":"cavernd20distinguishinglandmarkyousee", "roll": [
  "Un filet d’eau s’écoulant le long des murs et sur le sol.",
  "Un lac souterrain d’eau potable.",
  "Une flaque d’eau stagnante.",
  "Un pont naturel au-dessus d’un gouffre.",
  "Un gouffre étroit dont les parois sont assez proches pour permettre de grimper entre elles.",
  "Un gouffre profond dont on ne voit pas le fond.",
  "Un puits dans le plafond sans lumière visible.",
  "Un puits dans le plafond d’où filtre une lumière diffuse.",
  "Un groupe de stalagmites disposées en cercle.",
  "Une formation de deux grandes stalactites et deux grandes stalagmites, évoquant des crocs dans une gueule béante.",
  "Une paire de colonnes naturelles.",
  "Une grande stalactite brisée tombée du plafond.",
  "Une série de nombreuses petites stalactites accrochées au plafond.",
  "Un mur humide couvert de moisissure douce.",
  "Une niche murale couverte de moisissure visqueuse.",
  "Une grande zone de champignons lumineux.",
  "Une large zone de petits champignons.",
  "Un groupe de champignons gigantesques.",
  "Une vaste caverne à l’écho puissant.",
  "Un tunnel oppressant au plafond bas."
]},
{"title": "d12 Éléments remarquables : Vous remarquez...", "id":"cavernd12featuresyounotice", "roll": [
  "Une cache abandonnée d’équipements de mine en mauvais état.",
  "Quelques vieux os desséchés.",
  "De nombreux os sous vos pieds.",
  "Des traces d’un campement récent.",
  "Une immense toile d’araignée.",
  "Une large zone glissante de moisissure au sol.",
  "Le fracas de pierres qui tombent.",
  "Des pierres instables sous vos pieds.",
  "Un plafond instable.",
  "Un son lointain — un cri, des coups de marteau, des pas ou des tambours.",
  "Le nom d’un ancien voyageur gravé dans un mur.",
  "Plusieurs runes anciennes gravées dans la paroi."
]},
{"title": "d12 La paroi de la caverne est...", "id":"d12thecavewallis", "roll": [
  "Légèrement humide.",
  "Dégoulinante d’eau.",
  "Glissante à cause de la moisissure.",
  "Couverte de champignons mous.",
  "Sèche comme un os.",
  "Rugueuse et sèche.",
  "Sèche et lisse.",
  "Dentelée.",
  "Criblée de petits trous.",
  "Friable, avec des morceaux qui s’effritent.",
  "Friable, avec de gros blocs qui tombent au toucher.",
  "Couverte d’une bave indéfinissable."
]},
{"title": "d6 Le plafond de la caverne est...", "id":"d6thecaveceilingis", "roll": [
  "D’un inconfortable proche de votre tête.",
  "Couvert de stalactites (attention à votre tête !).",
  "Lisse comme du verre.",
  "Rugueux et irrégulier.",
  "Relié au sol par des colonnes naturelles.",
  "Si haut qu’il est difficile à distinguer."
]},
{"title": "d6 Dangers/Obstacles : Vous trouvez...", "id":"d6hazardsobstaclesyoufind", "roll": [
  "Une colonie de champignons vénéneux.",
  "Une zone de moisissure toxique.",
  "Le plafond s’effondre.",
  "Plusieurs rochers dégringolent d’un mur en pente.",
  "Le sol est très glissant.",
  "Votre pied manque le sol alors que vous tombez dans une fosse ou un gouffre."
]},
{"title": "d12 Voyageurs/Visiteurs : Vous tombez sur...", "id":"d12travelersvisitorsyoucomeupon", "roll": [
  "Un explorateur (d4) : 1. duergar ; 2. gobelin ; 3. humain ; 4. kobold.",
  "Un esclave évadé (d6) : 1. nain ; 2. gobelin ; 3. gnome ; 4. halfelin ; 5. humain ; 6. kobold.",
  "Un cueilleur (d4) : 1. duergar ; 2. gobelin ; 3. kobold ; 4. orque.",
  "Un criminel en fuite (d4) : 1. hérétique ; 2. meurtrier ; 3. contrebandier ; 4. voleur.",
  "Un chasseur de trésor égaré (d4) : 1. nain ; 2. demi-elfe ; 3. elfe hautain ; 4. humain.",
  "Un cartographe (d4) : 1. nain ; 2. gobelin ; 3. gnome ; 4. svirfneblin.",
  "Un messager (d4) : 1. elfe noir ; 2. gobelin ; 3. gnome ; 4. svirfneblin.",
  "Un mineur (d6) : 1. nain ; 2. gnome ; 3. gobelin ; 4. humain ; 5. kobold ; 6. svirfneblin.",
  "Un prospecteur (d4) : 1. nain ; 2. gnome ; 3. humain ; 4. svirfneblin.",
  "Un éclaireur (d4) : 1. elfe noir ; 2. gobelin ; 3. kobold ; 4. orque.",
  "Un soldat (d6) : 1. elfe noir ; 2. duergar ; 3. nain ; 4. gobelin ; 5. kobold ; 6. orque.",
  "Un espion (d4) : 1. elfe noir ; 2. duergar ; 3. gobelin ; 4. kobold."
]},
{"title": "d20 La mine est une source de...", "id":"d20themineisasourceof", "roll": [
  "Craie.",
  "Charbon.",
  "Cuivre.",
  "Or.",
  "Fer.",
  "Plomb.",
  "Chaux.",
  "Nickel.",
  "Platine.",
  "Sel.",
  "Argent.",
  "Zinc.",
  "Diamants.",
  "Émeraudes.",
  "Jade.",
  "Rubis.",
  "Saphirs.",
  "Turquoise.",
  "Autres gemmes (d6) : 1. améthyste ; 2. aigue-marine ; 3. grenat ; 4. opale ; 5. péridot ; 6. tanzanite ; 7. topaze ; 8. zircon.",
  "Un métal particulièrement rare (d3) : 1. adamantium ; 2. mithral ; 3. orium."
]},
{"title": "d12 Entrée : L’entrée de la mine est...", "id":"d12entrancetheminesentranceis", "roll":[
  "En haut d’un sentier sinueux depuis un camp ou un village.",
  "En haut d’un sentier escarpé depuis un camp ou un village.",
  "Une large bouche de caverne naturelle.",
  "Une grande fosse à ciel ouvert.",
  "Un passage étroit facile à repérer.",
  "Un tunnel en pente raide et glissante.",
  "Un tunnel renforcé de poutres en bois.",
  "Un tunnel partiellement effondré, infranchissable sans excavation.",
  "Marquée par plusieurs panneaux.",
  "Cachée par le terrain (d4) : 1. des rochers ; 2. une cascade ; 3. un surplomb rocheux ; 4. une butte.",
  "Cachée par la végétation (d4) : 1. un buisson épineux ; 2. un rideau de mousse ; 3. d’énormes racines d’arbres ; 4. des lianes envahissantes.",
  "Difficile d’accès (d4) : 1. en haut ou en bas d’une falaise ; 2. au fond d’un trou profond ; 3. dans un tunnel sous-marin ; 4. à travers un rocher ou un mur illusoire."
]},
{"title": "d6 La majorité de la mine est...", "id":"d6mostofthemineis", "roll":[
  "Un labyrinthe tentaculaire de tunnels sinueux.",
  "Un labyrinthe tentaculaire de tunnels étroits.",
  "Une série de tunnels reliant de grandes cavernes naturelles.",
  "Une grande carrière à ciel ouvert.",
  "Une série de tunnels reliant de grandes fosses ou dolines.",
  "Un labyrinthe tentaculaire de tranchées ouvertes."
]},
{"title": "d8 Le matériau extrait de la mine est...", "id":"d8materialexcavatedfromthemineis", "roll":[
  "Transporté sur des radeaux descendant un ruisseau ou une rivière.",
  "Transporté à dos de mulets.",
  "Transporté dans des chariots tirés par des mulets.",
  "Transporté par de robustes poneys.",
  "Transporté dans des chariots tirés par des bœufs.",
  "Transporté sur le dos de bêtes de somme inhabituelles (d4) : 1. ours ; 2. lézards géants ; 3. chèvres ; 4. chevaux morts-vivants.",
  "Transporté dans des wagonnets individuels.",
  "Transporté dans de longs trains de wagonnets."
]},
{"title": "d10 Dangers/Obstacles : Vous trouvez...", "id":"d10hazardsobstaclesyoufind", "roll":[
  "Une colonie de champignons vénéneux.",
  "Une plaque de moisissure toxique.",
  "Un effondrement soudain.",
  "Plusieurs rochers dévalent une paroi en pente.",
  "Le sol est très glissant.",
  "Votre pied rate le sol et vous tombez dans un puits ou un gouffre.",
  "Un tas d'explosifs instables.",
  "Une explosion soudaine dans une autre partie de la mine secoue le sol.",
  "Le sol grouille de vermine (d4) : 1. scarabées ; 2. mille-pattes ; 3. rats ; 4. araignées.",
  "Le tunnel ou la tranchée est lentement inondé."
]},
{"title": "d20 Créatures : Si vous creusez profondément, vous trouverez...", "id":"d20denizensifyoudigdeepyoullfind", "roll":[
  "Rampe-charogne.",
  "Voileur (cloaker).",
  "Ténébrufus (darkmantle).",
  "Drider.",
  "Champignons.",
  "Gargouille.",
  "Fantômes.",
  "Gricks.",
  "Horreur à crochets.",
  "Mimiques.",
  "Myconides.",
  "Gelée ou autre limon.",
  "Otyugh.",
  "Perceur.",
  "Ropeur.",
  "Monstre rouilleur.",
  "Squelettes.",
  "Stirges.",
  "Hulk des ombres.",
  "Revenants (wraiths)."
]},
{"title": "d12 Voisinage : Les mineurs se plaignent de problèmes causés par une colonie voisine de...", "id":"d12neighborstheminerscomplainoftroublefromanearbycolonyof", "roll":[
  "Cyclopes.",
  "Duergars.",
  "Nains.",
  "Elfes noirs.",
  "Gnomes des profondeurs.",
  "Gobelins.",
  "Grimlocks.",
  "Hobgobelins.",
  "Kobolds.",
  "Orques.",
  "Troglodytes.",
  "Trolls."
]},
{"title": "d20 Repère Distinctif : Vous voyez...", "id":"mined20distinguishinglandmarkyousee", "roll":[
  "Un filet d'eau qui s'écoule le long des murs et sur le sol.",
  "Un lac souterrain d'eau potable.",
  "Une mare d'eau stagnante.",
  "Un pont branlant au-dessus d'un gouffre.",
  "Un gouffre étroit dont les parois sont assez proches pour l'escalade.",
  "Un gouffre profond dont on ne voit pas le fond.",
  "Un groupe de rochers disposés en cercle.",
  "Un mur humide recouvert de moisissure douce.",
  "Une alcôve dans le mur, couverte de moisissure visqueuse.",
  "Une large plaque de champignons mous.",
  "Une caverne avec une forte résonance.",
  "Un tunnel exigu avec un plafond bas.",
  "Un embranchement avec des rails pour chariots de mine.",
  "Un chariot de mine renversé.",
  "Une lanterne éteinte fixée au mur.",
  "Une lanterne allumée fixée au mur.",
  "Une veine tourbillonnante de minerai visible dans le mur.",
  "Une large veine de minerai visible dans le mur.",
  "Un mur partiellement excavé, riche en minerai.",
  "Un tas de roche extraite."
]},
{"title": "d12 Éléments : Vous remarquez...", "id":"mined12featuresyounotice", "roll":[
  "Quelques équipements de mine cassés.",
  "De vieux os desséchés.",
  "Des traces d’un campement récent et bref.",
  "Des signes d’un camp abandonné.",
  "Une toile d’araignée immense.",
  "Une large zone glissante de moisissure sur le sol.",
  "Le fracas de pierres qui tombent.",
  "Des pierres instables sous vos pieds.",
  "Le bruit métallique d’une pioche frappant la roche.",
  "Le son lointain de marteaux en action.",
  "Une marque de prospecteur gravée sur le mur.",
  "Une poutre en bois fissurée au-dessus de votre tête."
]},
{"title": "d4 La mine est largement considérée comme...", "id":"d4themineiswidelybelievedtobe", "roll":[
  "Pleine de richesses.",
  "Un endroit productif pour creuser.",
  "De moins en moins rentable.",
  "Presque épuisée."
]},
{"title": "d8 La mine est contrôlée par...", "id":"d8themineiscontrolledby", "roll":[
  "Une puissante guilde marchande bien connue.",
  "Une maison noble riche.",
  "Un partenariat de quelques prospecteurs.",
  "Un clan ou un collectif de locaux.",
  "Personne en particulier ; premier arrivé, premier servi.",
  "Une cabale marchande secrète.",
  "Un seigneur de guerre ou un capitaine mercenaire brutal.",
  "Un chef de la pègre qui n’a jamais mis les pieds sur le site."
]},
{"title": "d6 La majorité des mineurs sont...", "id":"d6mostoftheminersare", "roll":[
  "Des hommes libres travaillant contre salaire.",
  "Des membres de bas rang d'une guilde.",
  "Payés avec une fraction de ce qu'ils extraient.",
  "Payés en crédit chez un marchand.",
  "Des prisonniers.",
  "Des esclaves."
]},
{"title": "d12 Les visiteurs du monastère viennent en quête de...", "id":"d12visitorstothemonasterycomeseeking", "roll":[
  "Connaissances anciennes.",
  "Sagesse mystique.",
  "Guidance spirituelle.",
  "Prières et soins.",
  "Bières et autres produits fabriqués sur place.",
  "Un refuge contre la guerre.",
  "Un abri lors d’un long voyage.",
  "Le secret du vrai bonheur.",
  "La perfection physique.",
  "Le moyen de voyager vers un autre royaume.",
  "Un entraînement dans un style de combat unique.",
  "Les outils et la formation pour assouvir une vengeance."
]},
{"title": "d12 Le monastère est connu pour...", "id":"d12themonasteryisknownforits", "roll":[
  "Ses guérisseurs compatissants.",
  "Sa musique sacrée.",
  "Sa sagesse ancienne.",
  "Ses sombres prophéties.",
  "Son architecture éblouissante.",
  "Son architecture inhabituelle.",
  "Une sculpture ou une peinture célèbre.",
  "Ses longues prières et veillées.",
  "Sa vaste bibliothèque et ses débats savants.",
  "Ses maîtres brasseurs ou vignerons.",
  "Ses mystiques puissants.",
  "Ses guerriers infatigables."
]},
{"title": "d8 Le complexe monastique est situé...", "id":"d8themonasterycomplexislocated", "roll":[
  "Au sommet d'une colline, loin de toute ville, mais avec un village en contrebas.",
  "Au sommet d'une colline non loin d'une grande ville.",
  "Au sommet d'une montagne isolée.",
  "Sur le flanc d'une montagne.",
  "Au cœur d'une forêt.",
  "Près d'une oasis dans le désert.",
  "Sous terre.",
  "Au cœur d'une ville."
]},
{"title": "d10 Le complexe monastique est...", "id":"d10themonasterycomplexis", "roll":[
  "Un groupe serré de bâtiments (ou de chambres).",
  "Un groupe de bâtiments avec des jardins, pelouses et cours entre les structures.",
  "Un groupe de bâtiments interconnectés.",
  "Un groupe de bâtiments entouré d'une clôture ou d'un muret.",
  "Un groupe de bâtiments entouré d'un mur de pierre défendable.",
  "Un seul grand bâtiment.",
  "Un grand bâtiment principal avec plusieurs bâtiments annexes à proximité.",
  "Une forteresse avec des murs, des tours de guet ou des postes de garde.",
  "Une série labyrinthique de petits bâtiments.",
  "Divisé symétriquement en deux ailes ou plus."
]},
{"title": "d4 Beaucoup des plafonds du monastère sont...", "id":"d4manyofthemonasterysceilingsare", "roll":[
  "Inconfortablement proches de votre tête.",
  "Reliés au sol par des colonnes.",
  "Peints de scènes mythologiques.",
  "Des dômes ou coupoles."
]},
{"title": "d6 Les bâtiments/pièces sont...", "id":"d6thebuildingschambersare", "roll":[
  "Décorés de statues.",
  "Décorés d’arcs et de colonnes en pierre.",
  "Des structures colorées en bois peint et plâtre.",
  "Des structures solides en bois travaillé.",
  "Des structures robustes en briques d’argile cuites au four.",
  "Derrière de grandes portes en métal (d6) : 1. laiton ; 2. bronze ; 3. or ; 4. fer ; 5. acier ; 6. étain."
]},
{"title": "d8 Beaucoup des murs intérieurs du monastère sont...", "id":"d8manyofthemonasterysinteriorwallsare", "roll":[
  "En pierre grossièrement taillée.",
  "En pierre finement taillée.",
  "En bois peint ou laqué.",
  "En bois brut non fini.",
  "Décorés de mosaïques complexes.",
  "Décorés de fresques élaborées.",
  "Décorés de sculptures en relief.",
  "Décorés de textes sacrés et de runes."
]},
{"title": "d10 Le monastère garde le secret de...", "id":"d10themonasteryguardsthesecretto", "roll":[
  "La paix dans le monde.",
  "La paix intérieure.",
  "L’illumination spirituelle.",
  "La conscience totale.",
  "L’apothéose.",
  "L’apocalypse.",
  "La transformation rituelle en avatar d’un dieu.",
  "L’ouverture d’un portail vers un autre royaume.",
  "La mort instantanée et irréversible.",
  "La pinte de bière parfaite."
]},
{"title": "d4 Le secret du monastère est connu de...", "id":"d4themonasteryssecretisknownto", "roll":[
  "Tout le monde, mais les détails sont cachés.",
  "Les moines qui accomplissent un service particulier.",
  "Plusieurs des maîtres du monastère.",
  "Un seul maître et un seul élève."
]},
{"title": "d12 Ce bâtiment/salle est...", "id":"d12thisbuildingchamberis", "roll":[
  "Une chapelle ou un sanctuaire.",
  "Un dortoir.",
  "Un cloître.",
  "Un réfectoire (salle à manger).",
  "Une bibliothèque.",
  "Un balnéaire (bains).",
  "Une infirmerie.",
  "Un sanatorium ou un hospice.",
  "Une école.",
  "Une forge.",
  "Une brasserie.",
  "Une grange."
]},
{"title": "d20 Éléments : Vous remarquez...", "id":"monasteryd20featuresyounotice", "roll":[
  "Un petit autel niché dans une alcôve du mur.",
  "Le son de cloches qui résonnent dans une tour.",
  "Une applique murale portant de nombreuses bougies.",
  "De hautes bougies sur des chandeliers plus hauts qu’un homme.",
  "Le tintement de carillons venant d’une pièce voisine.",
  "Une tapisserie représentant une scène mythologique.",
  "Une petite fontaine ou un bassin de réflexion.",
  "Le son d’un gong venant d’une autre pièce.",
  "Un grand symbole sacré incrusté dans le mur.",
  "Un énorme livre de textes ou de prières sacrées.",
  "Le parfum de l’encens brûlant à proximité.",
  "Un prie-Dieu placé sous une petite statue ou une icône.",
  "Une lampe à huile avec des panneaux de verre coloré.",
  "Une mosaïque incrustée dans le sol de la pièce.",
  "Une large fresque représentant une scène mythologique.",
  "Les conduites d’un système de plomberie courant le long du mur.",
  "Des robes et des tuniques suspendues à des crochets.",
  "Un tapis ornemental.",
  "Le son de chants provenant d’une autre pièce.",
  "Une statue d’une figure reconnaissable."
]},
{"title": "d12 Rencontres : Vous tombez sur...", "id":"d12encountersyoucomeupon", "roll":[
  "Un élève aux yeux brillants.",
  "Un élève exténué.",
  "Un novice patient.",
  "Un artiste martial féroce.",
  "Un enseignant dogmatique.",
  "Un érudit excentrique.",
  "Un vieux maître sage.",
  "Un voyageur venu de loin.",
  "Un membre du personnel de service du monastère.",
  "Un membre de la garde du monastère.",
  "Une énergie étrange.",
  "La sensation d’être observé."
]},
{"title": "d12 La prison est située...", "id":"d12theprisonislocated", "roll":[
  "Sur une petite île au large d’une côte isolée.",
  "Sur une petite île proche d’une ville.",
  "Dans une tour d’un château.",
  "Sous un complexe de temples.",
  "Dans une annexe d’un complexe de temples.",
  "Sous un hôtel de ville.",
  "Dans une annexe d’un hôtel de ville.",
  "Sous une ville, profondément enfouie.",
  "Derrière des murs, dans un lieu rural fortifié (d4) : 1. littoral ; 2. terres agricoles ; 3. pays minier ; 4. terres d’élevage.",
  "Sous terre, dans un lieu rural caché (d4) : 1. littoral ; 2. terres agricoles ; 3. pays minier ; 4. terres d’élevage.",
  "Derrière des murs, dans un lieu sauvage fortifié (d6) : 1. désert ; 2. forêt ; 3. collines ; 4. montagnes ; 5. marais ; 6. toundra.",
  "Sous terre, dans un lieu sauvage caché (d6) : 1. désert ; 2. forêt ; 3. collines ; 4. montagnes ; 5. marais ; 6. toundra."
]},
{"title": "d8 La prison a été construite par...", "id":"d8theprisonwasbuiltby", "roll":[
  "Un roi ou une reine sage.",
  "Un seigneur ou une dame ambitieux(se).",
  "Un tyran malveillant.",
  "Un comité civique.",
  "Un maire ou shérif populaire.",
  "Un roi ou une reine sans scrupules.",
  "Une guilde marchande prospère.",
  "Une puissante maison noble."
]},
{"title": "d6 Le complexe pénitentiaire est...", "id":"d6theprisoncomplexis", "roll":[
  "Un dédale tentaculaire de passages sinueux.",
  "Un dédale tentaculaire de passages étroits.",
  "Organisé en rangées de cellules ou de fosses petites et bien ordonnées.",
  "Organisé autour d’un grand bloc ou d’une grande fosse centrale.",
  "Une série interminable de longs couloirs.",
  "Une série de couloirs aux plafonds très bas."
]},
{"title": "d6 La prison est entourée de...", "id":"d6theprisonissurroundedby", "roll":[
  "Des murs de pierre très hauts.",
  "Des murs de pierre incroyablement épais.",
  "Un mur d’enceinte avec de nombreuses portes fortifiées.",
  "Un fossé rempli d’eau putride.",
  "Un fossé rempli de boue épaisse qui aspire les bottes.",
  "Un fossé rempli de piques acérées."
]},
{"title": "d10 Les prisonniers sont détenus dans...", "id":"d10prisonersareheldwithin", "roll":[
  "Des cellules individuelles, en isolement complet.",
  "Des cellules individuelles, mais ils peuvent voir et entendre d'autres prisonniers.",
  "Des cellules individuelles, mais ils peuvent entendre d'autres prisonniers.",
  "Des cellules pouvant accueillir jusqu'à deux prisonniers.",
  "Des cellules pouvant accueillir jusqu'à deux prisonniers, chacun enchaîné au mur.",
  "Des cellules pouvant accueillir jusqu'à quatre prisonniers.",
  "Des cellules pouvant accueillir jusqu'à quatre prisonniers, chacun enchaîné au mur.",
  "Une grande salle avec de nombreux autres prisonniers, chacun enchaîné au mur.",
  "Des puits ou fosses individuels, ouverts par le haut.",
  "Une ou plusieurs fosses géantes contenant de nombreux autres prisonniers."
]},
{"title": "d4 L'état des cellules (ou fosses) est...", "id":"d4thecellsorpitsconditionis", "roll":[
  "Bien entretenu ; les murs sont solides.",
  "Vétuste mais robuste ; les murs présentent quelques fissures.",
  "Décrépit ; les murs s'effritent.",
  "Tellement sombre qu’il est difficile de dire."
]},
{"title": "d4 Les prisonniers sont traités...", "id":"d4prisonersaretreated", "roll":[
  "Humainement ; ils reçoivent des repas corrects, un peu d’exercice et des soins si nécessaire.",
  "Comme des chiens ; ils reçoivent des repas de mauvaise qualité et juste assez de soins pour survivre.",
  "Comme des rats ; ils reçoivent des repas infects et sont en proie à la maladie.",
  "Comme s’ils n’existaient pas ; ils reçoivent de la nourriture de temps en temps."
]},
{"title": "d10 La prison est connue pour...", "id":"d10theprisonisknownfor", "roll":[
  "De nombreux prisonniers morts d'une terrible peste.",
  "Une évasion massive dans le passé.",
  "L'évasion d'un criminel célèbre.",
  "Avoir été la dernière demeure d'un criminel célèbre.",
  "Avoir été la dernière demeure d’un héros légendaire.",
  "Être hantée par des fantômes vengeurs.",
  "Ses fosses de torture horribles.",
  "N'avoir jamais subi d'évasion réussie.",
  "Son style architectural inhabituel.",
  "La qualité de ses repas."
]},
{"title": "d8 Selon la rumeur, à l’intérieur des murs de la prison se trouve...", "id":"d8accordingtorumorwithintheprisonswallslies", "roll":[
  "Un tunnel secret vers l’extérieur.",
  "Les ossements d’un hors-la-loi célèbre.",
  "La tête conservée d’un ancien méchant.",
  "Une terrible bête à laquelle on donne les prisonniers en pâture.",
  "Un seigneur ou une dame disparu(e).",
  "Un trésor volé par un prisonnier notoire.",
  "Un dispositif de torture unique et terrible.",
  "Les ossements d’un roi ou d’une reine déchu(e)."
]},
{"title": "d10 Pièces : Cette salle est...", "id":"prisond10roomsthischamberis", "roll":[
  "Une cellule de prison.",
  "Une autre cellule de prison.",
  "Un couloir reliant les blocs de cellules.",
  "Une salle de garde.",
  "La caserne.",
  "Les quartiers du geôlier.",
  "Une cour ou un grand espace intérieur pour l’exercice.",
  "Un réfectoire.",
  "Une salle d’interrogatoire.",
  "Une salle de torture."
]},
{"title": "d20 Éléments : Vous remarquez...", "id":"prisond20featuresyounotice", "roll":[
  "Une porte en bois renforcée de bandes d'acier.",
  "Des barreaux d'acier là où vous attendiez un mur de pierre.",
  "Des menottes vides le long du mur.",
  "Un porte-flambeau vide.",
  "Une lumière de torche lointaine.",
  "Le sol est irrégulier.",
  "Une fissure dans le sol en pierre.",
  "Une souris qui détale sous vos pieds.",
  "La puanteur de chair en décomposition.",
  "L'odeur d'urine stagnante.",
  "Une odeur putride.",
  "Une odeur de moisi et d’humidité.",
  "Un gémissement inconfortable.",
  "Un léger grattement.",
  "Un étrange bruit de tapotement.",
  "Les couinements de rats.",
  "Les cris lointains de voix.",
  "Des hurlements d’agonie.",
  "Des hurlements horribles.",
  "Le cliquetis de chaînes."
]},
{"title": "d12 Vous tombez sur...", "id":"d12youcomeupon", "roll":[
  "Un garde en train de somnoler.",
  "Une paire de gardes en patrouille.",
  "Un groupe de quatre gardes jouant aux cartes ou aux dés pendant leur pause.",
  "Une meute de chiens de chasse dressés, menée par un garde de haut rang alerté de la tentative d’évasion.",
  "Un officier de la loi présent pour interroger un autre prisonnier dans une affaire non liée.",
  "Une alarme stridente retentit.",
  "Une large cour bien éclairée qu’il faut traverser, sous le regard de gardes postés dans des tours.",
  "Un mur élevé bloquant la route d’évasion.",
  "Une fenêtre grillagée bloquant le passage.",
  "Les cuisines et le réfectoire infestés de rats.",
  "Un tueur en série emprisonné, également en train de tenter une évasion.",
  "Un voleur emprisonné, avide de vengeance."
]},
{"title": "d8 Le geôlier est...", "id":"d8thejaileris", "roll":[
  "Un lâche qui aime jouer les durs.",
  "Un tyran dans tous les sens du terme.",
  "Un bâtard issu d’une maison noble.",
  "Un homme ayant grandi parmi les criminels.",
  "Un prêtre avec un agenda puritain.",
  "Un horrible sadique.",
  "Un homme de foi doux et réservé.",
  "Un petit homme malfaisant."
]},
{"title": "d4 Le geôlier s'inquiète de...", "id":"d4thejailerisconcernedabout", "roll":[
  "Rumeurs d’une tentative d’évasion imminente.",
  "Perdre son emploi après la mort suspecte d’un prisonnier.",
  "Faire face à un prisonnier qui lui donne la chair de poule.",
  "Trouver un moyen de gagner un peu d’argent en plus."
]},
{"title": "d4 Le geôlier cherche à...", "id":"d4thejailerislookingto", "roll":[
  "Abuser de quelqu’un sans défense.",
  "Se sentir puissant.",
  "Entrer en contact avec un prisonnier perturbé.",
  "Échanger des récits macabres."
]},
{"title": "d8 Le geôlier porte...", "id":"d8thejailercarries", "roll":[
  "Un grand trousseau de clés.",
  "Un grand couteau et une matraque.",
  "Un seau de bouillie froide venant des cuisines.",
  "Un trophée pris à un prisonnier torturé.",
  "Un livre de prières de poche.",
  "Une massue cloutée.",
  "Un fouet ou un flagrum.",
  "Une outre de vin."
]},
{"title": "d4 Le garde a pris ce travail pour...", "id":"d4theguardtookthisjobfor", "roll":[
  "Le salaire stable.",
  "La possibilité d’intimider les autres.",
  "Prouver à quel point il est dur.",
  "Décharger son agressivité sur les criminels."
]},
{"title": "d4 Sur le visage du garde, il y a...", "id":"d4ontheguardsfaceis", "roll":[
  "Une cicatrice disgracieuse.",
  "Un sourire idiot.",
  "Un regard vide.",
  "Une grosse moustache."
]},
{"title": "d4 Le prisonnier a...", "id":"d4theprisonerhas", "roll":[
  "Une longue barbe hirsute.",
  "Une barbe clairsemée.",
  "La peau pendante sur les os.",
  "Des furoncles et des plaies sur la peau."
]},
{"title": "d6 Le prisonnier est ici parce que...", "id":"d6theprisonerisherebecause", "roll":[
  "Il a volé quelque chose.",
  "Il a tué quelqu’un.",
  "Il a violé quelqu’un.",
  "Il a prôné la rébellion et les troubles.",
  "Il a commis un acte de fraude.",
  "Il a été confondu avec quelqu’un d’autre."
]},
{"title": "d6 Les fidèles du temple prient...", "id":"d6worshipersatthetempleprayto", "roll":[
  "Un seul dieu, et uniquement lui.",
  "Un dieu principalement, mais d'autres dieux à l'occasion ou pour des demandes spécifiques.",
  "Plusieurs dieux d’un même panthéon, mais deux dieux se distinguent des autres.",
  "Un panthéon entier, chaque dieu étant prié selon les besoins.",
  "Un dieu auquel le temple n'était pas initialement dédié.",
  "Plusieurs dieux d’un panthéon auxquels le temple n'était pas initialement dédié."
]},
{"title": "d12 Le temple est dédié à...", "id":"d12thetempleisdedicatedto", "roll":[
  "Le dieu du soleil / du ciel.",
  "La déesse de la terre / la mère nourricière.",
  "La déesse des récoltes / des saisons.",
  "Le dieu de l’artisanat / de la connaissance.",
  "Le dieu des ténèbres / des secrets.",
  "Le dieu de la mort / du mal.",
  "La déesse de la chasse / des bois.",
  "La déesse de l’amour / de la beauté / de la fertilité.",
  "La déesse de la lune / de la magie.",
  "Le dieu des mers / des tempêtes.",
  "Le dieu farceur / messager.",
  "Le dieu tyran / de la guerre."
]},
{"title": "d12 Le temple est connu pour...", "id":"d12thetempleisknownforits", "roll":[
  "Des guérisseurs miraculeux.",
  "Des guérisseurs compatissants.",
  "De magnifiques prêtresses.",
  "Une musique merveilleuse.",
  "Des prophéties exactes.",
  "Une sagesse accumulée.",
  "Une architecture saisissante.",
  "Une architecture inhabituelle.",
  "Une incroyable collection d’œuvres d’art.",
  "Une sculpture ou une peinture célèbre.",
  "De longs services de prière et veillées.",
  "Des offices animés et des débats."
]},
{"title": "d6 L'entrée du temple est gardée par...", "id":"d6thetemplesentranceisguardedby", "roll":[
  "Un ordre juré de guerriers dévots.",
  "Des mercenaires.",
  "Des statues effrayantes d'êtres monstrueux.",
  "Des statues colossales impressionnantes de guerriers.",
  "Des statues de belles jeunes femmes, attirant les visiteurs dans un piège.",
  "Rien ; le temple accueille tout le monde."
]},
{"title": "d8 Le plan du sol principal du temple est...", "id":"d8thetemplesmainfloorplanis", "roll":[
  "Circulaire.",
  "Ellipsoïdal.",
  "Triangulaire.",
  "Carré.",
  "Rectangulaire.",
  "Pentagonal.",
  "Polygonal avec de nombreux côtés (d8) : 1. six ; 2. sept ; 3. huit ; 4. neuf ; 5. dix ; 6. douze ; 7. treize ; 8. vingt.",
  "En forme de croix."
]},
{"title": "d8 Le complexe du temple est...", "id":"d8thetemplecomplexis", "roll":[
  "Simple : une grande salle de culte principale avec quelques pièces fonctionnelles attenantes.",
  "Simple avec une grande annexe : l'annexe contient de nombreuses pièces.",
  "Simple avec des fortifications.",
  "À plusieurs niveaux : les niveaux supérieurs ou inférieurs sont inaccessibles à la plupart des visiteurs.",
  "À plusieurs ailes : certaines ailes sont inaccessibles à la plupart des visiteurs.",
  "Disposé de façon concentrique : les zones intérieures sont inaccessibles à la plupart des visiteurs.",
  "Labyrinthique : conçu pour délibérément désorienter les étrangers.",
  "Simple avec un complexe complexe caché sous la salle principale de culte."
]},
{"title": "d6 Le terrain du temple est dominé par...", "id":"d6thetemplegroundsaredominatedby", "roll":[
  "Des murs de pierre impénétrables.",
  "Une structure complexe d’arcs et de colonnes en pierre.",
  "Une structure colorée en bois peint et plâtre.",
  "Une structure robuste en bois travaillé.",
  "Une structure solide de briques cuites au four.",
  "Une grande structure avec d’immenses portes métalliques (d6) : 1. laiton ; 2. bronze ; 3. or ; 4. fer ; 5. acier ; 6. étain"
]},
{"title": "d8 Bon nombre des murs intérieurs du temple sont...", "id":"d8manyofthetemplesinteriorwallsare", "roll":[
  "En pierre brute taillée grossièrement.",
  "En pierre taillée lisse.",
  "En bois peint ou laqué.",
  "En bois franc non fini.",
  "Décorés de mosaïques complexes.",
  "Décorés de fresques élaborées.",
  "Décorés de sculptures en relief.",
  "Décorés de textes sacrés et de runes."
]},
{"title": "d6 Bon nombre des plafonds du temple sont...", "id":"d6manyofthetemplesceilingsare", "roll":[
  "Désagréablement bas, frôlant presque votre tête.",
  "Reliés au sol par des colonnes.",
  "Peints de scènes mythologiques.",
  "Si hauts qu’il est difficile d’en distinguer les détails.",
  "Voûtés.",
  "En dômes ou coupoles."
]},
{"title": "d20 La fonction de cette pièce est...", "id":"templed20thepurposeofthisroomis", "roll":[
  "Une armurerie ou une caserne.",
  "Une salle de garde ou un poste de sentinelle.",
  "Une cellule de prière solitaire.",
  "Une cellule pour détenir des prisonniers.",
  "Une chambre d'inquisition ou de torture.",
  "Un bureau de prêtre ou une salle d’audience.",
  "Un sanatorium ou une infirmerie.",
  "Un bassin, bain ou fontaine cérémoniel(le).",
  "Une morgue ou un funérarium.",
  "Une crypte pour une personne importante (d4) : 1. héros célèbre ; 2. grand prêtre puissant ; 3. prêtre obscur ; 4. noble fortuné.",
  "Une pièce dédiée à des rituels spécifiques (d4) : 1. conjurations ; 2. divinations ; 3. funérailles ; 4. miracles de guérison.",
  "Une chapelle ou un sanctuaire dédié à une divinité mineure, un saint ou un martyr.",
  "Une salle de classe ou un dortoir.",
  "Une bibliothèque.",
  "Les quartiers ou la salle d’habillage d’un prêtre.",
  "Une salle de banquet, un grand réfectoire ou une petite salle à manger.",
  "Une cuisine ou un garde-manger.",
  "Une salle des trophées ou une galerie d’art.",
  "Une écurie ou un chenil.",
  "Un atelier pour les artisans du temple."
]},
{"title": "d20 Éléments : Vous remarquez...", "id":"templed20featuresyounotice", "roll":[
  "Un petit autel placé dans une alcôve du mur.",
  "Le son des cloches résonnant depuis une tour.",
  "Une applique murale contenant de nombreuses bougies.",
  "De grandes bougies sur des chandeliers, plus hautes qu’un homme.",
  "Le tintement de carillons venant d’une pièce voisine.",
  "Une tapisserie représentant une scène mythologique.",
  "Une petite fontaine ou un bassin de réflexion.",
  "Le son d’un gong provenant d’une autre pièce.",
  "Un grand symbole sacré incrusté dans le mur.",
  "Un énorme livre de textes ou de prières sacrés.",
  "L’odeur d’encens brûlant à proximité.",
  "Un prie-Dieu placé sous une petite statue ou une icône.",
  "Une lampe à huile aux panneaux de verre coloré.",
  "Une mosaïque incrustée dans le sol de la pièce.",
  "Une large fresque ou peinture murale représentant une scène mythologique.",
  "Les tuyaux d’un immense orgue courant le long des murs.",
  "Des robes et des aubes suspendues à des crochets.",
  "Un tapis ornemental.",
  "Un paravent pour cacher les prêtres à la vue.",
  "Une statue d’une figure reconnaissable."
]},
{"title": "d6 Rencontres : Vous tombez sur...", "id":"d6encountersyoucomeupon", "roll":[
  "Un jeune prêtre ou une jeune prêtresse.",
  "Un vieux prêtre ou une vieille prêtresse.",
  "Un voyageur venu de loin.",
  "Un fidèle local habitué.",
  "Un membre du personnel de service du temple.",
  "Un membre de la garde du temple."
]},
{"title": "d20 Ce tombeau a été construit pour...", "id":"d20thistombwasbuiltfor", "roll":[
  "Un ancien roi.",
  "Une ancienne reine.",
  "Un ancien grand prêtre ou une grande prêtresse.",
  "Un ancien sorcier.",
  "Un puissant guerrier.",
  "Un terrible tyran.",
  "Un aventurier légendaire.",
  "Un héros de guerre célébré.",
  "Un roi ou une reine sans scrupules.",
  "Un maire ou chef de village vaniteux.",
  "Un puissant commandant militaire ou seigneur de guerre.",
  "Un puissant sorcier ou magicienne.",
  "Un prêtre ou une prêtresse puissant(e).",
  "Un souverain bien-aimé.",
  "Un riche marchand.",
  "Un membre d'une maison noble.",
  "Un membre de la famille royale.",
  "La femme d’un riche personnage ou dirigeant.",
  "La mère d’un riche personnage ou dirigeant.",
  "L’enfant d’un riche personnage ou dirigeant."
]},
{"title": "d12 L'entrée du tombeau est...", "id":"d12thetombsentranceis", "roll":[
  "Grande ouverte, laissant entrer beaucoup de lumière dans la chambre d’entrée.",
  "Derrière une énorme paire de portes en métal (d4) : 1. laiton ; 2. bronze ; 3. or ; 4. fer.",
  "Sous une dalle de pierre.",
  "Une simple porte en bois encadrée de pierre.",
  "Une lourde porte en bois encadrée de pierre.",
  "Derrière une lourde porte en pierre.",
  "Sous un arbre noueux et ancien.",
  "Sous un obélisque ou un monument similaire.",
  "Sous une grande statue.",
  "Camouflée par le terrain (d4) : 1. rochers ; 2. cascade ; 3. surplomb rocheux ; 4. butte.",
  "Camouflée par la végétation (d4) : 1. fourré d'épines ; 2. rideau de mousse ; 3. racines d’arbres énormes ; 4. vignes envahissantes.",
  "Difficile d’accès (d4) : 1. en haut ou en bas d'une falaise ; 2. dans un puits profond ; 3. dans un tunnel sous-marin ; 4. à travers un mur ou un rocher illusoire."
]},
{"title": "d10 L'entrée du tombeau est gardée par...", "id":"d10thetombsentranceisguardedby", "roll":[
  "Un ordre juré de guerriers dévots.",
  "Des mercenaires.",
  "De grandes statues effrayantes de bêtes (d8) : 1. chauves-souris ; 2. ours ; 3. dragons ; 4. aigles ; 5. lions ; 6. corbeaux ; 7. serpents ; 8. loups.",
  "Des statues colossales impressionnantes de guerriers.",
  "Des statues de belles jeunes femmes, attirant les visiteurs dans un piège.",
  "Plusieurs statues en ruine.",
  "Des guerriers squelettiques.",
  "Un agencement inquiétant d’ossements.",
  "Une bande de hors-la-loi qui explore prudemment ses secrets.",
  "Rien du tout ; le tombeau semble plutôt accueillant et chaleureux."
]},
{"title": "d6 La grande crypte du tombeau se trouve...", "id":"d6thetombsgrandcryptislocated", "roll":[
  "Juste derrière une lourde porte dans la salle d’entrée.",
  "En bas d’un escalier en colimaçon abrupt depuis la salle d’entrée.",
  "Au bout d’un long couloir bordé de cryptes secondaires.",
  "Au bout d’un long couloir bordé de statues.",
  "Au bout d’un long couloir bordé de passages menant à des cryptes secondaires.",
  "Plusieurs niveaux en dessous de la salle d’entrée."
]},
{"title": "d8 L’agencement du tombeau est...", "id":"d8thetombslayoutis", "roll":[
  "Simple : une grande crypte principale avec quelques cryptes et pièces secondaires attenantes.",
  "Simple avec une grande salle d’entrée ; la salle d’entrée mène à des cryptes secondaires et d’autres pièces.",
  "À plusieurs niveaux ; l’accès aux niveaux inférieurs est facile à trouver.",
  "À plusieurs niveaux ; l’accès aux niveaux inférieurs est difficile à trouver.",
  "À plusieurs ailes ; l’accès à certaines ailes est difficile à trouver.",
  "Une série de pièces disposées de façon concentrique ; la grande crypte se trouve parmi les pièces intérieures.",
  "Labyrinthique : conçue pour délibérément désorienter les intrus.",
  "Simple avec un complexe complexe caché sous la grande crypte."
]},
{"title": "d8 Beaucoup des murs intérieurs du tombeau sont...", "id":"d8manyofthetombsinteriorwallsare", "roll":[
  "En pierre brute taillée grossièrement.",
  "En pierre taillée lisse.",
  "En bois peint ou laqué.",
  "En bois dur non fini.",
  "Décorés de mosaïques complexes.",
  "Décorés de fresques élaborées.",
  "Décorés d’ossements et d’icônes de la mort.",
  "Décorés de textes sacrés et de runes."
]},
{"title": "d6 Beaucoup des plafonds du tombeau sont...", "id":"d6manyofthetombsceilingsare", "roll":[
  "Désagréablement proches de votre tête.",
  "En pierre, lisse comme du verre.",
  "En pierre, rugueux et irréguliers.",
  "Reliés au sol par des colonnes.",
  "Peints ou sculptés avec des scènes emblématiques.",
  "Traversés par des poutres en bois."
]},
{"title": "d6 On raconte que le tombeau...", "id":"d6thetombisrumoredto", "roll":[
  "Contient un trésor immense.",
  "Est lourdement piégé pour repousser les intrus.",
  "Abrite une arme ou un artefact légendaire.",
  "Inflige une puissante malédiction aux intrus.",
  "Renferme les restes de quelqu’un que l’on croyait perdu à jamais.",
  "A déjà été vidé de ses monstres et de son or par des chasseurs de trésors."
]},
{"title": "d20 La fonction de cette pièce est...", "id":"tombd20thepurposeofthisroomis", "roll":[
  "Une antichambre menant à une crypte ou une chapelle.",
  "Une chapelle dédiée à la protection des âmes des défunts.",
  "Une chapelle dédiée à l’accompagnement des âmes des défunts dans leur voyage.",
  "Une grande crypte pour une personne importante (d4) : 1. héros célèbre ; 2. grand prêtre ; 3. puissant noble ; 4. riche marchand.",
  "Une fausse crypte destinée à piéger les pilleurs de tombes.",
  "Une crypte pour les membres immédiats de la famille.",
  "Une crypte pour les générations précédentes de la famille.",
  "Une crypte pour l’époux(se) du défunt.",
  "Une crypte de tombes anonymes.",
  "Un bassin ou une fontaine de réflexion.",
  "Une crypte pour les serviteurs ou esclaves dévoués.",
  "Une salle dédiée à des rituels spécifiques (d3) : 1. divinations ; 2. funérailles ; 3. nécromancie.",
  "Une galerie dédiée au défunt (d3) : 1. trophées ; 2. statues ; 3. peintures.",
  "Une salle de garde avec des gardiens (d8) : 1. fantômes ; 2. golems ; 3. chevaliers ; 4. mercenaires ; 5. cultistes ; 6. squelettes ; 7. revenants ; 8. zombies.",
  "La pièce d’habillement d’un prêtre.",
  "Un local de rangement pour les outils d’embaumement.",
  "Un local de rangement pour l’entretien du tombeau.",
  "Un atelier d’embaumement des morts.",
  "Une crypte dissimulée derrière une porte secrète contenant la dépouille la plus importante du tombeau.",
  "Les quartiers ou vestiaire d’un prêtre."
]},
{"title": "d20 Éléments remarquables : Vous remarquez...", "id":"tombd20featuresyounotice", "roll":[
  "Un petit autel installé dans une alcôve du mur.",
  "Une plaque énumérant une lignée familiale.",
  "Une plaque indiquant les dates de naissance et de décès.",
  "Un applique murale tenant plusieurs bougies.",
  "Un applique murale vide prévue pour une torche.",
  "Une puanteur de terre pourrie.",
  "Une odeur de moisi et de moisissure.",
  "L’odeur de chair en décomposition.",
  "Une fresque représentant une scène mythologique.",
  "Une petite fontaine ou un bassin de réflexion.",
  "Un immense livre de textes ou prières sacrés.",
  "Une lampe à huile ornée.",
  "Une mosaïque incrustée dans le sol de la pièce.",
  "Une grande fresque ou peinture murale représentant une scène mythologique ou historique.",
  "Un sarcophage doré.",
  "Un sarcophage de pierre simple.",
  "Un cercueil en bois massif finement ouvragé.",
  "Un cercueil en bois simple et solide.",
  "Un cercueil de pierre marqué par des dates.",
  "Un cercueil vide."
]},
{"title": "d20 Qu'est-ce qui hante ce tombeau ?", "id":"d20whathauntsthistomb", "roll":[
  "Un essaim de griffes rampantes.",
  "Un revenant cupide.",
  "Un ancien demi-liche.",
  "Des fantômes malveillants.",
  "Des guerriers zombies.",
  "Un chien squelette.",
  "Un vampire nouvellement transformé.",
  "Un vampire ancien.",
  "Un énorme tas d’ossements animé.",
  "Des squelettes humanoïdes tordus.",
  "Un zombie issu d’un aventurier tombé au combat.",
  "Une momie haineuse.",
  "Des gardiens squelettiques.",
  "Des soldats fantômes.",
  "Le fantôme d’une belle jeune fille.",
  "Des goules affamées.",
  "Un spectre fou.",
  "Un fantôme joueur.",
  "Un lanceur de sorts traître devenu liche.",
  "Un chevalier de la mort vengeur."
]},
{"title": "d12 Habitants : Qui vit dans le tombeau maintenant ?", "id":"d12denizenswhatlivesinthetombnow", "roll":[
  "Rampeur charognard.",
  "Cloaker (voile d’ombre).",
  "Mante obscure.",
  "Champignons.",
  "Mimics (imitateurs).",
  "Myconides.",
  "Gelée ou autre substance visqueuse.",
  "Otyugh.",
  "Perceur.",
  "Ropeur.",
  "Stirges (sangsues volantes).",
  "Hulk des ombres."
]},
{"title": "d8 Visiteurs : Qui est entré récemment dans le tombeau ?", "id":"d8visitorswhohasenteredthetomboflate", "roll":[
  "Un vieux prêtre ou une vieille prêtresse dévoué(e).",
  "Un jeune prêtre ou une jeune prêtresse curieux(se).",
  "Un voyageur ou un érudit venu de loin.",
  "Un membre de la famille du défunt.",
  "Un chasseur de trésors cupide.",
  "Un étudiant en nécromancie.",
  "Un tueur en série en fuite.",
  "Un aventurier brave mais imprudent."
]},



// end of dungeons

];
