// settlements.js
//

top.settlements = [



 {"title": "d100 Verbe", "id":"d100verb_tavernnames", "roll":[
"Noyade",
"Pendaison",
"Roter",
"Courir",
"Marcher",
"Chasser",
"Combattre",
"Balancer",
"Casser",
"Travailler",
"Fermenter",
"Fleurir",
"S'inquiéter",
"Suivre",
"Couler",
"Se plaindre",
"Se tenir debout",
"Rigoler",
"Rire",
"Haleter",
"Embarquer",
"Se prélasser",
"Couper",
"Chanter",
"Fixer",
"Pousser",
"Décevoir",
"Hésiter",
"Lier",
"Tourner",
"Fendre",
"Désirer",
"Bousiller",
"Bousculer",
"Trébucher",
"Se languir",
"Geindre",
"Voler",
"Entasser",
"Prostituer",
"Faire la guerre",
"Cligner de l'œil",
"Grignoter",
"Glisser",
"Ronfler",
"Renifler",
"Jouer",
"Pratiquer",
"Attraper",
"Brûler",
"Enflammé",
"Geler",
"Empoisonner",
"Enterrer",
"Lancer",
"Étinceler",
"Vapeur",
"Frapper",
"Chiffonner",
"Bavarder",
"Marmonner",
"Rugir",
"Labourer",
"Mordre",
"Hurler",
"Rugir",
"Crier",
"Verser",
"Grincer",
"Piquer",
"Charger",
"Bêler",
"Poignarder",
"Transpercer",
"Piquer",
"Avaler",
"Sucer",
"Boire",
"Se faufiler",
"Cacher",
"Trancher",
"Boiter",
"Trébucher",
"Changer",
"Glisser",
"Aveugler",
"Transpercer",
"Frappant",
"Écraser",
"Sauter",
"Tonnerre",
"Faire taire",
"Pleurer",
"Geindre",
"Deuil",
"Assombrir",
"Empiler",
"Creuser",
"Lancer",
]},
{"title": "d100 Adjectif", "id":"d100adjective_tavernnames", "roll":[
"Calme",
"Joyeux",
"Bon",
"Tordu",
"Blanc",
"Gris",
"Ennoirci",
"Harassé",
"Crimson",
"Argent",
"Doré",
"Perturbé",
"Sale",
"Moche",
"Bâtard",
"Hésitant",
"Glorieux",
"Beau",
"Beau",
"Ridé",
"Malheureux",
"Intelligent",
"Charmant",
"Ignorant",
"Sénile",
"Aigre",
"Doux",
"Solitaire",
"Vert",
"Aveugle",
"Affamé",
"Inquiet",
"Éduqué",
"Stupide",
"Encouragé",
"Honorifique",
"Puant",
"Sans fond",
"Gras",
"En désordre",
"Stylé",
"Déstressé",
"Tourmenté",
"Tourmenté",
"Mortifié",
"Inégal",
"Cassé",
"Moisi",
"Visqueux",
"Fermenté",
"Corrompu",
"Orné",
"Noyé",
"Assassiné",
"Veuf",
"Pendu",
"En colère",
"Lubrique",
"Hanté",
"Fort",
"Flétri",
"Beau",
"Pieux",
"Pécheur",
"Patient",
"Ivre",
"Digne",
"Riche",
"Détestable",
"Faible",
"Minuscule",
"Miniature",
"Énorme",
"Élargi",
"Engorgé",
"Lubrique",
"Despicable",
"Lascif",
"Rond",
"Violent",
"Maladroit",
"Défectueux",
"Pristine",
"Propre",
"Fissuré",
"Éclaté",
"Bijou",
"Supérieur",
"Sans défaut",
"Commun",
"Exquis",
"Élégant",
"Fin",
"Terne",
"Fragile",
"Cassant",
"Efféminé",
"Masculin",
"Supin",
]},
{"title": "d100 Nom 1", "id":"d100noun1a_tavernnames", "roll":[
"Cavalier",
"Demoiselle",
"Mage",
"Célibataire",
"Roi",
"Magistrat",
"Chef de guerre",
"Guerrier",
"Jument",
"Loup",
"Renard",
"Lion",
"Agneau",
"Gardien",
"Mule",
"Assassin",
"Épéiste",
"Dame",
"Chevalier",
"Soldat",
"Sorcier",
"Magicien",
"Ranger",
"Barde",
"Druide",
"Moine",
"Paladin",
"Sorcier",
"Voleur",
"Clerc",
"Érable",
"Gobelin",
"Kobold",
"Gnome",
"Hobbit",
"Nain",
"Idiot",
"Vierge",
"Horde",
"Écuyer",
"Aigle",
"Coq",
"Porcelet",
"Voleur",
"Prêtre",
"Frère",
"Forgeron",
"Garde",
"Cerf",
"Sorcière",
"Diable",
"Ange",
"Serpent",
"Serpent",
"Rat",
"Souris",
"Bandit",
"Chef",
"Griffon",
"Dragon",
"Reptile",
"Poney",
"Baron",
"Vache",
"Bœuf",
"Chien",
"Chèvre",
"Crapeau",
"Étalon",
"Monstre",
"Vermine",
"Regardant",
"Singe",
"Éléphant",
"Cochon sauvage",
"Beagle",
"Chauve-souris",
"Démon",
"Imp",
"Fée",
"Esprit",
"Chienne",
"Etourneau",
"Minotaure",
"Barbare",
"Prophète",
"Marchand",
"Cordonnier",
"Licorne",
"Ogre",
"Nymphe",
"Boucher",
"Capitaine",
"Pêcheur",
"Amoureux",
"Maçon",
"Bricoleur",
"Baleine",
]},
{"title": "d100 Nom 1B", "id":"d100noun1b_tavernnames", "roll":[
"Cavalier",
"Demoiselle",
"Mage",
"Célibataire",
"Roi",
"Magistrat",
"Chef de guerre",
"Guerrier",
"Jument",
"Loup",
"Renard",
"Lion",
"Agneau",
"Gardien",
"Mule",
"Assassin",
"Épéiste",
"Dame",
"Chevalier",
"Soldat",
"Sorcier",
"Magicien",
"Ranger",
"Barde",
"Druide",
"Moine",
"Paladin",
"Sorcier",
"Voleur",
"Clerc",
"Érable",
"Gobelin",
"Kobold",
"Gnome",
"Hobbit",
"Nain",
"Idiot",
"Vierge",
"Horde",
"Écuyer",
"Aigle",
"Coq",
"Porcelet",
"Voleur",
"Prêtre",
"Frère",
"Forgeron",
"Garde",
"Cerf",
"Sorcière",
"Diable",
"Ange",
"Serpent",
"Serpent",
"Rat",
"Souris",
"Bandit",
"Chef",
"Griffon",
"Dragon",
"Reptile",
"Poney",
"Baron",
"Vache",
"Bœuf",
"Chien",
"Chèvre",
"Crapeau",
"Étalon",
"Monstre",
"Vermine",
"Regardant",
"Singe",
"Éléphant",
"Cochon sauvage",
"Beagle",
"Chauve-souris",
"Démon",
"Imp",
"Fée",
"Esprit",
"Chienne",
"Etourneau",
"Minotaure",
"Barbare",
"Prophète",
"Marchand",
"Cordonnier",
"Licorne",
"Ogre",
"Nymphe",
"Boucher",
"Capitaine",
"Pêcheur",
"Amoureux",
"Maçon",
"Bricoleur",
"Baleine",
]},
{"title": "d100 Nom 2", "id":"d100noun2_tavernnames", "roll":[
"Selle",
"Guilde",
"Crocs",
"Homme",
"Pardon",
"Plasir",
"Ceinture",
"Bâton",
"Bouclier",
"Prince",
"Maître",
"Serviteur",
"Repas",
"Prince",
"Faveur",
"Amour",
"Mot",
"Écrivain",
"Apprenti",
"Acólite",
"Robe",
"Déesse",
"Dieu",
"Or",
"Bourse",
"Piège",
"Roi",
"Fils",
"Sœur",
"Mère",
"Fille",
"Cry",
"Cri",
"Placard",
"Panier",
"Reine",
"Richesse",
"Étoile",
"Vide",
"Femme",
"Homme",
"Prostituée",
"Boucher",
"Enclume",
"Volume",
"Sacrifice",
"Armure",
"Tasse",
"Casserole",
"Poêle",
"Tabouret",
"Princesse",
"Chaîne",
"Épée",
"Porc",
"Céréale",
"Dent",
"Lance",
"Hache",
"Fourreau",
"Couteau",
"Poignard",
"Lance",
"Arc",
"Arbalète",
"Bâton",
"Bâton",
"Feu",
"Glace",
"Vent",
"Terre",
"Eau",
"Pierre",
"Louche",
"Monastère",
"Calice",
"Gobelet",
"Donjon",
"Libido",
"Lanterne",
"Os",
"Vie",
"Pierre",
"Mistress",
"Esprit",
"Trésor",
"Barter",
"Armurier",
"Majordome",
"Page",
"Volume",
"Plume",
"Ombre",
"Ami",
"Labyrinthe",
"Montagne",
"Espoir",
"Botte",
"Gantelet",
]},



{"title": "d50 Le magasin vend...", "id":"d50theshopsells_shops", "roll":[
"Armes",
"Armures",
"Objets magiques",
"Nourriture fraîche",
"Nourriture séchée",
"Animaux",
"Esclaves",
"Services",
"Principalement des objets inutiles",
"Œuvres d'art",
"Bijoux",
"Gemmes et minerais",
"Outils de minage",
"Articles ménagers",
"Outils agricoles",
"Aliments pour animaux",
"Outils de fabrication",
"Bière et liqueurs",
"Objets d'intérêt d'une génération précédente",
"Objets d'intérêt d'une terre lointaine",
"Vêtements",
"Gadgets gnomes",
"Potions",
"Poisons",
"Fournitures alchimiques",
"Fournitures magiques",
"Instruments de musique",
"Tissus",
"Un peu de tout",
"Épices",
"Outils de chasse",
"Herbes",
"Médicaments et toniques",
"Livres",
"Poupées",
"Jouets",
"Animaux exotiques",
"Fourrures et peaux",
"Produits illicites",
"Fromages",
"Viandes",
"Animaux de charge",
"Fournitures de construction",
"Fruits et légumes",
"Fournitures pour une guilde locale",
"Articles en cuir",
"Objets fabriqués à partir de métaux rares",
"Fournitures de beauté et d'hygiène",
"Créatures magiques",
"Roues de chariot",
]},
{"title": "d10 Le type de magasin est...", "id":"d10theshopstypeis_shops", "roll":[
"Un bâtiment dans un quartier commerçant",
"Attaché à la maison du marchand",
"Un chariot tiré par une équipe de chevaux ou de boeufs",
"Sous une tente",
"Dans un bazar ouvert sur un tapis",
"Dans un étal de bazar",
"Dans l'arrière-salle d'un autre magasin",
"Une caravane marchande",
"Dans un endroit accessible uniquement par magie",
"Une franchise. Le magasin peut être trouvé à plusieurs endroits",
]},
{"title": "d12 Le magasin est détenu par...", "id":"d12theshopisownedby_shops", "roll":[
"Un comptable aux yeux perçants",
"Un chef de guilde",
"Un noble",
"Un gnome obsessionnel-compulsif",
"Un nain avare",
"Un ancien soldat",
"La femme d'un fermier",
"Un haut-elfe snob",
"Un hobbit distrait",
"Un brute oppressif",
"Une vieille sorcière",
"Un demi-orc paresseux",
]},
{"title": "d6 L'état du magasin est...", "id":"d6theshopsconditionis_shops", "roll":[
"Neuf. Tout a sa place, et est à sa place",
"Bien entretenu. Il est nettoyé régulièrement",
"Moyenne. Un peu poussiéreux",
"En désordre. Des insectes et des rongeurs fuient à vos pas",
"Sombre. Il n'y a pas de lumière naturelle. Seulement une ou deux bougies éclairent le magasin",
"Décrépité. Le bâtiment devrait être condamné",
]},
{"title": "d6 L'état des marchandises est...", "id":"d6theconditionofthemerchandiseis_shops", "roll":[
"Impeccable. Gardé dans le meilleur état possible",
"Nettoyé régulièrement",
"Mélangé. Certains articles semblent neufs, tandis que d'autres semblent être là depuis longtemps",
"Poussiéreux et sale",
"En train de se désagréger",
"Ancien",
]},
{"title": "d6 Le magasin obtient ses fournitures de...", "id":"d6theshopgetsitssuppliesfrom_shops", "roll":[
"Elles sont fabriquées ou obtenues par le marchand lui-même",
"Elles sont fabriquées ou obtenues par les apprentis du marchand",
"Le partenaire commercial du marchand",
"Elles sont fabriquées ailleurs en grande quantité et vendues dans le magasin",
"Elles sont achetées à d'autres personnes en ville et revendues",
"Personne ne sait, et personne ne pose de questions",
]},
{"title": "d8 Les articles sont tarifés...", "id":"d8theitemsarepriced_shops", "roll":[
"De manière équitable",
"En dessous de la valeur",
"Au-dessus de la valeur",
"Exorbitant",
"Tout est à troquer",
"Des moyens de paiement \"autres\" sont encouragés",
"En fonction de l'humeur du marchand",
"En fonction de combien le marchand pense que le client en a besoin",
]},
{"title": "d5 La taille du magasin est...", "id":"d5theshopssizeis_shops", "roll":[
"Géant. Plusieurs pièces",
"Grand. Une grande pièce",
"Moyenne. Une pièce assez grande pour contenir ce qui est nécessaire",
"Petit. La pièce semble encombrée",
"Minuscule. Le marchand fonctionne presque à partir d'un sac",
]},
{"title": "d4 À quel point le magasin est-il occupé...", "id":"d4howbusyistheshop_shops", "roll":[
"C'est l'un des endroits les plus populaires à visiter",
"Quelques personnes vont et viennent dans le magasin",
"Pas très occupé. Vous êtes les seules personnes présentes",
"Il voit rarement un client",
]},
{"title": "d50 Quelque chose d'intéressant que vous trouvez...", "id":"d50somethinginterestingyoufind_shops", "roll":[
"Le propriétaire vit dans une pièce attenante au magasin",
"Il y a une pièce secrète à l'arrière pour vendre des marchandises illicites",
"Le propriétaire ne semble pas avoir sa place ici",
"Un des articles ne semble pas être à sa place",
"Une cloche sonne chaque fois que quelqu'un entre dans le magasin",
"Le propriétaire est exceptionnellement amical",
"Le propriétaire ne semble pas vouloir faire de commerce",
"Certains articles sont étrangement magiques (ou non magiques)",
"Vous sentez une présence invisible qui vous observe",
"Des barrières magiques empêchent les gens de manipuler les marchandises",
"Un gobelin manipule certaines marchandises",
"Un ogre est attaché à l'un des murs",
"Quelques chiens vous surveillent tout en mâchant un os",
"Un chat vous suit dans le magasin",
"Une chèvre semble faire la garde dehors",
"Un nid de rats se forme dans un coin isolé",
"Un oiseau parlant insiste pour vous crier des obscénités",
"De nombreux articles sont en train d'être emballés pour la vente",
"Un nouveau lot vient d'arriver et est en train d'être mis en rayon",
"Vous entendez des bruits provenant du toit ou de la pièce au-dessus du magasin",
"Le sol est fissuré",
"Le marchand nettoie un article qui a été endommagé au sol",
"Le propriétaire se dispute avec un employé",
"Un singe vous suit et essaie de vous remettre des marchandises",
"Des empreintes de pas mènent directement à un mur",
"Un corbeau essaie de voler des articles dans votre sac",
"Les jeunes enfants du marchand essaient en vain de conclure une vente difficile",
"Le marchand ne parle pas la langue commune",
"Les articles changent quand vous ne regardez pas",
"De la musique joue dans tout le magasin",
"Le marchand peut raconter une histoire sur chaque article qu'il vend",
"Certains des articles semblent volés",
"Le magasin n'ouvre que la nuit",
"Le magasin est fermé pour la journée",
"Un article inhabituel est en vente avec une sombre histoire derrière",
"Quelques voyous retiennent le marchand",
"Un des clients tente de voler dans le magasin",
"Le magasin a une forte odeur de moisissure",
"Le magasin appartient à un ami ou un ancien membre du groupe",
"Un fantôme parcourt les marchandises",
"Le propriétaire dort profondément",
"Le propriétaire a une odeur nauséabonde et offensante",
"Le propriétaire est un vendeur persuasif",
"Une arme légendaire est exposée, mais non en vente",
"Des fresques décorent les murs",
"Le marchand insiste pour dire qu'il vient d'une ancienne lignée de marchands puissants",
"Le marchand est habillé beaucoup mieux que prévu",
"Le marchand ressemble à un mendiant",
"Les constables ou la garde locale interviewent tout le monde dans le magasin",
"Le propriétaire vient de mourir",
]},


{"title": "d8 Le marché est situé dans...", "id":"d8themarketplaceislocatedin", "roll":[
"Une grande place rectangulaire",
"Une grande place circulaire ou elliptique",
"Une grande place de forme polygonale (d4): 1. carré parfait; 2. trapèze; 3. triangle; 4. pentagone",
"Une intersection de deux larges routes",
"Un labyrinthe tentaculaire de petites ruelles",
"Un labyrinthe tentaculaire de tunnels sous les rues de la ville",
"Un énorme pavillon avec un toit solide au-dessus",
"Une série désorganisée de grandes tentes",
]},
{"title": "d10 Les étals, chariots et stands des vendeurs sont principalement organisés par...", "id":"d10vendorstallscartsandboothsaremostlyorganizedby", "roll":[
"Type de marchandise",
"Nation d'origine des marchandises",
"Race ou ethnie des marchands",
"Rien; l'endroit est un grand fouillis désorganisé",
"Affiliation religieuse ou politique des marchands",
"Les matières premières et les produits sur un côté du marché, les produits finis de l'autre côté",
"Les marchandises importées d'un côté du marché, les produits locaux de l'autre côté",
"Un système complexe et archaïque inscrit dans un ancien document civique ou religieux",
"La classe sociale à laquelle le vendeur s'adresse",
"L'ordre d'arrivée des vendeurs sur le marché chaque jour",
]},


{"title": "d50 Nom de la colonie (partie 1)...", "id":"d50settlementnamepart1", "roll":[
"Pierre",
"Eau",
"Feuille",
"Glace",
"Flamme",
"Soleil",
"Tempête",
"Terre",
"Éclat",
"Étoile",
"Art",
"Guerre",
"Cœur",
"Dur",
"Chute",
"Roche",
"Destinée",
"Chêne",
"Larme",
"Corbeau",
"Blaireau",
"Serpent",
"Lion",
"Enfer",
"Colère",
"Saumure",
"Rat",
"Sanglier",
"Lys",
"Cœur",
"Puanteur",
"Mage",
"Dieu",
"Sols",
"Pur",
"Mal",
"Cam",
"Marais",
"Clair",
"Divisé",
"Fondateur",
"Héritier",
"Féerique",
"Seigneur",
"Roi",
"Serviteur",
"Démon",
"Neige",
"Terre",
]},
 {"title": "d50 Nom de la colonie (partie 2)...", "id":"d50settlementnamepart2", "roll":[
"crête",
"pont",
"cours",
"attraper",
"lame",
"refuge",
"montée",
"plus",
"lumière",
"principal",
"flamme",
"place",
"larme",
"pli",
"repos",
"hôte",
"artisanat",
"repaire",
"creux",
"vallée",
"marteau",
"lanterne",
"rail",
"pieu",
"anneau",
"cercle",
"spirale",
"printemps",
"mâchoire",
"marque",
"grêle",
"lac",
"enfant",
"fort",
"forteresse",
"ruisseau",
"avancer",
"fondre",
"bourg",
"gué",
"ramper",
"moral",
"combe",
"vallon",
"jardin",
"voeux",
"compagnon",
"crête",
"quartier",
"ville",
]},
{"title": "d6 Taille de la population...", "id":"d6populationsize", "roll":[
"50 personnes (hameau)",
"100 personnes (petit village)",
"250 personnes (village)",
"1 000 personnes (petite ville)",
"5 000 personnes (ville)",
"25 000 personnes (grande ville)",
]},

 {"title": "d100 Les principaux habitants sont...", "id":"d100maininhabitantsare", "roll":[
"Humains",
"Humains",
"Humains",
"Humains",
"Humains",
"Humains",
"Humains",
"Humains",
"Humains",
"Humains",
"Humains",
"Humains",
"Humains",
"Humains",
"Humains",
"Humains",
"Humains",
"Humains",
"Humains",
"Humains",
"Humains",
"Humains",
"Humains",
"Humains",
"Humains",
"Humains",
"Humains",
"Humains",
"Humains",
"Humains",
"Humains",
"Humains",
"Humains",
"Humains",
"Humains",
"Elfes des bois",
"Elfes des bois",
"Elfes des bois",
"Elfes des bois",
"Elfes des bois",
"Hauts elfes",
"Hauts elfes",
"Hauts elfes",
"Hauts elfes",
"Hauts elfes",
"Hauts elfes",
"Hauts elfes",
"Hauts elfes",
"Hauts elfes",
"Eladrins",
"Eladrins",
"Demi-elfes",
"Demi-elfes",
"Drows",
"Drows",
"Nains des montagnes",
"Nains des montagnes",
"Nains des montagnes",
"Nains des montagnes",
"Nains des montagnes",
"Nains des montagnes",
"Nains des montagnes",
"Nains des montagnes",
"Nains des montagnes",
"Nains des montagnes",
"Nains des collines",
"Nains des collines",
"Nains des collines",
"Nains des collines",
"Nains des collines",
"Hobbits pieds légers",
"Hobbits pieds légers",
"Hobbits pieds légers",
"Hobbits robustes",
"Hobbits robustes",
"Gnomes des rochers",
"Gnomes des rochers",
"Gnomes des forêts",
"Gnomes des forêts",
"Gnomes des profondeurs",
"Dragonborn",
"Dragonborn",
"Dragonborn",
"Dragonborn",
"Dragonborn",
"Orques et Demi-orques",
"Orques et Demi-orques",
"Orques et Demi-orques",
"Tieflings et Démoniaques",
"Tieflings et Démoniaques",
"Aarakocra",
"Aarakocra",
"Genasi et Élémentaires",
"Genasi et Élémentaires",
"Shifters et Lycanthropes",
"Shifters et Lycanthropes",
"Goliaths et Géants",
"Changelings et Doppelgangers",
"Warforged et Constructs",
"Aasimar et Célestes",
]},
{"title": "d20 L'atmosphère de la colonie est...", "id":"d20thesettlementsatmosphereis", "roll":[
"Calme",
"Pittoresque",
"Paisible",
"Vaguement inquiétante",
"Décidément sinistre",
"Tendue",
"Violente",
"Pleine de peur",
"Animée",
"Troublée",
"Chaotique",
" agréable",
"Sombre",
"Lourde",
"Oppressante",
"Relaxante",
"Libératrice",
"Spirituelle",
"Indifférente",
"Accablée de chagrin",
]},
{"title": "d100 Une caractéristique marquante de la colonie est...", "id":"d100aprominentfeatureofthesettlementis", "roll":[
"Ses beaux parcs",
"Ses majestueux vergers",
"Une bibliothèque notable",
"Une guilde puissante",
"L'odeur du pain cuit",
"Les sons des forgerons au travail",
"L'abondance de gibier dans les terres environnantes",
"Les vastes terres agricoles qui l'entourent",
"Ses marchandises exotiques",
"Les bidonvilles",
"Son syndicat criminel",
"Ses bordels de luxe",
"Son interdiction de la prostitution",
"Le fait qu'elle soit protégée par de solides murs en pierre",
"Le fait qu'elle soit construite sur une motte flottante de terre",
"Ses barrières magiques visibles, qui repoussent les monstres",
"Le fait qu'elle soit constamment assiégée",
"Le fait qu'elle soit dirigée par un tyran",
"La loi est appliquée de manière stricte",
"L'absence de gouvernement; l'anarchie règne",
"Un grand temple",
"Un cimetière clôturé plus grand que nécessaire",
"Un système de tunnels sous la colonie",
"Un portail planétaire",
"Une malédiction puissante",
"Le fait que les aventuriers soient détestés par la population",
"Un obélisque mystérieux qui surplombe les autres bâtiments",
"Un artiste célèbre habite la colonie",
"Le fait que la magie soit détestée par la population",
"Ses gardes lourdement armés et bien entraînés",
"Le monstre apprivoisé qui la défend",
"Une route commerciale bien fréquentée qui la traverse",
"Ses serveuses de bar \"amicales\"",
"Distillerie locale de bière",
"Un château d'un noble seigneur",
"Une tour dans laquelle une princesse est enfermée",
"Le fait qu'elle soit envahie par les nuisibles",
"Le fait qu'elle traverse une dépression économique",
"Le fait qu'elle soit extorquée par un monstre intelligent",
"Un groupe de réfugiés campant près de la colonie",
"Le fait qu'elle soit sur le chemin d'une caravane de gitans",
"Le fait qu'un carnaval itinérant passe souvent",
"Les vignobles à proximité",
"Son histoire en tant que champ de bataille",
"Sa proximité avec un bastion de monstres",
"Un puits à souhaits avec une légende locale",
"Le fait qu'elle soit construite dans une zone de magie morte",
"Le fait qu'elle soit construite dans une zone de magie sauvage",
"Le fait que ce soit le lieu d'un événement mythique",
"Le fait qu'elle soit construite sur des ruines antiques",
"Une statue honorant un héros mort depuis longtemps",
"Une abondance d'un certain animal",
"Un sanctuaire dédié à un dieu maléfique",
"Une publication abordable portant des nouvelles du royaume",
"Un culte pacifique",
"Ses larges rues",
"Son architecture incroyablement belle",
"Son mécénat des arts",
"L'académie de magie à proximité",
"Les herbes rares qui y poussent",
"L'utilisation de cristaux lumineux comme lampadaires",
"Son observatoire astronomique",
"Un pont qui traverse une large rivière",
"Ses habitants fièrement patriotes",
"Un gibet érigé dans la place principale",
"Un fantôme sympathique",
"Sa politique \"sans armes\"",
"Un politicien corrompu",
"Des raids réguliers par un groupe de bandits voisins",
"Le fait qu'elle ait été fondée par des cannibales, et que certains continuent cette tradition",
"Le fait qu'elle soit en réalité une base de bandits",
"Le fait que toute lumière sauf la lumière du soleil soit étouffée",
"Le fait que ce soit le lieu d'un trésor pirate non réclamé",
"Les mines voisines",
"Une histoire d'assassinats",
"Son attitude très progressiste",
"Son attitude conservatrice inébranlable",
"Son leader incompétent et bouffon",
"Sa paranoïa",
"Sa xénophobie",
"Sa tolérance envers les autres",
"Un coven de sorcières comme dirigeants",
"Sa population principalement masculine",
"Sa population principalement féminine",
"Sa forte concentration d'enfants",
"Son absence notable d'enfants",
"Sa connexion avec le Feywild",
"Sa connexion avec le Shadowfell",
"Son ambiance sale",
"L'odeur des égouts",
"Un fleuve qui la divise",
"Les serviteurs morts-vivants qui effectuent des travaux",
"Le fait qu'elle soit le centre d'une chasse à l'homme",
"Une mascotte poney avec un nom adorable",
"L'odeur écrasante de soufre",
"Un bourdonnement bas qui imprègne la colonie sans cause connue",
"Un arbre millénaire sur la place de la ville",
"Le fait qu'elle soit sous la protection d'esprits élémentaires amicaux",
"La chaleur brûlante de ses forges",
"Sa fameuse impartialité",
]},
{"title": "d30 Les joueurs devraient se soucier de la colonie parce que...", "id":"d30theplayersshouldcareaboutthesettlementbecause", "roll":[
"Il y a des magasins d'objets magiques",
"Un donjon a été récemment découvert à proximité",
"Un puissant sorcier y vit",
"Un PNJ que les joueurs ont rencontré auparavant s'y trouve",
"Quelque chose qu'ils veulent s'y trouve",
"Un voleur leur a volé quelque chose ici",
"Il a été mentionné dans une lettre trouvée sur un ennemi abattu",
"Ils sont engagés par quelqu'un dans la colonie",
"C'est la seule colonie avec laquelle se réapprovisionner dans un rayon de plusieurs lieues",
"Un des habitants a demandé de l'aide pour un problème",
"C'est le seul refuge sûr dans les environs infestés de monstres",
"Ils sont impliqués dans un crime et on leur a demandé de ne pas quitter la ville",
"Il y a des rumeurs intéressantes sur leurs ennemis",
"Les joueurs ont libéré des prisonniers qui ont demandé à être emmenés là",
"Un ennemi les a défiés",
"Les récompenses sur le panneau de travail sont élevées",
"Des choses ne collent pas tout à fait ; une enquête pourrait être nécessaire",
"Il continue à être mentionné partout où ils vont",
"Les habitants les accueillent comme des héros",
"Ils ont besoin de se mettre à l'abri d'une tempête violente",
"Ils ont besoin d'une aide que la colonie peut fournir",
"Un enfant/un PNJ sans défense est en danger et a besoin d'aide",
"Il y a des signes d'infestation de monstres",
"Une créature dont les objectifs sont en conflit avec les leurs vit là",
"Un puissant PNJ essaie de les mettre sous un \"geas\"",
"Un patron leur promet des emplois là-bas",
"Ils entendent des rumeurs sur un objet magique caché à proximité",
"Un crime étrange est commis, les impliquant indirectement",
"Un PNJ local leur a rendu un service et souhaite en tirer profit",
"Une entité puissante leur propose un marché",
]},



{"title": "d10 Le nom du magasin est", "id":"d10thenameoftheshopis", "roll":[
"Vieille Grindylocks",
"Enchantements et Malédictions",
"Les Fidgets de Sam le Nervieux",
"Banshees, Basilisques et Beholders",
"Hextech et autres objets magiques",
"La Griffe Rampante",
"La Boule de Feu Pétillante",
"La Montée de Magie Sauvage",
"Les Plumes du Phénix",
"Les Accessoires Magiques de Michael",
]},
{"title": "d20 Le magasin est situé", "id":"d20theshopislocated", "roll":[
"Sous terre",
"Dans les bidonvilles",
"Dans le marché",
"Dans la cave de la taverne",
"Dans la maison d'un lanceur de sorts",
"Aux docks",
"Sur un navire",
"Dans le même bâtiment que la taverne des sorciers",
"Dans le quartier arcane",
"Sur la place de la ville",
"Dans une ruelle habitée principalement par des elfes",
"Dans une ruelle habitée principalement par des nains",
"Dans une ruelle habitée principalement par des gnomes",
"Dans une ruelle habitée principalement par des Tieflings",
"Dans une ruelle habitée principalement par des gobelins",
"Dans le quartier noble",
"À l'entrée du Colisée",
"Le magasin est le chariot d'un marchand itinérant",
"Au sommet d'une montagne",
"Au fond d'une rivière",
]},

{"title": "d10 Le magasin vend", "id":"d10theshopsells", "roll":[
"Bijoux et accessoires, rien de puissant",
"Potions et poisons",
"Potions d'amour, Viagra et autres choses de ce genre",
"Divinations",
"Composants matériels pour divers sorts",
"Grimoires et encre magique",
"Armes magiques",
"Armures magiques",
"Parchemins",
"Animaux enchantés",
]},
{"title": "d10 Le magasin est détenu par", "id":"d10theshopisownedby", "roll":[
"Un humain incroyablement vieux",
"Un gnome nerveux",
"Un hobbit distrait",
"Un gobelin avare et malveillant",
"Un sorcier voleur",
"Une fée",
"Un haut-elfe snob",
"Un sorcier qui expérimente constamment",
"Un efreeti essayant de négocier avec votre âme",
"Un guerrier qui ne connaît rien à la magie, mais vend les biens qu'il a acquis au fil des années",
]},
{"title": "d10 L'endroit semble", "id":"d10theplacelooks", "roll":[
"Suspendu",
"Impeccable",
"Naturel",
"Usé",
"Vivant",
"Incroyablement petit à l'intérieur par rapport à ce qu'il semble à l'extérieur",
"Incroyablement grand à l'intérieur par rapport à ce qu'il semble à l'extérieur",
"Calciné",
"Congelé",
"Étincelant",
]},
{"title": "d10 Une caractéristique des articles vendus ici est", "id":"d10acharacteristicoftheitemssoldhereis", "roll":[
"Ils sont tous en mauvais état",
"Ils ont des effets inconnus",
"Ils sont instables et peuvent libérer des poussées magiques lors de leur utilisation",
"Ils sont périmés (par exemple, un sort expiré)",
"Ils sont maudits",
"Ils sont bénis",
"Les articles sont tous volés",
"Les articles ont de grandes histoires",
"Le précédent propriétaire des articles les recherche encore",
"Les articles sont antiques",
]},

{"title": "d8 L'arène est...", "id":"d8thearenais", "roll":[
"Une ancienne structure en pierre utilisée depuis des siècles",
"Une vieille structure en pierre utilisée depuis des générations",
"Une construction merveilleuse avec de grands gradins, des trappes et des ascenseurs",
"Une structure en bois solide, récemment construite",
"Une structure en pierre nette, récemment construite",
"Un ensemble de gradins en bois branlants autour d'un anneau de terre",
"Un cercle de corde entouré de spectateurs et de quelques cages",
"Un fossé souterrain avec des spectateurs penchés au-dessus d'une rampe",
]},
{"title": "d8 Les jeux sont organisés...", "id":"d8thegamesarebeingheld", "roll":[
"En l'honneur de l'anniversaire du souverain",
"En l'honneur d'un anniversaire historique",
"En l'honneur d'une victoire militaire récente",
"Pour réaliser un profit légitime pour les organisateurs",
"Pour réaliser un profit de jeu pour les organisateurs",
"Pour se débarrasser des prisonniers",
"Strictement pour divertir les masses",
"Pour déterminer un champion pour une quête dangereuse ou une cérémonie traditionnelle",
]},
{"title": "d8 L'événement principal est...", "id":"d8themaineventis", "roll":[
"Un battle royale ou une grande mêlée",
"Une reconstitution d'une bataille historique",
"Un duel entre deux champions de l'arène",
"Un duel entre un champion et un outsider sévère",
"Alimenter des prisonniers aux bêtes",
"Un combat entre l'homme et la bête (d8) : 1. ours ; 2. chimères ; 3. dragons ; 4. araignées géantes ; 5. lions ; 6. ours-hiboux ; 7. tigres ; 8. loups",
"Une course de chars ou une course à pied",
"Des exploits de force",
]},
{"title": "d12 Le champion du jour gagne...", "id":"d12thedayschampionwins", "roll":[
"Une lourde bourse d'argent",
"Une bourse considérable d'or",
"Une arme coûteuse et ornée",
"Un morceau d'armure coûteux et orné",
"Une couronne florale et une belle chaîne en argent",
"Une couronne florale et une ceinture en or sertie de pierres précieuses",
"Un manteau en soie fine et une chaîne en argent sertie de pierres précieuses",
"Une pétition du souverain",
"Une position d'honneur dans l'armée et une bourse d'argent",
"Une position d'honneur dans la garde du souverain",
"Une semaine de soins et de plaisir et une bourse d'argent",
"Une nuit avec l'une des épouses des nobles et une bourse d'or",
]},
{"title": "d6 L'attitude de la foule est...", "id":"d6thecrowdsattitudeis", "roll":[
"Bruyante et festive",
"Impatiente et excitée",
"Relaxée et décontractée",
"Hostile et tendue",
"Déçue et en colère",
"Bruyante et rebelle",
]},
{"title": "d8 La foule est principalement composée de...", "id":"d8thecrowdismadeupofmostly", "roll":[
"Commerçants, nobles et gens de bien",
"Soldats, officiers et suiveurs de camp",
"Artisans et commerçants locaux",
"Paysans locaux et travailleurs non qualifiés",
"Étrangers et voyageurs",
"Esclaves, serviteurs et ouvriers",
"Marins, pirates et coquins",
"Personnes de toutes les classes sociales",
]},
{"title": "d200 Cet endroit s'appelle...", "id":"d200thisplaceiscalled", "roll":[
"Les Marguerites",
"Le Don",
"Les Clignotants",
"Les Suspenders de la Prude",
"La Poussière d'Or",
"La Dent de Velours",
"Le Foyer des Murmures",
"Le Crochet",
"Au-Delà du Fleuve",
"Slooshes",
"Le Rapide Vagabond",
"Le Belette",
"Le Furet Nervieux",
"Longueur du Pieu",
"Les Gardes",
"Chasteté",
"Le Masque",
"La Robe Rouge",
"Les Bijoux",
"La Flûte de Soie",
"Le Tête de Ménestrel",
"Les Tambours",
"Le Choix des Marins",
"La Jalousie du Forgeron",
"La Femme Qui Râle",
"Les Décombres de Colin",
"Le Battement de Dron",
"Le Clin d'Œil",
"Le Cor de Maggie",
"Le Soleil & Cidre",
"Le Ver de Chêne",
"Chatouille et Plume",
"La Maîtresse",
"Madame Zersannie",
"Le Cour des Rois",
"Le Sou Coincé",
"Fente",
"Le Front de la Vierge",
"Le Rouillé",
"Le Furet de Soie",
"Les Grandes Jambes",
"Les Murmures des Elfes",
"La Jambe",
"Les Suspenders Faux",
"Les Culottes d'Aunt Fannie",
"Le Dernier Repos",
"Le Chant du Coq",
"Les Yeux Sans Clignotement",
"Le Seins Abondants",
"Les Défenses",
"Le Gentleman Qui Pousse",
"Les Tally Ho",
"Le Mâle",
"Les Cochons en Couverture",
"Le Tendre Toucher",
"Le Souhait d'Aphrodite",
"Le Secret Sale",
"Les Longs Cheveux",
"La Sueur",
"Le Bordel",
"Les Pommes de Terre",
"Le Fini Rapide",
"Cumberlands",
"Les Saucisses Disparues",
"Le Fou de Rire",
"Les Dragons",
"Le Panier",
"Les Avoines du Fermier",
"Le Sourcil Levé",
"Les Génies",
"La Plume de la Lointaine",
"Le Junk",
"Le Choix du Connaisseur",
"Le Colosse",
"Le Confort Doux",
"Le Galop",
"Les Gloires des Grand Globes",
"Le Glimmeric",
"L'Étreinte Aimante",
"Le Collier du Choker",
"L'Emporium de la Grande Madame des Délices Fins, Treats, et de l'Exotique",
"Le Repli du Thug",
"Le Retour du Guerrier",
"Les Gobblers d'Or",
"Les Croons Cackling",
"Les Verrues",
"Le Meilleur de Bessie",
"Le Corset",
"Les Winkies",
"Le Shagger",
"Port d'Appel",
"La Maison Loin des Prostituées",
"Douce",
"La Vierge Belle",
"La Pièce",
"Accueilli",
"Les Délices Glamour",
"Vivre Heureux Pour Toujours",
"Le Regard Sensuel",
"La Grande Flush",
"La Bougie Allumée",
"La Bougie Rouge",
"La Bougie Levée",
"La Flamme Dansante",
"Le Resort Candlelight",
"La Cerise la Plus Douce",
"La Cerise",
"La Tarte à la Cerise",
"La Cerise de Velours",
"La Cerise d'Or",
"Le Rideau de Soie",
"Le Rideau Rouge",
"Le Rideau Dentelle",
"Le Rideau Accueillant",
"Le Rideau Satiné",
"Les Poupées Satinées",
"Les Poupées Sucrées",
"Les Poupées en Porcelaine",
"La Poupée Sucrée",
"Danseurs et Poupées",
"La Porte Rouge",
"La Porte d'Or",
"La Porte d'Argent",
"La Porte de la Vierge",
"La Porte des Danseurs",
"L'Étreinte de l'Amant",
"L'Étreinte de la Dame",
"L'Étreinte la Plus Douce",
"L'Étreinte la Plus Chaleureuse",
"L'Étreinte Accueillante",
"Le Gant Satiné",
"Les Gants de Soie",
"Les Gants Dentelle",
"Le Gant de la Dame",
"Le Gant de la Vierge",
"Le Cœur Brillant",
"Les Cœurs Roses",
"Les Cœurs Dentelle",
"Les Cœurs de l'Amoureux",
"Le Cœur de la Vierge",
"La Maison de Nuit",
"La Maison Rose",
"La Maison en Porcelaine",
"La Maison Accueillante",
"La Maison Confortable",
"La Lampe la Plus Chaleureuse",
"La Lampe Rouge",
"La Lampe Rose",
"La Lampe Douce",
"La Lampe de la Dame",
"Le Baiser de la Dame",
"Le Baiser de la Vierge",
"Le Baiser de la Nuit",
"Les Baisers Doux",
"Les Baisers Satinés",
"Le Lieu de Pêche",
"La Pêche",
"La Pêche la Plus Joli",
"La Pêche la Plus Sucrée",
"La Pêche d'Or",
"La Bourse de Soie",
"La Bourse Satinée",
"La Bourse de la Dame",
"La Bourse de la Danseuse",
"La Bourse Rose",
"La Pièce de la Vierge",
"La Pièce des Amoureux",
"La Pièce de Nuit",
"La Pièce Chaleureuse",
"La Pièce Rouge",
"La Pantoufle d'Argent",
"La Pantoufle Satinée",
"La Pantoufle de Soie",
"La Pantoufle Rouge",
"La Pantoufle de la Danseuse",
"La Jupe Dentelle",
"La Jupe Accueillante",
"La Jupe Rose",
"La Jupe de Danseuse",
"La Jupe de la Dame",
"La Chaussure de la Vierge",
"La Chaussure Rouge",
"Les Chaussures Confortables",
"Les Chaussures des Amoureux",
"Les Chaussures en Argent",
"Les Bas de Soie",
"Le Bas Rouge",
"Le Bas Dentelle",
"Le Bas de la Dame",
"Les Bas les Plus Doux",
"Le Voile de la Vierge",
"Le Voile Dentelle",
"Le Voile de Soie",
"Le Voile des Amoureux",
"Le Voile de la Nuit",
"Fenêtre Douce-Lumineuse",
"Fenêtre Brillante",
"Fenêtre Allumée",
"Fenêtre Rose",
"Fenêtre Accueillante",
]},
{"title": "d20 Le bordel est situé...", "id":"d20thebrothelislocated", "roll":[
"Dans les bidonvilles",
"Dans un quartier de cabanes",
"Dans un quartier résidentiel aisé",
"Dans le quartier des docks",
"Dans le quartier en bord de rivière",
"Dans le quartier des casernes",
"Dans une ruelle d'un bazar étranger",
"Dans une ruelle près de la place principale du marché",
"À l'ombre d'un temple",
"Au-dessus d'une taverne bruyante",
"Derrière une taverne pleine de criminels",
"À côté d'une taverne pleine de joueurs",
"Sous terre",
"En dehors des murs de la ville ou en périphérie d'un village",
"Au pied d'une tour de sorcier",
"Dans une grotte qui était le repaire d'un monstre",
"Au-dessus d'une auberge sur une route commerçante animée",
"Dans le sous-sol d'une taverne",
"Dans une rue avec de nombreux autres bordels",
"Dans une maison dans un parc, jardin ou forêt",
]},
{"title": "d10 En plus des classiques des bordels quotidiens, ici vous pouvez obtenir...", "id":"d10inadditiontotheusualeverydaybrothelfarehereyoucanprocure", "roll":[
"Des trucs vraiment bizarres, pour ceux ayant les fétiches les plus intéressants.",
"Des trucs illégaux. Si cela se découvre, l'endroit serait incendié et les propriétaires pendus. C'est clairement gardé en grand secret.",
"Des performances impliquant de la nourriture.",
"Un moyen de vivre des fantasmes violents.",
"Des races exotiques.",
"Les plus belles femmes et hommes. Ce n'est pas qu'une simple prétention, c'est la vérité divine.",
"Un forfait tout compris—toutes les courtisanes, nourriture et boissons à volonté !",
"La vente de drogues altérant l'esprit.",
"Des choses avec des ingrédients exotiques/magiques, des potions, etc.",
"Des délices magiques.",
]},
{"title": "d8 L'endroit est géré par...", "id":"d8theplaceisrunby", "roll":[
"Un collectif des pensionnaires eux-mêmes",
"Une vieille madame méchante",
"Une grande madame avec une attitude sans compromis",
"Une figure maternelle chaleureuse",
"Un brute grincheux",
"Un tyran cruel",
"Une séductrice sensuelle",
"Une sorcière charmante",
]},
{"title": "d12 À manger, l'endroit sert...", "id":"d12toeattheplaceserves", "roll":[
"Des en-cas simples",
"Des banquets",
"De la nourriture paysanne",
"De la nourriture donnée à la main par une courtisane",
"Des délices exotiques",
"Des friandises épicées",
"De la nourriture simple",
"Des sucreries et des délices",
"Des repas sales et mal faits",
"Des buffets à volonté",
"Un simple ragoût et du pain",
"Rien ; ça satisfait d'autres appétits",
]},
{"title": "d8 À boire, l'endroit sert...", "id":"d8todrinktheplaceserves", "roll":[
"Des bières",
"Des cocktails",
"Du grog, et rien que du grog",
"Des vins bon marché",
"De l'hydromel",
"Les meilleurs vins et champagnes",
"Des lagers",
"Rien ; l'ivresse n'est pas tolérée",
]},
{"title": "d10 On parle de cet endroit ; on dit que...", "id":"d10peopletalkaboutthisplacetheysay", "roll":[
"Les filles sont sous-payées et mal traitées",
"Rien de spécial ; c'est un bordel de quartier",
"Un noble ou un marchand éminent est un habitué",
"La déesse de l'amour et de la fertilité a béni cet endroit et tous ses adeptes doivent y rendre visite",
"Les habituelles histoires ; une nouvelle fille fait sensation",
"Une fois par mois, des services sont proposés à prix réduit",
"C'est secrètement la maison d'un culte sombre",
"Toutes les pensionnaires sont de la même famille",
"Rien de particulier, une fille populaire est enceinte",
"On peut payer les services avec autre chose que de la monnaie (d6) : 1. travail contractuel ; 2. biens ; 3. services religieux ; 4. invitations de haut profil ; 5. secrets ; 6. actions",
]},
{"title": "d10 On parle de cet endroit ; des rumeurs suggèrent que récemment...", "id":"d10peopletalkaboutthisplacerumorssuggestthatrecently", "roll":[
"Un noble a mis une des filles enceinte mais refuse de la reconnaître ainsi que l'enfant",
"Quelqu'un a massacré la moitié des travailleurs et des clients pendant la nuit",
"Un client a été poignardé avec un ouvre-lettres",
"Un homme prétendant être un parangon du dieu de l'amour a visité l'endroit",
"Un groupe de villageois outrés a commencé à protester devant le bordel, dégoûté par ce qui s'y passe",
"Le plus ancien des habitués, qui visitait le bordel chaque jour depuis cinquante ans, est décédé. Une journée de deuil et de célébration, avec des funérailles somptueuses, est organisée pour lui",
"Une des pensionnaires a été étranglée",
"Une des pensionnaires est tombée follement amoureuse d'un client, mais il ou elle est marié(e)",
"Un trou béant est apparu dans le sous-sol. Personne ne peut en voir le fond, et le patron craint qu'il ne se développe et cause plus de dégâts",
"Plusieurs clients ont contracté une maladie",
]},
{"title": "d10 Meubles de la chambre : Cette chambre a...", "id":"d10roomfurnishingsthisroomhas", "roll":[
"Un lit à baldaquin avec des rideaux en velours",
"Un lit à baldaquin avec des rideaux en dentelle",
"Un fauteuil longue chaise en cuir doux",
"Un fauteuil longue chaise en velours rose",
"Un grand tas d'oreillers avec des glands doux",
"Un grand tas d'oreillers avec des bords frangés",
"Une table avec des fruits et du vin posés dessus",
"Une table avec des parfums et des huiles posés dessus",
"Un grand miroir contre un mur",
"Un grand miroir au plafond au-dessus du lit",
]},
{"title": "d20 Caractéristiques : Vous remarquez...", "id":"brotheld20featuresyounotice", "roll":[
"Le parfum de lavande",
"Le parfum de lilas",
"Le parfum de gingembre et de cannelle",
"Le parfum des roses",
"Des bougies parfumées",
"Une douce lueur rouge provenant d'une lampe tamisée",
"Une lampe brûlant faiblement",
"Une statue de deux figures s'embrassant",
"Une statue de deux figures s'unissant",
"Une statue d'une femme nue en train de se baigner",
"Une peinture de plusieurs nus se baignant",
"Une peinture d'un couple d'amoureux",
"Un rideau de perles",
"Un rideau en soie",
"Un tapis moelleux sous vos pieds",
"Un tapis épais en fourrure sous vos pieds",
"Le son d'une musique douce et lointaine",
"Le bruit des meubles qui craquent à proximité",
"Un cri perçant et long",
"Un long gémissement",
]},
{"title": "d20 Repère : Vous voyez un(e)...", "id":"d20landmarkyouseeaan", "roll":[
"Académie ou université",
"Ruine ancienne",
"Arène",
"Cimetière",
"Salle civique, salle du conseil ou salle de guilde",
"Place publique ou promenade",
"Forteresse",
"Porte ou arche",
"Bibliothèque",
"Phare ou tour de guet",
"Marché",
"Mémorial (d4) : 1. mausolée ; 2. bassin réfléchissant ; 3. grande statue ; 4. jardin botanique",
"Monument (d6) : 1. colosse ; 2. colonne ; 3. obélisque ; 4. plaque ; 5. jardin de statues ; 6. mur",
"Palais",
"Place de défilé ou terrain d'entraînement",
"Quai, marina ou bazar de voyageurs",
"Plaza ou place publique",
"Temple",
"Théâtre",
"Parcs à bestiaux",
]},
{"title": "d20 Cette partie de la ville est...", "id":"d20thispartofthecityisthe", "roll":[
"Les bidonvilles",
"Quartier résidentiel, pauvre",
"Quartier résidentiel, classe moyenne",
"Quartier résidentiel, classe supérieure",
"Quartier des palais",
"Quartier des temples",
"Quartier de l'artisanat",
"Quartier des docks",
"Quartier en bord de rivière",
"Quartier du port",
"Quartier universitaire",
"Quartier militaire",
"Quartier commerçant",
"Quartier des jardins",
"Quartier des monuments",
"Nécropole",
"Quartier des théâtres",
"Centre civique",
"Enclave ethnique",
"Enclave étrangère",
]},
{"title": "d20 Les habitants appellent cette rue...", "id":"d20thelocalscallthisstreet", "roll":[
"(d8) : 1. Rue de l'armurerie ; 2. Rue des barricades ; 3. Rue des chevaliers ; 4. Rue des fossés ; 5. Rue des piques ; 6. Rue des remparts ; 7. Rue des boucliers ; 8. Rue des lances",
"(d6) : 1. Rue de l'arc ; 2. Rue du pont ; 3. Rue du canal ; 4. Rue croisée ; 5. Rue des poteaux ; 6. Rue de la rivière",
"(d6) : 1. Rue du château ; 2. Rue de la maison ; 3. Rue de la forteresse ; 4. Rue du manoir ; 5. Rue du rocher ; 6. Rue de la tour",
"(d8) : 1. Route du bétail ; 2. Rue commune ; 3. Rue verte ; 4. Rue des sentiers ; 5. Allée des prés ; 6. Rue du verger ; 7. Route des pâturages ; 8. Allée des fleurs sauvages",
"(d12) : 1. Rue de l'enclume ; 2. Rue du tonnelier ; 3. Rue de la forge ; 4. Rue du marteau ; 5. Rue des fers à cheval ; 6. Rue du fer ; 7. Rue du maçon ; 8. Rue de l'acier ; 9. Rue du tailleur ; 10. Rue de la pierre ; 11. Rue du menuisier ; 12. Rue du tisserand",
"(d8) : 1. Rue du promontoire ; 2. Rue de la falaise ; 3. Rue de la crête ; 4. Rue haute ; 5. Rue des hauteurs ; 6. Rue de la colline ; 7. Allée du sommet ; 8. Rue du pic ; 9. Allée de la crête ; 10. Rue du sommet",
"(d8) : 1. Allée du diable ; 2. Allée des démons ; 3. Rue basse ; 4. Allée des magpies ; 5. Rue des pauvres ; 6. Rue des pièces de monnaie ; 7. Allée des rats ; 8. Allée des serpents","Rue du marché",
"(d8) : 1. Rue du boulanger ; 2. Rue du crochet ; 3. Route de la ferme ; 4. Rue des plumes ; 5. Rue du moulin ; 6. Route du porc ; 7. Route des éleveurs ; 8. Rue du parc à bestiaux",
"(d8) : 1. Route des bannières ; 2. Rue des capitaines ; 3. Rue du tambour ; 4. Rue de la marche ; 5. Rue du défilé ; 6. Rue triomphale ; 7. Rue des trompettes ; 8. Rue de la victoire",
"(d6) : 1. Rue du roi ; 2. Allée des seigneurs ; 3. Rue des monarques ; 4. Rue du palais ; 5. Rue de la reine ; 6. Rue royale",
"(d6) : 1. Rue du cercle ; 2. Route de la frontière ; 3. Rue des rideaux ; 4. Route de la ville ; 5. Rue de la garde ; 6. Rue du mur",
"(d8) : 1. Rue de la baie ; 2. Rue du commerce ; 3. Route des quais ; 4. Rue du port ; 5. Rue du lac ; 6. Rue du pier ; 7. Route du bord de mer ; 8. Rue de l'eau",
"(d8) : 1. Rue de la vue sur la baie ; 2. Rue de la vue sur le château ; 3. Rue de la vue sur le jardin ; 4. Rue de la vue sur le vert ; 5. Rue de la vue sur le port ; 6. Rue de la vue sur le marché ; 7. Rue de la vue sur la rivière ; 8. Rue de la vue sur l'eau",
"(d8) : 1. Route du nord ; 2. Rue du nord ; 3. Route du sud ; 4. Rue du sud ; 5. Route de l'est ; 6. Rue de l'est ; 7. Route de l'ouest ; 8. Rue de l'ouest",
"(d12) : 1. Rue du hêtre ; 2. Rue du cèdre ; 3. Rue de la cerise ; 4. Rue du cyprès ; 5. Rue du pin ; 6. Rue de l'érable ; 7. Rue du chêne ; 8. Rue du palmier ; 9. Rue du pin ; 10. Rue de l'épicéa ; 11. Rue du noyer ; 12. Rue du saule",
"(d8) : 1. Rue de la porte du nord ; 2. Rue de la porte du sud ; 3. Rue de la porte de l'est ; 4. Rue de la porte de l'ouest ; 5. Route de la vieille porte ; 6. Rue du fleuve ; 7. Rue de la tour de garde ; 8. Rue de la porte de l'eau",
"(d12) : 1. Rue des ronces ; 2. Rue des buissons ; 3. Allée des jardins ; 4. Rue des jardins ; 5. Rue des lilas ; 6. Allée des lys ; 7. Rue des pétales ; 8. Rue des coquelicots ; 9. Rue des roses ; 10. Allée des tournesols ; 11. Allée des épines ; 12. Rue des violettes",
"(d6) : 1. Rue de l'émeraude ; 2. Allée des bijoutiers ; 3. Rue de l'or ; 4. Route des riches ; 5. Route des rubis ; 6. Allée de l'argent",
"(d8) : 1. Rue du bain ; 2. Rue de la fontaine ; 3. Vieille route de briques ; 4. Vieille route de pierres ; 5. Rue disparue ; 6. Rue de la ruine de pierre ; 7. Allée des pierres tombées ; 8. Rue du puits",
]},

{"title": "d20 Jeux, concours et événements", "id":"d20gamescontestsandevents", "roll":[
"Un groupe de paysans joue aux fers à cheval derrière.",
"Les aventuriers sont surpris de trouver la ligue locale de fléchettes en plein essor à leur entrée. Les serveuses sont habituées au chaos et évitent les fléchettes avec facilité. Le videur demi-ogre utilise des fléchettes de jardin.",
"Un groupe de Nains des Collines est en plein concours de boisson, et deux d'entre eux sont déjà inconscients. Le prix est un stein en platine massif.",
"Concours de mailles mouillées !",
"Quatre grands barbares se défient bruyamment dans un concours de bras de fer.",
"Une adolescente timide récite de la mauvaise poésie dans un coin. Personne ne lui prête attention.",
"C'est la soirée trivia ! Les érudits de l'École d'Histoire et des Arts de l'Université gagnent toujours, mais ce soir, nous représentons et l'École de l'Alchimie va montrer à ces prétentieux bibliophiles ce que signifie être un vrai nerd.",
"Un promoteur se faufile autour des tables à la recherche de challengers pour affronter le champion pugiliste local.",
"C'est une soirée saucisses ! L'endroit est bondé de nains impatients de dévorer l'offre à volonté de saucisses.",
"Un brute surdimensionnée fait des bras de fer en écrasant la main de tous ceux qui passent.",
"Quelques gobelins jouent aux dés avec des squelettes animés à une table dans le coin.",
"Un gobelin triche mal à un jeu de dés, tandis qu'un squelette triche très bien.",
"Un dragonborn rouge de 2,20 m avec une épée bâtarde de 1,50 m participe à un concours de boisson contre un nain. Le dragonborn a une chope de 4 pintes et parvient presque à suivre le rythme.",
"Un groupe de joueurs est assis dans une cabine à jouer aux cartes. Tous trichent, sauf le paladin, qui, curieusement, gagne.",
"Un colosse en cuir de barbare fait un bras de fer contre un petit dragon et gagne.",
"Un Roper éveillé gagne deux parties de billard en même temps.",
"Un groupe de pixies ivres joue à cache-cache en se cachant derrière les clients.",
"Les joueurs tombent sur un championnat régional de cartes qui se tient ce soir. L'inscription est élevée, mais le pot aussi.",
"Un inventeur gnome au look louche présente fièrement sa dernière invention. Il l'appelle une « machine à sous ». ",
"Un conteur aux cheveux gris est assis près du feu et organise un concours. Il offrira une grosse bourse à celui qui racontera une histoire qu'il n'a pas encore entendue, mais jusqu'à présent, personne n'a gagné.",
]},

{"title": "d12 Divertissement", "id":"d12entertainment", "roll":[
"Le barman raconte des histoires élaborées sur l'origine du dragon wyrmling empaillé sur la cheminée. En réalité, c'est un vieux mage et c'était son familier qui est tombé malade et est mort. Il le garde en souvenir.",
"Un barde raconte l'histoire de la dernière aventure audacieuse des joueurs. Il embellit beaucoup. Lorsqu'il reconnaît le groupe, il en fait tout un spectacle.",
"Un barde raconte l'exploit récent des joueurs. C'est une évidente tentative de dénigrer leur personnage.",
"Un groupe de bardes locaux, The Rolling Boulders, se produit, et une grande foule de groupies ivres n'arrête pas de crier.",
"Un mendiant propose de chanter pour quelques sous. Vous l'avez entendu chanter à la dernière table. Il est affreux.",
"Une diseuse de bonne aventure audacieuse a installé son stand dans une cabine au coin. Elle vous informe qu'elle voit une gueule de bois dans votre futur proche.",
"Une interprétation émouvante de \"La Dame et le Dragon Féérique\" fait crier la foule pour un rappel des musiciens.",
"Le joueur de luth attrape des sous-vêtements lancés par la foule et les drape sur son casque ridicule à cornes.",
"Sur scène ce soir : The Deep Tones. Un quatuor de nains avec de longues barbes et des voix profondes chantant des favoris a capella de lieux sans lumière (ou sans vraie musique).",
"Sur scène ce soir : Shaela Windspeaker. Une chanteuse-compositrice elfe au ton légèrement plaintif qui avance lentement dans sa chanson la plus récente de protestation contre les siècles passés et présents de guerre.",
"Un magicien nerveux sur la petite scène fait des tours avec la Prestidigitation pour des spectateurs non amusés.",
"Un duo de musiciens chantent des chansons traditionnelles de buveurs. Ils ont improvisé une scène avec plusieurs tables. L'un d'eux semble légèrement pencher.",
]},

{"title": "d20 Clients et Personnel", "id":"d20patronsandstaff", "roll":[
"Un pauvre fermier essaie de payer sa note de bar avec un sac de pommes de terre et un tonneau de cornichons.",
"Un capitaine de mer a installé son stand à une table et essaie de vendre des souvenirs de son dernier grand voyage d'exploration. Des oiseaux, des pièces exotiques, de petites sirènes, il a tout. Certains semblent faux, mais un peu semble étrangement réel.",
"Un ranger est assis seul dans un coin, fumant. Une capuche couvre la majeure partie de son visage. À ses pieds, un chien-loup dort. Tout le monde lui accorde une grande distance.",
"Un troll solitaire boit au bout du bar et pleure doucement en chantant une chanson country après l'autre.",
"Un magicien défoncé peine à réaliser un tour de cartes désastreux après l'autre.",
"Un groupe mixte d'Elfes boit du mauvais vin et se couvre le nez avec des mouchoirs parfumés pour éviter la puanteur. L'un d'eux porte un arc en obsidienne dans son dos.",
"Une jeune femme et un homme bourru posent des questions aux clients sur eux-mêmes. Lorsqu'ils arrivent aux joueurs, la femme est intéressée par leurs récits d'aventure. Ils ne savent pas qu'ils parlent à l'héritier présomptif et à son garde de confiance.",
"Deux gardes se disputent à une table pour savoir lequel des deux caporaux est le préféré, comparant presque les mêmes lances et affirmant avoir la meilleure.",
"Un clown triste boit une bière tout seul.",
"Une jeune et belle femme tient cour au milieu de ses prétendants. Son père intervient, et elle s'éloigne embarrassée.",
"Un idiot organise une soirée de célibataire. Ses amis sont bruyants et harcèlent de manière obstinée les serveuses.",
"C'est la soirée des dames ! Et ce n'est pas décevant... Quelques jolies petites choses du guildes des tisserands sont ici, quelques guérisseuses attirantes du temple, et la belle nouvelle bibliothécaire de la ville.",
"Une vieille sorcière bourrue boit du sherry en caressant le gros chat gris qui est sur ses genoux.",
"Le barman est une marilith, mélangeant quatre boissons à la fois.",
"La serveuse est une succube, elle reçoit de très bons pourboires.",
"L'employé des toilettes est un zombie malodorant. Il vous offre un cristal de menthe.",
"Derrière le bar, il y a un alchimiste gnome avec une passion pour les expériences de mixologie.",
"Le mop-hand sans dents se remémore avec un hobgoblin militaire déchu autour de quelques bières, en parlant de comment un otyugh dans les toilettes n'était pas aussi mauvais que la fois où un dévoreur de cadavres s'y trouvait.",
"La serveuse est un doppelganger. Lorsqu'elle revient à votre table avec vos boissons, elle a pris la forme de l'un des membres de votre groupe.",
"Un prêtre corpulent fait une excellente danse ondulante en rythme avec la musique. Ou alors, un cube gélatineux a fait son entrée sur la piste de danse ?",
]},
{"title": "d6 Boissons douteuses", "id":"d6questionabledrinks", "roll":[
"Le cocktail spécial de ce soir : Le Pixiewine. Chaque verre de ce vin crispé, parfumé aux fleurs, est servi avec une pixie.",
"Le cocktail spécial de ce soir : Le Suckerpunch. Chaque verre de ce punch puissant rouge-violet contient plusieurs petites tentacules qui se tordent et qui sortent du verre pour se coller à votre visage avec leurs ventouses. Ça fait en fait un peu du bien.",
"Le spécial de ce soir : Apporte-Ton-Corne. Apportez la corne de votre bête ou humanoïde monstrueux préféré (de n'importe quelle taille !), et nous la remplirons de bière bon marché ou de vin pour 2 pièces de cuivre.",
"Le cocktail spécial de ce soir : Le Mindbomb. Il est fait avec de l'absinthe et de la poudre explosive.",
"Le cocktail spécial de ce soir : Le Fireball. Servi par des sorciers de 5e niveau ou plus.",
"Le cocktail spécial de ce soir : Le Stonebones. Un puissant cocktail de rhum fait avec de la poudre de corne de gorgon et de l'œil de basilic. Ce n'est qu'une paralysie partielle.",
]},
{"title": "d20 Complots, Farces et Problèmes", "id":"d20schemesmischiefandtrouble", "roll":[
"Un groupe de bandits de grand chemin discute bruyamment et un peu trop fort du convoi qu'ils ont pillé à l'extérieur de la ville et de ce qu'ils vont faire de leur part.",
"Des aventuriers manipulant un compagnon transformé en pierre par un basilic entrent dans le bar. Le voleur essaie de le vendre au barman comme porte-chapeau. Le barman y réfléchit.",
"Le barman est à court de chopes parce qu'un magicien est évanoui dans un coin, sur une table couverte de chopes. Son familier ivre attaque toute personne s'approchant de la table pour empêcher la récupération des chopes.",
"Un Dragonfaé est évanoui dans les poutres. Accroché à une de ses griffes se trouve un soutien-gorge en dentelle.",
"Un gnome grassouillet vend du fromage puant dans un panier en osier.",
"Un beholder ivre devient de plus en plus grincheux. Ou peut-être joue-t-il, difficile à dire.",
"Deux contrebandiers discutent dans un coin avant de commencer à se disputer. Ils se tirent dessus, l'un d'eux meurt. Personne n'est vraiment sûr de qui a tiré le premier.",
"Un homme est assis seul, parlant normalement à la chaise vide en face de lui, avant de crier de colère.",
"Un couple de Ratfolk est harcelé par quelques clients ivres. Ils ne ripostent pas.",
"Un enfant tente de monter une farce contre un personnage peu apprécié. Il est proche de réussir, mais vous pouvez repérer une faille dans son plan que vous pourriez résoudre.",
"C'est la soirée des dames ! Et ce bar est un véritable repaire de saucisses.",
"Un nécromancien entraîne un client ivre hors de la porte.",
"Le videur frappe un gobelin indiscipliné avec son massue du matin. Personne ne s'en soucie car la fête bat son plein.",
"Un couteau coupe en plein dans le centre du jeu de fléchettes en cours des elfes. Les elfes dégainent leurs arcs et commencent à tirer dans la salle.",
"Un illithid raconte l'avenir avec un jeu de cartes de tarot sur un tonneau retourné à l'extérieur. Certains disent que c'est de la triche parce qu'il peut lire dans les pensées, mais moi je dis que c'est de la triche parce qu'il peut manger les esprits.",
"Un otyugh a encore mis le bazar dans les toilettes.",
"Au tableau de fléchettes, un elfe des bois est pris pour cible, et il doit déjà une somme importante aux humains bruyants autour de lui.",
"La taverne est pleine de groupes de touristes, tous admirant une seule affiche sur le tableau d'annonces. Vous réalisez vite qu'il s'agit tous de groupes d'aventuriers, et il ne reste qu'une seule mission. Ils commencent tous à courir dehors pour être les premiers à la réaliser.",
"Une grande vache est assise à une extrémité, un magicien murmurant à son oreille : \"Je suis sûr que ça ne m'arrive jamais, chérie\".",
"La salle principale est remplie de monde. Un nain majestueux orné d'une grande chaîne se tient sur le bar, achetant des boissons pour tout le monde et prêchant les mérites de Gundar, le grand dieu des réjouissances.",
]},
{"title": "d40 Vous avez entendu parler de cette taverne/avez mangé là-bas parce que...",  "id": "d40youhaveheardofthistavernbeforeeatentherebeforebecause",  "roll": [
    "ils font une excellente kirschtorte",
    "ils maîtrisent vraiment leurs pierogis",
    "ils sont la capitale mondiale du borscht",
    "leur réputation pour les gołąbkis est inégalée",
    "ils mettent du bacon partout",
    "cette serveuse super sexy",
    "ils ont toujours un parking pour chevaux",
    "leur porridge de carottes est à mourir",
    "Personne ne sait où c'est, donc c'est généralement calme.",
    "Ils sont ouverts plus tard que tout autre endroit en ville.",
    "Personne sauf les aventuriers n'est assez courageux pour manger dans un endroit construit sous le rail de foudre, donc les marchands et les habitants pauvres restent à l'écart.",
    "Ils achètent toute la viande que vous apportez et la cuisinent fraîche.",
    "Ils ont expulsé sans pitié les autres commerces de la ville et vous mouriez de faim.",
    "Desserts délicieux. La tarte au fromage est à mourir !",
    "Sélection de bières. Ils ont une excellente sélection de bières.",
    "Bière maison. Ils brassent leur propre dragon-stout maison !",
    "Viande. Le propriétaire est un chasseur qui part chaque jour dans les bois pour attraper et tuer le rôti principal.",
    "Décor bestial. Les murs sont couverts de fourrures, de bois de cerf et de têtes de bêtes.",
    "Décor élégant. Les cabines sont séparées par de magnifiques rideaux en dentelle et un agréable parfum d'encens imprègne l'air.",
    "Histoires héroïques. Le propriétaire a tué un dragon.",
    "Histoires tristes. Le barman est une noble superbe qui s'est enfuie avec le pauvre type qui possédait cet endroit avant qu'il ne meure.",
    "Sex-appeal. Les serveuses portent des blouses décolletées et/ou des jupes moulantes.",
    "Service amical. Les serveuses sont vraiment sympas.",
    "Antre des joueurs. Le jeu de dés est à enjeux élevés.",
    "Personnel étrange. Le videur est un demi-troll.",
    "Personnel badass. Le videur a un tatouage de dragon sur le visage.",
    "Vins haut de gamme. Leurs vins viennent d'une île elfique imprononçable.",
    "Boissons magiques. Le barman est un magicien alchimiste qui sert des potions d'amour, des décoctions pour dormir et des tonics pour les moustaches. (Certains diront qu'un bon tonic pour les moustaches est tout ce dont on a besoin pour une potion d'amour.)",
    "Divertissement. Le barman joue d'un excellent piano.",
    "Décorations, ils ont des trophées de partout.",
    "Critiques, un type avec un stylo, du papier et ces nouvelles inventions qu'on appelle des mots a écrit un article à leur sujet.",
    "Noblesse, les gens de la haute société aiment cet endroit.",
    "L'admission est un symbole de statut.",
    "Les gens, c'est là où vous allez pour trouver des dépanneurs.",
    "Chaleur, les murs empêchent magiquement le froid et la neige d'entrer.",
    "Les Nains l'ont construit.",
    "C'était autrefois une bibliothèque et il y a une énorme sélection de livres à lire.",
    "C'était autrefois un temple et le demi-dieu vénéré là-bas essaie parfois de frapper les profanateurs, parfois avec plus de succès que d'autres.",
    "Ils acceptent une généreuse ligne de crédit.",
    "C'est un lieu exotique, et parfois des spelljammers s'y arrêtent, apportant des bibelots venant de tous les plans."
  ]},



// end of settlements

];
