//  subrolls.js
//
//  Note:
//    percent_to is the percent to roll at all
//    percent_of is the percent of the total to roll



tavern_names = [

  {"title": "Le/La [Nom 1] et [Nom 1B]", "main_rolls":["settlements/d100noun1a_tavernnames", "settlements/d100noun1b_tavernnames", ],"sub_rolls":[],},
  {"title": "Le/La [Nom 1] et le/la [Nom 1B]", "main_rolls":["settlements/d100noun1a_tavernnames", "settlements/d100noun1b_tavernnames", ],"sub_rolls":[],},
  {"title": "Le/La [Nom 1]'s [Nom 2]", "main_rolls":["settlements/d100noun1a_tavernnames", "settlements/d100noun2_tavernnames",],"sub_rolls":[],},
  {"title": "Le/La [Nom 1] [Nom 2] [Adjectif]", "main_rolls":["settlements/d100adjective_tavernnames", "settlements/d100noun1a_tavernnames", "settlements/d100noun2_tavernnames",],"sub_rolls":[],},
  {"title": "Le/La [Nom 1] et le/la [Nom 2]", "main_rolls":["settlements/d100noun1a_tavernnames", "settlements/d100noun2_tavernnames",],"sub_rolls":[],},
  {"title": "Le/La [Verbe] [Nom 1]", "main_rolls":["settlements/d100verb_tavernnames", "settlements/d100noun1a_tavernnames", ],"sub_rolls":[],},
  {"title": "Le/La [Nom 1] [Adjectif]", "main_rolls":["settlements/d100adjective_tavernnames", "settlements/d100noun1a_tavernnames", ],"sub_rolls":[],},
  {"title": "Le/La [Nom 1] et le/la [Nom 1] [Adjectif]", "main_rolls":["settlements/d100noun1a_tavernnames", "settlements/d100adjective_tavernnames", "settlements/d100noun1b_tavernnames", ],"sub_rolls":[],},


  //"settlements/d4namingformula_tavernnames",
  //"settlements/d100verb_tavernnames",
  //"settlements/d100adjective_tavernnames",
  //"settlements/d100noun1a_tavernnames",
  //"settlements/d100noun1b_tavernnames",
  //"settlements/d100noun2_tavernnames",

];

military_npcs = [

  {"title":"Armurier", "use":"Utilisez ces tableaux comme source d'inspiration ou utilisez-les de manière aléatoire. Certains tableaux peuvent être utilisés a plusieurs reprise.", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/d4thearmoreris", "npcs/d4thearmorerislookingfor", "npcs/d4thearmorsmithcarries", ],"sub_rolls":[],},
  {"title":"Soldat de campagne", "use":"Utilisez ces tableaux comme source d'inspiration ou utilisez-les de manière aléatoire. Certains tableaux peuvent être utilisés a plusieurs reprise.", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/d6thetraveleris", "npcs/d4thetravelerisseeking", "npcs/d4tonightthetravelerislookingfor", ],"sub_rolls":[],},
  {"title":"Cuisinier", "use":"Utilisez ces tableaux comme source d'inspiration ou utilisez-les de manière aléatoire. Certains tableaux peuvent être utilisés a plusieurs reprise.", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/d6thecookislookingfor", ],"sub_rolls":[],},
  {"title":"Quartier-maitre", "use":"Utilisez ces tableaux comme source d'inspiration ou utilisez-les de manière aléatoire. Certains tableaux peuvent être utilisés a plusieurs reprise.", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/d4thequartermasteris", "npcs/d4thequartermasterseekssomeoneto", "npcs/d4currencythequartermastertradesin", ],"sub_rolls":[],},
  {"title":"Eclaireur", "use":"Utilisez ces tableaux comme source d'inspiration ou utilisez-les de manière aléatoire. Certains tableaux peuvent être utilisés a plusieurs reprise.", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/d4thescoutis", "npcs/d4thescoutislookingto", "npcs/d4thescoutcarries", ],"sub_rolls":[],},
  {"title":"Palefrenier/Écuyer/Valet", "use":"Utilisez ces tableaux comme source d'inspiration ou utilisez-les de manière aléatoire. Certains tableaux peuvent être utilisés a plusieurs reprise.", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/d7theservantis", "npcs/d4theservanthas", "npcs/d6theservantwantsto", ],"sub_rolls":[],},

];


merchant_npcs = [

  {"title":"Soigneur animalier/Porteur", "use":"Utilisez ces tableaux comme source d'inspiration ou utilisez-les de manière aléatoire. Certains tableaux peuvent être utilisés a plusieurs reprise.", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/d6theanimalhandlerhas", "npcs/d4theanimalhandlerwantsto", "npcs/d6theanimalhandlercarries", ],"sub_rolls":[],},
  {"title":"Cuisinier", "use":"Utilisez ces tableaux comme source d'inspiration ou utilisez-les de manière aléatoire. Certains tableaux peuvent être utilisés a plusieurs reprise.", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/d4thecookgreetsyouwith", "npcs/d4thecookislookingfor", "npcs/d6thecookcarries", ],"sub_rolls":[],},
  {"title":"Garde", "use":"Utilisez ces tableaux comme source d'inspiration ou utilisez-les de manière aléatoire. Certains tableaux peuvent être utilisés a plusieurs reprise.", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/d6theguardis", "npcs/d4theguardworksfor", "npcs/d10theguardhas", ],"sub_rolls":[],},
  {"title":"Guide", "use":"Utilisez ces tableaux comme source d'inspiration ou utilisez-les de manière aléatoire. Certains tableaux peuvent être utilisés a plusieurs reprise.", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/d4theguideis", "npcs/d4theguideislookingto", "npcs/d4theguidecarries", ],"sub_rolls":[],},
  {"title":"Voyageur", "use":"Utilisez ces tableaux comme source d'inspiration ou utilisez-les de manière aléatoire. Certains tableaux peuvent être utilisés a plusieurs reprise.", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/d6thetraveleris", "npcs/d6thetravelerissearchingfor", "npcs/d4tonightthetravelerislookingfor", ],"sub_rolls":[],},
  {"title":"Maitre de caravane", "use":"Utilisez ces tableaux comme source d'inspiration ou utilisez-les de manière aléatoire. Certains tableaux peuvent être utilisés a plusieurs reprise.", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/d8thecaravanmasteris", "npcs/d8thecaravanmasterislookingfor", "npcs/d6thecaravanmasteristakingspecialcaretoavoid", "npcs/d8thecaravanmastercarries", ],"sub_rolls":[],},
  {"title":"Marchand de caravanes", "use":"Utilisez ces tableaux comme source d'inspiration ou utilisez-les de manière aléatoire. Certains tableaux peuvent être utilisés a plusieurs reprise.", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/d6themerchantis", "npcs/d4themerchantwears", "npcs/d4themerchantseekssomeoneto", "npcs/d6themerchantcarries", "npcs/d6currencybesidescointhemerchantwilltradein", ],"sub_rolls":[],},

];

town_npcs = [

  {"title":"Alchimiste", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d6thealchemistis", "npcs/d4thealchemistislookingfor", "npcs/d4thealchemistcarries", ],"sub_rolls":[],},
  {"title":"Apprentit artisan", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d4theapprenticeis", "npcs/d4theapprenticeseekssomeoneto", ],"sub_rolls":[],},
  {"title":"Apprentit artisan", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d4theapprenticeis", "npcs/d4theapprenticeseekssomeoneto", ],"sub_rolls":[],},
  {"title":"Apprentit artisan", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d4theapprenticeis", "npcs/d4theapprenticeseekssomeoneto", ],"sub_rolls":[],},
  {"title":"Artisan", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d6theartisanis", "npcs/d8theartisanhas", "npcs/d8theartisanhas", "npcs/d6theartisanisparticularlyskilledat", "npcs/d8theartisanislookingfor", "npcs/d6theartisaniscarrying", "npcs/d6theartisanis", "npcs/d6theartisandreamsof", ],"sub_rolls":[],},
  {"title":"Barde", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d20thebardis", "npcs/d20alwayspreparedtomakeamelodyorrhythmthebardcarrieshisher", "npcs/d10thebardsmusicalinstrumentis", "npcs/d12ifthingsgetroughthebardhas", "npcs/d12thebardalsocarries", "npcs/d12thebardiswearing", "npcs/d12thebardhas", "npcs/d12thebardislookingfor", "npcs/d10thebardisalwaysabighitamong", "npcs/d12thebardtellsataleofarecentvisitto", ],"sub_rolls":[],},
  {"title":"Barde", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d20thebardis", "npcs/d20alwayspreparedtomakeamelodyorrhythmthebardcarrieshisher", "npcs/d10thebardsmusicalinstrumentis", "npcs/d12ifthingsgetroughthebardhas", "npcs/d12thebardalsocarries", "npcs/d12thebardiswearing", "npcs/d12thebardhas", "npcs/d12thebardislookingfor", "npcs/d10thebardisalwaysabighitamong", "npcs/d12thebardtellsataleofarecentvisitto", ],"sub_rolls":[],},
  {"title":"Serveur/Serveuse", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d8theservergreetsyouwith", "npcs/d6theserverislookingfor", "npcs/d4theservercarries", ],"sub_rolls":[],},
  {"title":"Serveur/Serveuse", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d8theservergreetsyouwith", "npcs/d6theserverislookingfor", "npcs/d4theservercarries", ],"sub_rolls":[],},
  {"title":"Serveur/Serveuse", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d8theservergreetsyouwith", "npcs/d6theserverislookingfor", "npcs/d4theservercarries", ],"sub_rolls":[],},
  {"title":"Fabricant d'arc/fléchier", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d4thebowyeris", "npcs/d4thebowyerislookingfor", "npcs/d4thebowyercarries", ],"sub_rolls":[],},
  {"title":"Cuisinier", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d6thecookislookingfor", ],"sub_rolls":[],},
  {"title":"Cuisinier", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d6thecookislookingfor", ],"sub_rolls":[],},
  {"title":"Cuisinier", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d6thecookislookingfor", ],"sub_rolls":[],},
  {"title":"Criminel", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d6thecriminalis", "npcs/d6thecriminalislookingfor", "npcs/d6thecriminalcarries", ],"sub_rolls":[],},
  {"title":"Fermier", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d8thepeasantis", "npcs/d8thepeasantseekssomeoneto", "npcs/d6thepeasantsprimarycropsandmarketfareinclude", ],"sub_rolls":[],},
  {"title":"Fermier", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d8thepeasantis", "npcs/d8thepeasantseekssomeoneto", "npcs/d6thepeasantsprimarycropsandmarketfareinclude", ],"sub_rolls":[],},
  {"title":"Fermier", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d8thepeasantis", "npcs/d8thepeasantseekssomeoneto", "npcs/d6thepeasantsprimarycropsandmarketfareinclude", ],"sub_rolls":[],},
  {"title":"Fermier", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d8thepeasantis", "npcs/d8thepeasantseekssomeoneto", "npcs/d6thepeasantsprimarycropsandmarketfareinclude", ],"sub_rolls":[],},
  {"title":"Fermier", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d8thepeasantis", "npcs/d8thepeasantseekssomeoneto", "npcs/d6thepeasantsprimarycropsandmarketfareinclude", ],"sub_rolls":[],},
  {"title":"Pêcheur", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d10thefishermanfishesin", "npcs/d6thefishermantypicallyfishesfrom", "npcs/d8thefishermanuses", "npcs/d6thefishermanpreferstofish", "npcs/d8thefishermanisseeking", "npcs/d8tattoothefishermanhas", "npcs/d10distinguishingfeaturethefishermanhas", ],"sub_rolls":[],},
  {"title":"Pêcheur", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d10thefishermanfishesin", "npcs/d6thefishermantypicallyfishesfrom", "npcs/d8thefishermanuses", "npcs/d6thefishermanpreferstofish", "npcs/d8thefishermanisseeking", "npcs/d8tattoothefishermanhas", "npcs/d10distinguishingfeaturethefishermanhas", ],"sub_rolls":[],},
  {"title":"Pêcheur", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d10thefishermanfishesin", "npcs/d6thefishermantypicallyfishesfrom", "npcs/d8thefishermanuses", "npcs/d6thefishermanpreferstofish", "npcs/d8thefishermanisseeking", "npcs/d8tattoothefishermanhas", "npcs/d10distinguishingfeaturethefishermanhas", ],"sub_rolls":[],},
  {"title":"Pêcheur", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d10thefishermanfishesin", "npcs/d6thefishermantypicallyfishesfrom", "npcs/d8thefishermanuses", "npcs/d6thefishermanpreferstofish", "npcs/d8thefishermanisseeking", "npcs/d8tattoothefishermanhas", "npcs/d10distinguishingfeaturethefishermanhas", ],"sub_rolls":[],},
  {"title":"Pêcheur", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d10thefishermanfishesin", "npcs/d6thefishermantypicallyfishesfrom", "npcs/d8thefishermanuses", "npcs/d6thefishermanpreferstofish", "npcs/d8thefishermanisseeking", "npcs/d8tattoothefishermanhas", "npcs/d10distinguishingfeaturethefishermanhas", ],"sub_rolls":[],},
  {"title":"Prostituée", "main_rolls":["npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d10theharlotis", "npcs/d6everyoneisbeautifultheharlothas", "npcs/d8nooneisflawlesstheharlothas", "npcs/d4theharlotsflawis", "npcs/d6theharlotisparticularlyskilledat", "npcs/d6theharlotislookingto", ],"sub_rolls":[],},
  {"title":"Prostituée", "main_rolls":["npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d10theharlotis", "npcs/d6everyoneisbeautifultheharlothas", "npcs/d8nooneisflawlesstheharlothas", "npcs/d4theharlotsflawis", "npcs/d6theharlotisparticularlyskilledat", "npcs/d6theharlotislookingto", ],"sub_rolls":[],},
  {"title":"Prostituée", "main_rolls":["npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d10theharlotis", "npcs/d6everyoneisbeautifultheharlothas", "npcs/d8nooneisflawlesstheharlothas", "npcs/d4theharlotsflawis", "npcs/d6theharlotisparticularlyskilledat", "npcs/d6theharlotislookingto", ],"sub_rolls":[],},
  {"title":"Chevalier", "main_rolls":["npcs/dxmalefirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d20theknightshousescolorsare", "npcs/d8theknightshousessymbolis", "npcs/d6theknighthassworntoanoblelordorladyto", "npcs/d8aboveallelsetheknightvalues", "npcs/d4theknightisarmoredin", "npcs/d6theknightsarmoris", "npcs/d12theknightiswielding", "npcs/d6theknightsmountis", "npcs/d12theknightis", "npcs/d12ontheknightsfaceis", "npcs/d10theknightcarries", ],"sub_rolls":[],},
  {"title":"Magistrat", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d4thelawofficialis", "npcs/d6thelawofficialseekssomeoneto", "npcs/d4thelawofficialcarries", ],"sub_rolls":[],},
  {"title":"Noble", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d6thenobleis", "npcs/d6thenobleseekssomeoneto", "npcs/d6thenoblecarries", "npcs/d100lineagethisnobleis_noble", "npcs/d20racethisnobleis…_noble", "npcs/d20positionthisnobleis_noble", "npcs/d50secretsandmotivationthisnobleis_noble", "npcs/d100outwardappearanceandpresentationthisnoble_noble", "npcs/d50quirksandintereststhisnoble…_noble",],"sub_rolls":[],},
  {"title":"Noble", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d6thenobleis", "npcs/d6thenobleseekssomeoneto", "npcs/d6thenoblecarries", "npcs/d100lineagethisnobleis_noble", "npcs/d20racethisnobleis…_noble", "npcs/d20positionthisnobleis_noble", "npcs/d50secretsandmotivationthisnobleis_noble", "npcs/d100outwardappearanceandpresentationthisnoble_noble", "npcs/d50quirksandintereststhisnoble…_noble",],"sub_rolls":[],},
  {"title":"Prêtre", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d6thepriestis", "npcs/d4thepriestislookingfor", "npcs/d4thepriestcarries", ],"sub_rolls":[],},
  {"title":"Commerçant", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d4theshopkeeperis", "npcs/d4theshopkeeperseekssomeoneto", ],"sub_rolls":[],},
  {"title":"Commerçant", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d4theshopkeeperis", "npcs/d4theshopkeeperseekssomeoneto", ],"sub_rolls":[],},
  {"title":"Commerçant", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d4theshopkeeperis", "npcs/d4theshopkeeperseekssomeoneto", ],"sub_rolls":[],},
  {"title":"Commerçant", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d4theshopkeeperis", "npcs/d4theshopkeeperseekssomeoneto", ],"sub_rolls":[],},
  {"title":"Commerçant", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d4theshopkeeperis", "npcs/d4theshopkeeperseekssomeoneto", ],"sub_rolls":[],},
  {"title":"Commerçant", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d4theshopkeeperis", "npcs/d4theshopkeeperseekssomeoneto", ],"sub_rolls":[],},
  {"title":"Forgeron", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d4thesmithis", "npcs/d4thesmithislookingfor", "npcs/d4thesmithcarries", ],"sub_rolls":[],},
  {"title":"Ecuyer", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d12theservantis", "npcs/d6theservantworksfor", "npcs/d8ontheservantsfaceis", ],"sub_rolls":[],},
  {"title":"Palefrenier", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d4thestablehandis", "npcs/d4thestablehandhas", "npcs/d4thestablehandwantsto", ],"sub_rolls":[],},
  {"title":"Voyageur", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d8thetraveleris", "npcs/d10thetravelerisseeking", ],"sub_rolls":[],},
  {"title":"Voyageur", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d8thetraveleris", "npcs/d10thetravelerisseeking", ],"sub_rolls":[],},
  {"title":"Voyageur", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d8thetraveleris", "npcs/d10thetravelerisseeking", ],"sub_rolls":[],},
  {"title":"Voyageur", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d8thetraveleris", "npcs/d10thetravelerisseeking", ],"sub_rolls":[],},
  {"title":"Voyageur", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d8thetraveleris", "npcs/d10thetravelerisseeking", ],"sub_rolls":[],},
  {"title":"Voyageur", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d8thetraveleris", "npcs/d10thetravelerisseeking", ],"sub_rolls":[],},
  {"title":"Tuteur/Sage", "main_rolls":["npcs/dxfirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d6thetutoris", "npcs/d4thetutorschargesviewhimheras", "npcs/d12thetutorisparticularlywellversedin", ],"sub_rolls":[],},
  {"title":"Bucheron", "main_rolls":["npcs/dxmalefirstname", "npcs/dxsurname", "npcs/dxpersonality","npcs/d10facialfeaturethewoodsmanhas", "npcs/d8apparelthewoodsmanwears", "npcs/d8mannerismthewoodsmanhas", "npcs/d8professionthewoodsmanis", "npcs/d10goalthewoodsmanislookingto", "npcs/d10possessionsthewoodsmancarriesorwears", ],"sub_rolls":[],},

];

castle_npcs = [

  {"title":"Noble", "main_rolls":["npcs/dxmalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d6thelordis", "npcs/d6thelordseekssomeoneto", "npcs/d6thelordcarries", ],"sub_rolls":[],},
  {"title":"Noble dame", "main_rolls":["npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d6theladyis", "npcs/d6theladyseekssomeoneto", "npcs/d4theladycarries", ],"sub_rolls":[],},
  {"title":"Garde", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d6theguardserveshisliegefor", "npcs/d6ontheguardsfaceis", "npcs/d4theguardcarries", ],"sub_rolls":[],},
  {"title":"Garde", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d6theguardserveshisliegefor", "npcs/d6ontheguardsfaceis", "npcs/d4theguardcarries", ],"sub_rolls":[],},
  {"title":"Garde", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d6theguardserveshisliegefor", "npcs/d6ontheguardsfaceis", "npcs/d4theguardcarries", ],"sub_rolls":[],},
  {"title":"Garde", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d6theguardserveshisliegefor", "npcs/d6ontheguardsfaceis", "npcs/d4theguardcarries", ],"sub_rolls":[],},
  {"title":"Garde", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d6theguardserveshisliegefor", "npcs/d6ontheguardsfaceis", "npcs/d4theguardcarries", ],"sub_rolls":[],},
  {"title":"Garde", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d6theguardserveshisliegefor", "npcs/d6ontheguardsfaceis", "npcs/d4theguardcarries", ],"sub_rolls":[],},
  {"title":"Garde", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d6theguardserveshisliegefor", "npcs/d6ontheguardsfaceis", "npcs/d4theguardcarries", ],"sub_rolls":[],},
  {"title":"Garde", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d6theguardserveshisliegefor", "npcs/d6ontheguardsfaceis", "npcs/d4theguardcarries", ],"sub_rolls":[],},
  {"title":"Garde", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d6theguardserveshisliegefor", "npcs/d6ontheguardsfaceis", "npcs/d4theguardcarries", ],"sub_rolls":[],},
  {"title":"Garde", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d6theguardserveshisliegefor", "npcs/d6ontheguardsfaceis", "npcs/d4theguardcarries", ],"sub_rolls":[],},
  {"title":"Chevalier", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d6theknightis", "npcs/d6theknighthasswornto", "npcs/d6theknightcarries", ],"sub_rolls":[],},
  {"title":"Chevalier", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/dxpersonality", "npcs/d6theknightis", "npcs/d6theknighthasswornto", "npcs/d6theknightcarries", ],"sub_rolls":[],},
  {"title":"Chevalier", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d6theknightis", "npcs/d6theknighthasswornto", "npcs/d6theknightcarries", ],"sub_rolls":[],},
  {"title":"Chevalier", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d6theknightis", "npcs/d6theknighthasswornto", "npcs/d6theknightcarries", ],"sub_rolls":[],},
  {"title":"Chevalier", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d6theknightis", "npcs/d6theknighthasswornto", "npcs/d6theknightcarries", ],"sub_rolls":[],},
  {"title":"Ecuyer/Valet", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d6theretaineris", "npcs/d4theretainerhas", "npcs/d6theretainerwantsto", ],"sub_rolls":[],},
  {"title":"Ecuyer/Valet", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d6theretaineris", "npcs/d4theretainerhas", "npcs/d6theretainerwantsto", ],"sub_rolls":[],},
  {"title":"Ecuyer/Valet", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d6theretaineris", "npcs/d4theretainerhas", "npcs/d6theretainerwantsto", ],"sub_rolls":[],},
  {"title":"Ecuyer/Valet", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d6theretaineris", "npcs/d4theretainerhas", "npcs/d6theretainerwantsto", ],"sub_rolls":[],},
  {"title":"Ecuyer/Valet", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d6theretaineris", "npcs/d4theretainerhas", "npcs/d6theretainerwantsto", ],"sub_rolls":[],},
  {"title":"Archer", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d6thearcheris", "npcs/d4thearcherislookingto", "npcs/d4thearchercarries", ],"sub_rolls":[],},
  {"title":"Archer", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d6thearcheris", "npcs/d4thearcherislookingto", "npcs/d4thearchercarries", ],"sub_rolls":[],},
  {"title":"Archer", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d6thearcheris", "npcs/d4thearcherislookingto", "npcs/d4thearchercarries", ],"sub_rolls":[],},
  {"title":"Archer", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d6thearcheris", "npcs/d4thearcherislookingto", "npcs/d4thearchercarries", ],"sub_rolls":[],},
  {"title":"Archer", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d6thearcheris", "npcs/d4thearcherislookingto", "npcs/d4thearchercarries", ],"sub_rolls":[],},
  {"title":"Armurier / Smith", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/dxpersonality", "npcs/d4thesmithis", "npcs/d4thesmithislookingfor", "npcs/d4thesmithcarries", ],"sub_rolls":[],},
  {"title":"Intendant", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d4thestewardis", "npcs/d4thestewardseekssomeoneto", "npcs/d4thestewardisconcernedabout", ],"sub_rolls":[],},
  {"title":"Aumônier", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d4thechaplainis", "npcs/d4thechaplainislookingfor", "npcs/d4thechaplaincarries", ],"sub_rolls":[],},
  {"title":"Cuisinier", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d4thecookgreetsyouwith", "npcs/d4thecookislookingfor", ],"sub_rolls":[],},
  {"title":"Fou/Bouffon", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d6thefoolis", "npcs/d8thefoolgetsthemostlaughsfrom", "npcs/d6thefoolwantsnothingmorethanto", ],"sub_rolls":[],},
  {"title":"Tuteur/Sage", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d6thetutoris", "npcs/d4thetutorschargesviewhimheras", "npcs/d12thetutorisparticularlywellversedin", ],"sub_rolls":[],},
  {"title":"Tuteur/Sage", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d6thetutoris", "npcs/d4thetutorschargesviewhimheras", "npcs/d12thetutorisparticularlywellversedin", ],"sub_rolls":[],},
  {"title":"Tuteur/Sage", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d6thetutoris", "npcs/d4thetutorschargesviewhimheras", "npcs/d12thetutorisparticularlywellversedin", ],"sub_rolls":[],},
  {"title":"Servante", "main_rolls":["npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d4theservantis", "npcs/d4theservanthas", "npcs/d4theservantwantsto", ],"sub_rolls":[],},
  {"title":"Servante", "main_rolls":["npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d4theservantis", "npcs/d4theservanthas", "npcs/d4theservantwantsto", ],"sub_rolls":[],},
  {"title":"Servante", "main_rolls":["npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d4theservantis", "npcs/d4theservanthas", "npcs/d4theservantwantsto", ],"sub_rolls":[],},
  {"title":"Servante", "main_rolls":["npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d4theservantis", "npcs/d4theservanthas", "npcs/d4theservantwantsto", ],"sub_rolls":[],},
  {"title":"Servante", "main_rolls":["npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d4theservantis", "npcs/d4theservanthas", "npcs/d4theservantwantsto", ],"sub_rolls":[],},
  {"title":"Capitaine des gardes", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d6thecaptainis", "npcs/d4thecaptainisconcernedabout", "npcs/d4thecaptainislookingfor", "npcs/d6thecaptaincarries", ],"sub_rolls":[],},
  {"title":"Maitre d'écurie", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d4thehorsemasteris", "npcs/d4thehorsemasterhas", "npcs/d4thehorsemasterwantsto", ],"sub_rolls":[],},
  {"title":"Palefrenier", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d4thestablehandis", "npcs/d4thestablehandhas", "npcs/d4thestablehandwantsto", ],"sub_rolls":[],},
  {"title":"Palefrenier", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d4thestablehandis", "npcs/d4thestablehandhas", "npcs/d4thestablehandwantsto", ],"sub_rolls":[],},
  {"title":"Palefrenier", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d4thestablehandis", "npcs/d4thestablehandhas", "npcs/d4thestablehandwantsto", ],"sub_rolls":[],},
  {"title":"Palefrenier", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d4thestablehandis", "npcs/d4thestablehandhas", "npcs/d4thestablehandwantsto", ],"sub_rolls":[],},
  {"title":"Palefrenier", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d4thestablehandis", "npcs/d4thestablehandhas", "npcs/d4thestablehandwantsto", ],"sub_rolls":[],},
  {"title":"Chasseur", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d6thehuntsmanis", "npcs/d4thehuntsmanisconcernedabout", "npcs/d4thehuntsmanislookingto", "npcs/d4thehuntsmancarries", ],"sub_rolls":[],},
  {"title":"Maitre chien", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d4thekennelmasteris", "npcs/d4thekennelmasterislookingto", "npcs/d4thekennelmastercarries", ],"sub_rolls":[],},
  {"title":"Fabricant d'arcs et de flêches", "main_rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d4thebowyeris", "npcs/d4thebowyerislookingfor", "npcs/d4thebowyercarries", ],"sub_rolls":[],},

];

pantheon = [
  {"title":"Dieu du Soleil / Ciel", "main_rolls":["objects/d6thisgodofthesunandorskyisoftencalled", "objects/d6heholdsdominionover", "objects/d6hisfollowersmust", ],"sub_rolls":[],},
  {"title":"Mère nature / Déesse", "main_rolls":["objects/d6thisearthandormothergoddessisoftencalled", "objects/d6sheholdsdominionover", "objects/d6herfollowersmust", ],"sub_rolls":[],},
  {"title":"Dieu de l'artisanat / du savoir", "main_rolls":["objects/d6thisgodofcraftingandorknowledgeisoftencalled", "objects/d6heholdsdominionover", "objects/d6hisfollowersmust", ],"sub_rolls":[],},
  {"title":"Dieu des ténèbres / secrets", "main_rolls":["objects/d6thisgodofdarknessandorsecretsisoftencalled", "objects/d6heholdsdominionover", "objects/d6hisfollowersmust", ],"sub_rolls":[],},
  {"title":"Dieu de la mort / du mal", "main_rolls":["objects/d6thisgodofdeathandorevilisoftencalled", "objects/d6heholdsdominionover", "objects/d6hisfollowersmust", ],"sub_rolls":[],},
  {"title":"Deésse de l'amour / fertilité", "main_rolls":["objects/d6thisgoddessofloveandorfertilityisoftencalled", "objects/d6sheholdsdominionover", "objects/d6herfollowersmust", ],"sub_rolls":[],},
  {"title":"Déesse de la lune / magie", "main_rolls":["objects/d6thisgoddessofthemoonandormagicisoftencalled", "objects/d6sheholdsdominionover", "objects/d6herfollowersmust", ],"sub_rolls":[],},
  {"title":"Déesse de la chasse / des bois", "main_rolls":["objects/d6thisgoddessthehuntandorwoodlandsisoftencalled", "objects/d6sheholdsdominionover", "objects/d6herfollowersmust", ],"sub_rolls":[],},
  {"title":"Dieu des tempêtes / mers", "main_rolls":["objects/d6thisgodisofstormsandorseasoftencalled", "objects/d6heholdsdominionover", "objects/d6hisfollowersmust", ],"sub_rolls":[],},
  {"title":"Dieu messager / trompeur", "main_rolls":["objects/d8thistricksterandormessengergodisoftencalled", "objects/d6heholdsdominionover", "objects/d6hisfollowersmust", ],"sub_rolls":[],},
  {"title":"Dieu de la guerre / tyran", "main_rolls":["objects/d6thiswartyrantgodisoftencalled", "objects/d6heholdsdominionover", "objects/d6hisfollowersmust", ],"sub_rolls":[],},
];

fishing_catch = [
  {"title":"- Pêche en océan froid", "main_rolls":["objects/d10nearshorecatchyouhaulin", "objects/d10deepseacatchyouhaulin", "objects/d6rarecatchyouhaulin", ],"sub_rolls":[],},
  {"title":"- Pêche en océan chaud", "main_rolls":["objects/d8nearshorecatchyouhaulin", "objects/d10deepseacatchyouhaulin", "objects/d8rarecatchyouhaulin", ],"sub_rolls":[],},
  {"title":"- Pêche en eaux douces", "main_rolls":["objects/d10coldwatercatchyouhaulin", "objects/d10warmwatercatchyouhaulin", "objects/d6swampwatercatchyouhaulin", ],"sub_rolls":[],},
  {"title":"- Récolte de fruits de mer", "use":"Pour récolter des fruits de mer, le personnage doit disposer d'un piège de chasse et réussir un test de compétence survie (sag) avec un DD de 12. S'il maîtrise la compétence Survie, le joueur peut effectuer ce test avec un avantage. Le joueur ne peut récolter ses pièges qu'après 24 heures.", "main_rolls":[ "objects/d12seafood",],"sub_rolls":[],},
];


top.subrolls = [

  // dungeons/locations
  {"title":"2d6 Pièces du chateau", "singular":"Pièce de chateau", "id":"castle2d6rooms", "roll_type":"amount", "number":"2d6", "percent_to":"100", "percent_of":"100", "rolls":["dungeons/d20roomsthischamberis", "dungeons/castled20featuresyounotice",],},
  {"title":"4d6 Nombre d' d50 habitants du château", "singular":"Habitant du chateau", "id":"castle4d6amountofd50inhabitants", "roll_type":"type", "number":"4d6", "percent_to":"100", "percent_of":"100", "roll":castle_npcs,},
  {"title":"5d6 Pièces du chateau", "singular":"Pièce de chateau","id":"castle5d6rooms", "roll_type":"amount", "number":"5d6", "percent_to":"100", "percent_of":"100", "rolls":["dungeons/d20roomsthischamberis", "dungeons/castled20featuresyounotice",],},
  {"title":"10d6 Nombre d' d50 habitants du château", "singular":"Habitant du chateau", "id":"castle10d6amountofd50inhabitants", "roll_type":"type", "number":"10d6", "percent_to":"100", "percent_of":"100", "roll":castle_npcs,},
  {"title":"8d6 Pièces du chateau", "singular":"Pièce de chateau","id":"castle8d6rooms", "roll_type":"amount", "number":"8d6", "percent_to":"100", "percent_of":"100", "rolls":["dungeons/d20roomsthischamberis", "dungeons/castled20featuresyounotice",],},
  {"title":"16d6 Nombre d' d50 habitants du château", "singular":"Habitant du chateau", "id":"castle16d6amountofd50inhabitants", "roll_type":"type", "number":"16d6", "percent_to":"100", "percent_of":"100", "roll":castle_npcs,},
  {"title":"15d6 Pièces du chateau", "singular":"Pièce de chateau","id":"castle15d6rooms", "roll_type":"amount", "number":"15d6", "percent_to":"100", "percent_of":"100", "rolls":["dungeons/d20roomsthischamberis", "dungeons/castled20featuresyounotice",],},
  {"title":"30d6 Nombre d' d50 habitants du château", "singular":"Habitant du chateau", "id":"castle30d6amountofd50inhabitants", "roll_type":"type", "number":"30d6", "percent_to":"100", "percent_of":"100", "roll":castle_npcs,},
  {"title":"4d6 Pièces du monastère", "singular":"Pièce du monastère","id":"monastery4d6rooms", "roll_type":"amount", "number":"4d6", "percent_to":"100", "percent_of":"100", "rolls":["dungeons/d12thisbuildingchamberis", "dungeons/monasteryd20featuresyounotice",],},
  {"title":"4d6 Pièces de la prison", "singular":"Pièce de la prison", "id":"prison4d6rooms", "roll_type":"amount", "number":"4d6", "percent_to":"100", "percent_of":"100", "rolls":["dungeons/prisond10roomsthischamberis", "dungeons/prisond20featuresyounotice",],},
  {"title":"4d4 Geoliers", "singular":"Geolier", "id":"prison4d4jailers", "roll_type":"amount", "number":"4d4", "percent_to":"100", "percent_of":"100", "rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "dungeons/d8thejaileris", "dungeons/d4thejailerisconcernedabout", "dungeons/d4thejailerislookingto", "dungeons/d8thejailercarries",],},
  {"title":"10d6 Prisonniers ", "singular":"Prisonnier","id":"prison10d6prisoners", "roll_type":"amount", "number":"10d6", "percent_to":"100", "percent_of":"100", "rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "dungeons/d4theprisonerhas", "dungeons/d6theprisonerisherebecause",],},
  {"title":"6d6 Pièces du temple", "singular":"Pièce du temple", "id":"temple6d6rooms", "roll_type":"amount", "number":"6d6", "percent_to":"100", "percent_of":"100", "rolls":["dungeons/templed20thepurposeofthisroomis", "dungeons/templed20featuresyounotice",],},
  {"title":"6d6 Pièces de la tombe", "singular":"Pièce de la tombe", "id":"tomb6d6rooms", "roll_type":"amount", "number":"6d6", "percent_to":"100", "percent_of":"100", "rolls":["dungeons/tombd20thepurposeofthisroomis", "dungeons/tombd20featuresyounotice", ],},

  // factions
  {"title":"6d6 Artisans", "singular":"Artisan", "id":"guild6d6artisan", "roll_type":"amount", "number":"6d6", "percent_to":"100", "percent_of":"100", "rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "factions/guildd6theartisanis", "factions/guildd8theartisanhas", "factions/guildd8theartisanhas2", "factions/d6theartisanisparticularlyskilledat", "factions/d8theartisanislookingfor", "factions/d6theartisaniscarrying", "factions/guildd6theartisanis2", "factions/d6theartisandreamsof", ],},
  {"title":"6d6 Apprentits artisans", "singular":"Apprentit", "id":"guild6d6apprentice", "roll_type":"amount", "number":"6d6", "percent_to":"100", "percent_of":"100", "rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "factions/d4theapprenticeis", "factions/d4theapprenticeseekssomeoneto", ],},
  {"title":"6d6 Fanatiques", "singular":"Fanatique", "id":"6d6cultist", "roll_type":"amount", "number":"6d6", "percent_to":"100", "percent_of":"100", "rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "factions/d6thecultist", "factions/d10thecultistwears", "factions/d10thecultisthas", "factions/d10thecultistis", "factions/d10thecultistislookingfor", ],},
  {"title":"1d4 Compagnies marchande", "singular":"Compagnie marchande", "id":"1d4tradingcompany", "roll_type":"amount", "number":"1d4", "percent_to":"100", "percent_of":"100", "rolls":["factions/d6thistradingcompanysspecificspecialtyorpurposeis", "factions/d8thistradingcompanyiscontrolledby", ],},
  {"title":"6d6 Commerçants", "singular":"Commerçant", "id":"6d6shopkeeper", "roll_type":"amount", "number":"6d6", "percent_to":"100", "percent_of":"100", "rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "factions/d4theshopkeeperis", "factions/d4theshopkeeperseekssomeoneto", ],},
  {"title":"6d6 Marchants", "singular":"Marchant", "id":"6d6merchant", "roll_type":"amount", "number":"6d6", "percent_to":"100", "percent_of":"100", "rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "factions/d6themerchantis", "factions/d4themerchantwears", "factions/d4themerchantseekssomeoneto", "factions/d6themerchantcarries", "factions/d6currencybesidescointhemerchantwilltradein", ],},
  {"title":"6d6 Soldats", "singular":"Soldat", "id":"6d6soldier", "roll_type":"amount", "number":"6d6", "percent_to":"100", "percent_of":"100", "rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "factions/d12thesoldieris", "factions/d12thesoldierfightsfor", "factions/d12onthesoldiersfaceis", "factions/d10thesoldiercarries", ],},
  {"title":"6d6 Nobles", "singular":"Noble", "id":"6d6nobles", "roll_type":"amount", "number":"6d6", "percent_to":"100", "percent_of":"100", "rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "factions/d6thenobleis", "factions/d8thenobleseekssomeoneto", "factions/d6thenoblecarries", "factions/d8thenoblewears", "factions/d8thenoblehas", "npcs/d100lineagethisnobleis_noble", "npcs/d20racethisnobleis…_noble", "npcs/d20positionthisnobleis_noble", "npcs/d50secretsandmotivationthisnobleis_noble", "npcs/d100outwardappearanceandpresentationthisnoble_noble", "npcs/d50quirksandintereststhisnoble…_noble",],},
  {"title":"6d6 Braconniers", "singular":"Braconnier", "id":"6d6poachers", "roll_type":"amount", "number":"6d6", "percent_to":"100", "percent_of":"100", "rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "factions/d8thepoachersfavoritepreyincludes", "factions/d6thepoachershunt", ],},
  {"title":"6d6 Voleurs", "singular":"Voleur", "id":"6d6robbers", "roll_type":"amount", "number":"6d6", "percent_to":"100", "percent_of":"100", "rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "factions/d6therobberstypicallystrikewith", "factions/d8therobbersarenotoriousfor", ],},
  {"title":"6d6 Contrebandiers", "singular":"Contrebandier", "id":"6d6smugglers", "roll_type":"amount", "number":"6d6", "percent_to":"100", "percent_of":"100", "rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "factions/d6thesmugglingringsprimarymodusoperandiinvolves", "factions/d8theringissupportedby", ],},
  {"title":"6d6 Pirates", "singular":"Pirate", "id":"6d6pirates", "roll_type":"amount", "number":"6d6", "percent_to":"100", "percent_of":"100", "rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "factions/d12tattoothepiratehas", "factions/d12distinguishingfeaturethepiratehas", ],},
  {"title":"6d6 Barbares", "singular":"Barbare", "id":"6d6barbarians", "roll_type":"amount", "number":"6d6", "percent_to":"100", "percent_of":"100", "rolls":["npcs/dxmalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "npcs/d8thewarriorisarmoredin", "npcs/d12thewarrioriswielding", "npcs/d8thewarriorisalsocarrying", "npcs/d6thewarriorfightswith", "npcs/d12thewarrioris", "npcs/d12onthewarriorsfaceis", "npcs/d10onthewarriorsbodyis", ],},
  {"title":"4d4 Enqueteurs", "singular":"Enqueteur", "id":"4d4investigators", "roll_type":"amount", "number":"4d4", "percent_to":"100", "percent_of":"100", "rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "factions/d10theconstableis", "factions/d6theconstableworksfor", "factions/d12ontheconstablesfaceis", "factions/d10theconstablecarries", ],},
  {"title":"6d6 Gardes", "singular":"Garde", "id":"6d6guards", "roll_type":"amount", "number":"6d6", "percent_to":"100", "percent_of":"100", "rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/dxpersonality", "factions/d10theguardis", "factions/d6theguardworksfor", "factions/d12ontheguardsfaceis", "factions/d10theguardcarries", ],},

  // monsters
  {"title":"6d6 Goblins", "singular":"Goblin", "id":"6d6goblins", "roll_type":"amount", "number":"6d6", "percent_to":"100", "percent_of":"100", "rolls":["npcs/dxpersonality", "monsters/d12thegoblinisparticularlyskilledat", "monsters/d12thegoblinwields", "monsters/d12thegoblinwears", "monsters/d12thegoblinsfacehas", "monsters/d8thegoblinhas", ],},
  {"title":"6d6 Lycanthropes", "singular":"Lycanthrope", "id":"6d6lycanthropes", "roll_type":"amount", "number":"6d6", "percent_to":"100", "percent_of":"100", "rolls":["monsters/d12thebeastshiftertransformsinto", "monsters/d6thebeastshiftertransformsinvoluntarily", "monsters/d8whiletransformedthebeastshifterbehaves", "monsters/d8thebeastshifterlives", "monsters/d12thebeastshiftermakesitshome", "monsters/d8thebeastshifterhasatendencyto", "monsters/d8inhumanoidformthebeastshifterfightswith", "monsters/d12inhumanoidformthebeastshifterpresentsitselfas", "monsters/d12inhumanoidformthebeastshiftersfacehas", "monsters/d20thebeastshiftersfavoritepreyare",],},
  {"title":"1d4 Lycanthropes peu commun", "singular":"Lycanthrope", "id":"1d4uncommonlycanthropes", "roll_type":"amount", "number":"1d4", "percent_to":"100", "percent_of":"100", "rolls":["monsters/d20thebeastshiftertransformsinto", "monsters/d6thebeastshiftertransformsinvoluntarily", "monsters/d8whiletransformedthebeastshifterbehaves", "monsters/d8thebeastshifterlives", "monsters/d12thebeastshiftermakesitshome", "monsters/d8thebeastshifterhasatendencyto", "monsters/d8inhumanoidformthebeastshifterfightswith", "monsters/d12inhumanoidformthebeastshifterpresentsitselfas", "monsters/d12inhumanoidformthebeastshiftersfacehas", "monsters/d20thebeastshiftersfavoritepreyare",],},
  {"title":"6d6 Orcs", "singular":"Orc", "id":"6d6orcs", "roll_type":"amount", "number":"6d6", "percent_to":"100", "percent_of":"100", "rolls":["monsters/d8appearancetheorchas", "monsters/d6tattootheorchas", "monsters/d8roletheorcis", "monsters/d8skillevenamongorcstheorcisparticularlygoodat", "monsters/d8armortheorcisarmoredin", "monsters/d8weapontheorciswielding", "monsters/d6motivationtheorcislookingfor", ],},
  {"title":"1 Chef de guerre Orc", "singular":"Chef de guerre Orc", "id":"1orcwarlord", "roll_type":"amount", "number":"1d1", "percent_to":"100", "percent_of":"100", "rolls":["monsters/d4racethisorcisa", "monsters/d10skintheyhaveskincoloured", "monsters/d20appearancethewarlordhas", "monsters/d20traittheorcwarlordisknownbecause", "monsters/d20combatthewarlordisknowntofightwith", "monsters/d100bannertheorcclanhasabannerthatshows", "monsters/d20soldiersthewarlordsmainsoldiersandwarriorsare", "monsters/d20minionstheorcsarmyalsohas", "monsters/d20basewhennotontheoffensivetheclanisbasedoutof", ],},
  {"title":"4d6 Loups", "singular":"Loup", "id":"4d6wolves", "roll_type":"amount", "number":"4d6", "percent_to":"100", "percent_of":"100", "rolls":["monsters/d10colorthewolfscoatis", "monsters/d10markingsthewolfhas", "monsters/d12eyesthewolfseyesare", "monsters/d12mannerthewolfis", "monsters/d6huntingthewolfprefersto", "monsters/d10favoritepreyifgiventhechoicethewolfwillopttoeat", "monsters/d10packthewolfis", ],},

  // objects
  {"title":"1d12 Dieux", "singular":"Dieu", "id":"1d12gods", "roll_type":"type", "number":"1d12", "percent_to":"100", "percent_of":"100", "roll":pantheon,},
  {"title":"3d6 Relations", "singular":"Relation", "id":"3d6relationships", "roll_type":"amount", "number":"3d6", "percent_to":"100", "percent_of":"100", "rolls":["objects/d10intrapantheonrelationshipsthisdeityisthe_____ofthatdeity", "objects/d6thegodsare", "objects/d6thegodsrelationshipwiththeirfollowers", ],},
  {"title":"6d6 Livres", "singular":"Livre", "id":"6d6books", "roll_type":"amount", "number":"6d6", "percent_to":"100", "percent_of":"100", "rolls":["objects/d20thebookssubjectis", "objects/d10thebooksconditionis", "objects/d12thebookscoveris", "objects/d10thebookis", ],},
  {"title":"6d6 Marins", "singular":"Marin", "id":"6d6sailors", "roll_type":"amount", "number":"6d6", "percent_to":"100", "percent_of":"100", "rolls":["npcs/d12thesailoris", "npcs/d20tattoothesailorhas", "npcs/d20thesailorstattooisamementoof", "npcs/d12distinguishingfacialfeaturethesailorhas", "npcs/d12accessoriesthesailoriswearingorcarrying", "npcs/d12attheendofalongvoyagethesailoriseagerto", "npcs/d12whendrunkthesailorisproneto", "npcs/d12whatthesailorreallywantsisto", ],},
  {"title":"1d4 jours à pêcher", "singular":"Prise", "id":"1d4catch", "roll_type":"type", "number":"1d4", "percent_to":"100", "percent_of":"100", "roll":fishing_catch,},

  // npcs
  {"title":"3d6 Nombre de d7 voyageurs de la caravane marchande", "singular":"Voyageur de la caravane marchande", "id":"merchant3d6amountofd7travelers", "roll_type":"type", "number":"3d6", "percent_to":"100", "percent_of":"100", "roll":merchant_npcs,},
  {"title":"3d6 Nombre de d6 supports militaire", "singular":"Support militaire", "id":"military3d6amountofd6support", "roll_type":"type", "number":"3d6", "percent_to":"100", "percent_of":"100", "roll":military_npcs,},
  {"title":"1 Commandant militaire", "singular":"Commandant militaire", "id":"1militarycommander", "roll_type":"amount", "number":"1d1", "percent_to":"100", "percent_of":"100", "rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/d6thecommanderis", "npcs/d6thecommanderislookingfor", "npcs/d4thecommanderistryingtoavoid", "npcs/d6thecommandercarries",  ],},
  {"title":"1d4 Geoliers", "singular":"Geolier", "id":"1d4jailers", "roll_type":"amount", "number":"1d4", "percent_to":"100", "percent_of":"100", "rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname", "npcs/d6thejaileris", "npcs/d4thejailerisconcernedabout", "npcs/d4thejailerislookingto", "npcs/d8thejailercarries",],},
  {"title":"1d4 Tortionnaires", "singular":"Tortionnaire", "id":"1d4torturers", "roll_type":"amount", "number":"1d4", "percent_to":"100", "percent_of":"100", "rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname",  "npcs/d4thetortureris", "npcs/d4thetorturerislookingto", "npcs/d6thetorturercarries",],},
  {"title":"3d6 Prisonniers", "singular":"Prisonnier", "id":"3d6prisoners", "roll_type":"amount", "number":"3d6", "percent_to":"100", "percent_of":"100", "rolls":["npcs/dxmalefirstname", "npcs/dxfemalefirstname", "npcs/dxsurname",  "npcs/d4theprisonerhas", "npcs/d6theprisonerisherebecause", "npcs/d4theprisonerhas",],},

  // settlements
  {"title":"8d4 Monuments/Quartiers", "singular":"Monument/Quartier", "id":"8d4landmarks", "roll_type":"amount", "number":"8d4", "percent_to":"100", "percent_of":"100", "rolls":["settlements/d20landmarkyouseeaan", "settlements/d20thispartofthecityisthe", ],},
  {"title":"4d4 Monuments/Quartiers", "singular":"Monument/Quartier", "id":"4d4landmarks", "roll_type":"amount", "number":"4d4", "percent_to":"100", "percent_of":"100", "rolls":["settlements/d20landmarkyouseeaan", "settlements/d20thispartofthecityisthe", ],},
  {"title":"2d4 Monuments/Quartiers", "singular":"Monument/Quartier", "id":"2d4landmarks", "roll_type":"amount", "number":"2d4", "percent_to":"100", "percent_of":"100", "rolls":["settlements/d20landmarkyouseeaan", "settlements/d20thispartofthecityisthe", ],},
  {"title":"1d4 Monuments/Quartiers", "singular":"Monument/Quartier", "id":"1d4landmarks", "roll_type":"amount", "number":"1d4", "percent_to":"100", "percent_of":"100", "rolls":["settlements/d20landmarkyouseeaan", "settlements/d20thispartofthecityisthe", ],},
  {"title":"10d4 Noms de rues", "singular":"Nom de rue", "id":"10d4streetnames", "roll_type":"amount", "number":"10d4", "percent_to":"100", "percent_of":"100", "rolls":["settlements/d20thelocalscallthisstreet", ],},
  {"title":"8d4 Noms de rues", "singular":"Nom de rue", "id":"8d4streetnames", "roll_type":"amount", "number":"8d4", "percent_to":"100", "percent_of":"100", "rolls":["settlements/d20thelocalscallthisstreet", ],},
  {"title":"4d4 Noms de rues", "singular":"Nom de rue", "id":"4d4streetnames", "roll_type":"amount", "number":"4d4", "percent_to":"100", "percent_of":"100", "rolls":["settlements/d20thelocalscallthisstreet", ],},
  {"title":"2d4 Noms de rues", "singular":"Nom de rue", "id":"2d4streetnames", "roll_type":"amount", "number":"2d4", "percent_to":"100", "percent_of":"100", "rolls":["settlements/d20thelocalscallthisstreet", ],},
  {"title":"10d6 Nombre de d50 habitants", "singular":"Habitant", "id":"10d6amountofd50towninhabitants", "roll_type":"type", "number":"10d6", "percent_to":"100", "percent_of":"100", "roll":town_npcs,},
  {"title":"8d6 Nombre de d50 habitants", "singular":"Habitantt", "id":"8d6amountofd50towninhabitants", "roll_type":"type", "number":"8d6", "percent_to":"100", "percent_of":"100", "roll":town_npcs,},
  {"title":"6d6 Nombre de d50 habitants", "singular":"Habitant", "id":"6d6amountofd50towninhabitants", "roll_type":"type", "number":"6d6", "percent_to":"100", "percent_of":"100", "roll":town_npcs,},
  {"title":"4d6 Nombre de d50 habitants", "singular":"Habitant", "id":"4d6amountofd50towninhabitants", "roll_type":"type", "number":"4d6", "percent_to":"100", "percent_of":"100", "roll":town_npcs,},
  {"title":"Noms de tavernes", "singular":"Nom de taverne", "id":"1d1TavernNames", "roll_type":"type", "number":"1d1", "percent_to":"100", "percent_of":"100", "roll":tavern_names,},


];
