// factions.js
//


top.factions = [



{"title": "d20 Ce mercenaire est un", "id":"d20thismercenaryisa", "roll":[
"voyageur de toujours",
"déserteur désabusé",
"aventurier grivois",
"professionnel froid",
"soldat de fortune en quête de gloire",
"chercheur de savoirs et d’expériences",
"guerrier fier en quête d’un adversaire digne",
"roturier cherchant à se faire de l’argent facilement",
"fripouille attachante",
"vétéran réputé",
"sadique assoiffé de sang",
"ancien mendiant devenu mercenaire",
"réfugié aguerri",
"ancien membre d’une armée dissoute",
"mercenaire rusé et calculateur",
"en quête de purification du monde des bandits ou des monstres",
"ancien garde de la ville déshonoré",
"esclave en fuite",
"marchand reconverti en tueur"
]},
{"title": "d8 dont les compétences sont celles d’un (option : ajouter un pile ou face)", "id":"d8theirskillsetisthatofaoptionaladdacoinflip", "roll":[
"Chasseur ou Trappeur",
"Voleur ou Assassin",
"Mage ou Enchanteur",
"Guérisseur ou Alchimiste",
"Chasseur de monstres ou Exterminateur",
"Gladiateur ou Duelliste",
"Clerc ou Barde"
]},
{"title": "d10 son arme principale est", "id":"d10theirprimaryweaponisa", "roll":[
"Hache de bataille",
"Scimitarre",
"Hallebarde",
"Arc",
"Épée courte et dague",
"Arbalète",
"Massue de guerre",
"Bâton",
"Marteau"
]},
{"title": "d8 qui se distingue par", "id":"d8whichstandsoutforbeing", "roll":[
"une matière inhabituelle",
"un bourdonnement ou une lueur surnaturelle",
"une fabrication manifestement exceptionnelle",
"un design étranger",
"un entretien médiocre et une saleté apparente",
"un état proche de la rupture",
"une gravure d’un nom"
]},
{"title": "d6 il est aussi doué pour", "id":"d6theyarealsogoodat", "roll":[
"Jeux (d6) : 1. Cartes ; 2. Dés ; 3. Bras de fer ; 4. Stratégie sur plateau ; 5. Claque-main ; 6. Lancer de fer à cheval",
"Arme secondaire (d6) : 1. Couteaux de lancer ; 2. Javelot ; 3. Fléau ; 4. Combat à mains nues ; 5. Dards ; 6. Fouet",
"Art de la scène (d6) : 1. Chant ; 2. Danse ; 3. Conte ; 4. Théâtre ; 5. Jonglage ; 6. Instrument de musique",
"Artisanat (d6) : 1. Forge ; 2. Construction ; 3. Couture ; 4. Brassage ; 5. Menuiserie ; 6. Cuisine",
"Compétence d’aventure (d6) : 1. Géographie ou Navigation ; 2. Crochetage ; 3. Entretien de l’équipement ; 4. Filature ; 5. Équitation ; 6. Commerce"
]},
{"title": "d40 sa caractéristique principale est", "id":"d40theirmaindistinguishingfeatureis", "roll":[
"des vêtements colorés",
"une cicatrice faciale défigurante",
"le refus d’accomplir certains types de missions",
"des origines manifestement étrangères",
"une coiffure ou une couleur de cheveux étrange",
"une aura de peur / respect / professionnalisme",
"une ressemblance frappante avec un criminel recherché dans une ville voisine",
"un état d’ébriété constant ou une gueule de bois perpétuelle",
"une beauté peu commune",
"des bijoux voyants",
"un style de combat inhabituel",
"le port de gris-gris ou d’amulettes de protection",
"une tendance au mutisme",
"l’affichage des couleurs de son seigneur ou royaume d’origine",
"une obsession pour la séduction",
"un langage vulgaire extrême",
"la compagnie d’un animal de compagnie",
"une dentition catastrophique",
"le fait de fumer la pipe",
"un âge très avancé",
"le port de symboles religieux",
"une voix forte et pénétrante",
"des blessures visibles",
"le port d’un trophée",
"un petit livre transporté dans une sacoche",
"une forte corpulence",
"des yeux de couleurs différentes (hétérochromie)",
"un trouble de l’élocution",
"le fait de toujours manger quelque chose",
"le port d’un cache-œil",
"une démarche boiteuse",
"un habillement tout en noir",
"une aptitude avec les enfants",
"un air profondément déprimé",
"une oreille manquante",
"des vêtements inadaptés au climat",
"le fait de cracher constamment par terre",
"un rire insupportable",
"le fait de manipuler sans cesse une pièce de monnaie"
]},
{"title": "d4 son niveau de compétence est", "id":"d4theirlevelofcompetenceis", "roll":[
"Moyen",
"Bon",
"Excellent"
]},
{"title": "d6 ses tarifs sont", "id":"d6theirpricingis", "roll":[
"Bas",
"Abordables",
"Légèrement au-dessus de la moyenne",
"Élevés",
"Exorbitants"
]},


{"title": "d12 Le symbole de la guilde est...", "id":"d12theguildssymbolis", "roll":[
"Un crâne.",
"Un œil.",
"Une flamme.",
"Une dague.",
"Une faux.",
"Une flèche.",
"Un poisson.",
"Un corbeau.",
"Un rat.",
"Un scorpion.",
"Une araignée.",
"Un serpent."
]},
{"title": "d20 La méthode d'exécution préférée de la guilde est...", "id":"d20theguildspreferredmethodofexecutionis", "roll":[
"Un poison ingéré ou une réaction allergique.",
"Une maladie mortelle (mais peu contagieuse).",
"Un poison de contact appliqué sur une arme.",
"Une flèche ou un carreau à distance.",
"Un coup de couteau dans la poitrine ou dans le dos.",
"De multiples coups de couteau.",
"La gorge tranchée.",
"Les entrailles arrachées ou l’éviscération.",
"L’écorchement ou le scalp.",
"La décapitation.",
"L’étranglement.",
"La pendaison.",
"Être enterré vivant.",
"La noyade.",
"Être bouilli vivant.",
"Être jeté d’un toit.",
"Par de l’acide (versé ou immersion).",
"Une explosion de feu.",
"Être brûlé vif.",
"Être donné en pâture aux bêtes."
]},
{"title": "d12 Les membres de la guilde sont généralement armés de...", "id":"d12guildmemberstypicallyarmthemselveswith", "roll":[
"Dagues et épées courtes empoisonnées.",
"Couteaux de lancer.",
"Dagues surdimensionnées.",
"Dagues dentelées.",
"Dagues et arbalètes.",
"Haches et couteaux.",
"Arcs et flèches.",
"Épées courtes et arbalètes.",
"Faucilles et faux.",
"Garrottes et dagues.",
"Lames exotiques et sarbacanes.",
"Bolas et projectiles empoisonnés."
]},
{"title": "d6 Les membres de la guilde opèrent généralement...", "id":"d6guildmemberstypicallyoperate", "roll":[
"Seuls.",
"Par paires.",
"En petits groupes.",
"En infiltrant une organisation.",
"En usurpant l'identité d'une personne précise.",
"À la vue de tous."
]},
{"title": "d6 Les membres de la guilde connaissent généralement...", "id":"d6guildmemberstypicallyknow", "roll":[
"Très peu d'autres membres de la guilde.",
"Plusieurs autres membres de la guilde.",
"Les détails de l'organisation de la guilde.",
"Rien au sujet des dirigeants de la guilde.",
"Les noms des dirigeants sans les avoir jamais rencontrés.",
"Un dirigeant de la guilde mais aucun autre membre."
]},
{"title": "d12 Le chef de la guilde est...", "id":"d12theguildsleaderis", "roll":[
"Un mégalomane dangereux.",
"Un démagogue charismatique.",
"Un étranger mystérieux.",
"Un voleur talentueux.",
"Une figure publique bien connue.",
"Un tueur impitoyable.",
"Une femme fatale.",
"Un voleur charmeur.",
"Un bretteur séduisant.",
"Un brute épaisse.",
"Un fanatique religieux.",
"Un soldat vétéran."
]},
{"title": "d6 Les objectifs de la guilde incluent (la hiérarchie et les exécutants peuvent avoir des objectifs différents)...", "id":"d6theguildsgoalsincludeleadershipandrankandfilememberscouldhavedifferentgoals", "roll":[
"Étendre leur clientèle.",
"Corrompre et influencer la politique locale ou régionale.",
"Éliminer une guilde rivale dans la même ville ou région.",
"Éliminer une guilde rivale dans une ville ou région étrangère.",
"Intimider les masses.",
"Inciter à la révolte populaire."
]},
{"title": "d8 La guilde refuse les contrats visant à tuer...", "id":"d8theguildrefusestotakecontractstokill", "roll":[
"Des femmes.",
"De jeunes enfants.",
"Des nobles ou citoyens éminents.",
"Des prêtres et des moines.",
"Des paysans et gens du peuple.",
"Des étrangers et voyageurs.",
"Des membres de la famille du client.",
"D'autres criminels."
]},
{"title": "d8 Les membres de la guilde frappent généralement avec...", "id":"d8guildmemberstypicallystrikewith", "roll":[
"Des tactiques de frappe et fuite.",
"Des embuscades.",
"Des diversions.",
"Une stratégie d'attaque minutieusement planifiée.",
"Une stratégie de fuite bien pensée.",
"L’effet de surprise.",
"L’annonce de leur présence.",
"Aucune pensée pour l’évasion."
]},
{"title": "d8 Les membres de la guilde planifient généralement leurs attaques pour...", "id":"d8guildmemberstypicallyplantheirattacksfor", "roll":[
"Juste après le lever du soleil.",
"Le zénith.",
"Juste après le coucher du soleil.",
"Au cœur de la nuit.",
"Le coup de minuit.",
"Après minuit.",
"Les toutes premières heures du matin.",
"Juste avant l’aube."
]},
{"title": "d12 Le quartier général de la guilde est caché dans ou près de...", "id":"d12theguildsheadquartersishiddeninornear", "roll":[
"la résidence du chef ou d’un haut membre de la guilde.",
"l’atelier d’un artisan ou une halle de guilde.",
"le bureau d’un marchand.",
"une taverne.",
"un bordel.",
"un entrepôt ou un chantier naval.",
"un complexe religieux.",
"les égouts de la ville.",
"la mairie.",
"une ancienne halle ou entrepôt de guilde.",
"une armurerie ou des casernes.",
"la demeure d’un riche citoyen ou notable."
]},
{"title": "d12 La guilde est crainte ou respectée par...", "id":"d12theguildisfearedorrespectedby", "roll":[
"les pêcheurs et marins.",
"les mendiants et orphelins.",
"les marchands et changeurs.",
"les nobles et dirigeants.",
"les politiciens et magistrats.",
"les gardes et shérifs.",
"les soldats et guerriers.",
"les voleurs et criminels.",
"les serviteurs et esclaves.",
"les prêtres et sages.",
"les femmes et enfants.",
"d’autres assassins."
]},
{"title": "d20 Il s'agit d'une guilde de...", "id":"d20thisisaguildfor", "roll":[
"mineurs.",
"forestiers.",
"fermiers.",
"ouvriers.",
"forgerons.",
"barbiers et dentistes.",
"bijoutiers.",
"bouffons, artistes et comédiens.",
"constructeurs navals.",
"tanneurs, pelletiers et cordonniers.",
"bouchers.",
"serruriers et cloutiers.",
"potier et teinturiers.",
"selliers, maréchaux-ferrants et palefreniers.",
"menuisiers, charrons et tonneliers.",
"maçons.",
"tisserands et tailleurs.",
"orfèvres et horlogers.",
"professionnels instruits (d8): 1. alchimistes; 2. architectes; 3. calligraphes; 4. historiens; 5. avocats et juges; 6. scribes; 7. ingénieurs de siège; 8. écrivains.",
"artisans et artistes spécialisés (d10): 1. brasseurs; 2. chandeliers; 3. chefs cuisiniers; 4. souffleurs de verre; 5. reconstituteurs historiques; 6. forgerons de mithril; 7. musiciens; 8. peintres; 9. sculpteurs; 10. orfèvres."
]},
{"title": "d8 Le statut et contrôle de cette guilde est...", "id":"d8thisguildsstatusandcontrolis", "roll":[
"pauvre ; bien qu’ancienne, la guilde est en déclin et peine à maintenir son pouvoir.",
"tout juste fondée, elle recrute frénétiquement pour gagner en influence.",
"en forte croissance, un événement récent lui a apporté fortune et pouvoir.",
"ralenti, un concurrent en ascension ronge lentement ses profits.",
"absolu, elle domine entièrement son domaine.",
"irrégulier, variant au gré des marchés et de la chance.",
"incontesté, elle exerce une domination totale sur les autres guildes locales.",
"douteux, certains membres opèrent en dehors du contrôle officiel."
]},
{"title": "d8 Les affaires illicites de cette guilde comprennent...", "id":"d8thisguildsillicitaffairscomprise", "roll":[
"absolument rien, ils sont des modèles de vertu.",
"quelques oublis fiscaux, bien sûr accidentels.",
"quelques faveurs politiques obtenues subtilement.",
"des pratiques de prix avantageux grâce à la cupidité des dirigeants.",
"des prix fixés, des pots-de-vin mineurs et l’indignation des prêtres.",
"corruption modérée, arnaques mineures et relations avec la guilde des voleurs.",
"corruption rampante, grands pots-de-vin, et liens avec des assassins.",
"pactes infernaux, contrefaçon massive et trahison comme routine du mardi matin."
]},
{"title": "d8 Le quartier général de cette guilde est...", "id":"d8thisguildsheadquartersis", "roll":[
"la résidence personnelle du ou des dirigeants, un grand manoir.",
"le sous-sol poussiéreux de la mairie.",
"une haute maison de ville étroite penchée dans la rue.",
"un navire amarré (même dans une ville sans rivière !).",
"un pavillon ouvert au centre du bazar.",
"également une grande banque prestigieuse.",
"un demi-plan opulent caché dans une ruelle sombre.",
"partagé avec toutes les autres guildes, la guilde des voleurs loge dans les égouts dessous."
]},
{"title": "d6 Quête mineure : Vous devez aller chercher une cargaison depuis...", "id":"d6minorquestyoumustfetchashipmentofgoodsfrom", "roll":[
"les portes de la ville, bloquées par un bureaucrate tatillon.",
"le village voisin, empêtrée dans une superstition locale.",
"une autre ville proche, à cause d’un malentendu d’expédition.",
"la nature elle-même, pour apprendre les bases du métier.",
"les coffres de la banque, sous hypothèque.",
"l’autre côté de la pièce où l’on vous donne la mission."
]},
{"title": "d6 Quête standard : La guilde a perdu l’accès à ses ressources à cause de...", "id":"d6standardquestrecentlytheguildhaslostaccesstorawmaterialsormanufacturingbecauseof", "roll":[
"un partenariat raté avec un fournisseur ou un fonctionnaire.",
"un blocus commercial à résoudre.",
"des voleurs ciblant la guilde (peut-être négociable).",
"un maître qui les gaspille, vous devez en récolter vous-même.",
"un décret d’un fonctionnaire les interdisant.",
"tout l’or dépensé en pots-de-vin, il ne reste rien pour la production."
]},
{"title": "d6 Quête majeure : La guilde veut que vous alliez chercher un matériau ou une créature rare depuis...", "id":"d6majorquesttheguildwouldlikeyoutofetchararecreatureormaterialfrom", "roll":[
"le marché de la Cité de Laiton.",
"les forges d'une ancienne forteresse naine.",
"un paisible pâturage au cœur d’Arborée.",
"une île lointaine remplie de magie noire et de cannibales.",
"un mirage mystique apparaissant tous les cent ans dans un désert.",
"le Plan des Rats (ou un lieu tout aussi sordide)."
]},
{"title": "d4 L’apprenti est...", "id":"d4theapprenticeis", "roll":[
"ennuyé.",
"avide d’apprendre.",
"frustré par ses erreurs.",
"nerveux et regardant partout."
]},
{"title": "d4 L’apprenti cherche quelqu’un pour...", "id":"d4theapprenticeseekssomeoneto", "roll":[
"lui donner quelques conseils dans son art.",
"acheter un objet fabriqué par lui.",
"raconter une histoire qui l’inspire.",
"fuir pour boire un verre et échanger des baisers."
]},
{"title": "d6 L’artisan est...", "id":"guildd6theartisanis", "roll":[
"un jeune compagnon.",
"un compagnon moyen.",
"un compagnon talentueux.",
"un vétéran de l’artisanat.",
"un maître reconnu.",
"un ancien du métier."
]},
{"title": "d8 L’artisan a...", "id":"guildd8theartisanhas", "roll":[
"un sourire amical.",
"des yeux perçants.",
"les yeux larmoyants.",
"une moue obstinée.",
"un air morose.",
"une dent manquante.",
"les yeux fatigués.",
"un sourire en coin amusé."
]},
{"title": "d8 L’artisan a...", "id":"guildd8theartisanhas2", "roll":[
"une claudication.",
"une bosse.",
"les mains tremblantes sauf lorsqu’il travaille.",
"l’habitude de baisser les yeux.",
"un nez bulbeux.",
"une cicatrice de brûlure sur le visage.",
"une fine moustache.",
"une moustache épaisse."
]},
{"title": "d6 L’artisan est particulièrement doué pour...", "id":"d6theartisanisparticularlyskilledat", "roll":[
"la fabrication d’un type d’objet spécifique.",
"l’identification de matières premières de qualité.",
"l’application des finitions.",
"la formation des apprentis.",
"la négociation des prix.",
"la gestion des jeux de pouvoir dans la guilde."
]},
{"title": "d8 L’artisan est à la recherche de...", "id":"d8theartisanislookingfor", "roll":[
"un nouvel apprenti.",
"un compagnon à embaucher.",
"matériaux rares.",
"meilleurs outils.",
"quelqu’un avec qui parler boutique.",
"quelqu’un qui a assisté à un événement sportif récent.",
"quelqu’un qui ira voir un événement sportif prochainement.",
"une bonne chope de bière forte."
]},
{"title": "d6 L’artisan porte...", "id":"d6theartisaniscarrying", "roll":[
"ses outils de travail.",
"des matières premières.",
"un objet fini.",
"quelques pièces.",
"une liste de tâches griffonnée sur un parchemin.",
"un trousseau de nombreuses clés.",
"une pipe et du tabac.",
"une flasque de whisky."
]},
{"title": "d6 L’artisan est...", "id":"guildd6theartisanis2", "roll":[
"un membre bien connu de la guilde.",
"un leader établi ou en devenir dans la guilde.",
"un nouveau venu ayant récemment déménagé depuis une région lointaine.",
"un membre discret qui évite la politique de guilde.",
"en désaccord avec les dirigeants de la guilde.",
"le chouchou de certains chefs de guilde."
]},
{"title": "d6 L’artisan rêve de...", "id":"d6theartisandreamsof", "roll":[
"créer un chef-d'œuvre de son art.",
"diriger la guilde.",
"prendre une retraite paisible.",
"partir à la retraite riche.",
"tout abandonner.",
"mener une vie d’aventure."
]},
{"title": "d12 Les cultistes vénèrent...", "id":"d12thecultistsrevere", "roll":[
"un dragon.",
"un seigneur démon.",
"un archidiable.",
"un ancien héros mort depuis longtemps.",
"un ancien méchant mort depuis longtemps.",
"un dieu déchu.",
"une créature aberrante.",
"un être élémentaire.",
"un primordial.",
"des esprits primordiaux.",
"un exarque d’un dieu.",
"leur propre chef de culte."
]},
{"title": "d10 Les cultistes se réunissent dans...", "id":"d10thecultistsmeetin", "roll":[
"une salle secrète d’un temple célèbre.",
"la cave d’une taverne populaire.",
"une pièce secrète d’un bâtiment de guilde connu.",
"la cave d’un riche marchand.",
"les égouts de la ville.",
"des catacombes anciennes sous la ville.",
"une cabane à la campagne.",
"une grotte sombre et inquiétante.",
"une pièce gardée dans un château.",
"les rayonnages d’une grande bibliothèque."
]},
{"title": "d20 Le chef du culte est...", "id":"d20thecultsleaderis", "roll":[
"un fidèle acolyte.",
"un enseignant dogmatique.",
"un guérisseur compétent.",
"un prêcheur charismatique.",
"un érudit excentrique.",
"un fanatique virulent.",
"un dangereux mégalomane.",
"un démagogue charismatique.",
"un étranger mystérieux.",
"une figure publique bien connue.",
"un tueur impitoyable.",
"une séductrice fatale.",
"un voleur charmeur.",
"un noble puissant.",
"un artiste talentueux.",
"un fanatique religieux.",
"un vétéran de guerre.",
"un artisan humble.",
"un ancien héros revenu à la vie.",
"la réincarnation d’un dieu."
]},
{"title": "d6 Les membres du culte sont principalement composés de...", "id":"d6thecultsmembershipisprimarilymadeupof", "roll":[
"pauvres et opprimés (d4): 1. mendiants; 2. ouvriers; 3. domestiques; 4. esclaves.",
"l’élite fortunée (d4): 1. chefs de guilde; 2. marchands; 3. nobles; 4. royauté.",
"une branche d’une autre religion (d8): 1. dieu du soleil; 2. mère terre; 3. dieu de la mort; 4. déesse de la chasse; 5. déesse de l’amour; 6. dieu des tempêtes; 7. dieu farceur; 8. dieu de la guerre.",
"membres d’un même métier (d8): 1. forgerons; 2. charpentiers; 3. fermiers; 4. pêcheurs; 5. mineurs; 6. soldats; 7. tailleurs de pierre; 8. tisserands.",
"membres d’une même race (d8): 1. nains; 2. elfes; 3. gnomes; 4. gobelins; 5. sang-mêlés; 6. halfelins; 7. humains; 8. reptiliens.",
"personnes de toutes les classes sociales."
]},
{"title": "d8 Les pratiques du culte incluent (les chefs et les croyants peuvent avoir des pratiques différentes)...", "id":"d8thecultspracticesinvolveleadershipandbelieverscouldadheretodifferentpractices", "roll":[
"sacrifices d’animaux (d10): 1. taureaux; 2. veaux; 3. chats; 4. poules; 5. chiens; 6. chèvres; 7. pigeons; 8. lapins; 9. béliers; 10. oiseaux chanteurs.",
"sacrifices humains (d6): 1. enfants; 2. personnes âgées; 3. prostituées; 4. infidèles; 5. prêtres/prêtresses; 6. vierges.",
"automutilation (d10): 1. bras; 2. dos; 3. joue; 4. torse; 5. oreille; 6. œil; 7. pieds; 8. doigt; 9. parties génitales; 10. nez.",
"offrandes brûlées (d4): 1. herbes; 2. encens; 3. viande; 4. prisonniers.",
"offrandes d’or, de gemmes et d’objets précieux.",
"incantations étranges.",
"actes publics de violence (d4): 1. passages à tabac; 2. pillages; 3. meurtres; 4. émeutes.",
"rites sexuels rituels (d4): 1. bestialité; 2. reproduction; 3. dépucelage; 4. orgies."
]},
{"title": "d8 Les objectifs du culte (les chefs et les croyants peuvent avoir des buts différents)...", "id":"d8thecultsgoalsleadershipandbelieverscouldhavedifferentgoals", "roll":[
        "Dominer la ville ou la région.",
        "Détruire la ville ou la région.",
        "Réincarner un être ancien et oublié.",
        "Déclarer la guerre à une ville ou nation rivale.",
        "Se rebeller contre les élites.",
        "Tuer les non-croyants.",
        "Ouvrir un portail vers un autre plan.",
        "Libérer une entité puissante prisonnière.",
    ]},
    {"title": "d12 Les membres du culte doivent suivre une règle stricte concernant...", "id":"d12thecultsmembersmustfollowastrictruleregarding", "roll":[
        "Porter une fleur dans les cheveux ou à la boutonnière (d4) : 1. lys ; 2. orchidée ; 3. rose ; 4. tulipe.",
        "Les tendances vestimentaires.",
        "L’entretien de leur arme personnelle (d4) : 1. gourdin ; 2. dague ; 3. hachette ; 4. bâton.",
        "Le traitement des animaux de compagnie.",
        "La manière de monter à cheval.",
        "La tenue de culte.",
        "La tenue de tous les jours.",
        "Le régime alimentaire.",
        "Les routines d’exercice.",
        "Le bain.",
        "La coiffure.",
        "Le brossage de dents.",
    ]},
    {"title": "d12 Les membres du culte craignent ou évitent soigneusement...", "id":"d12thecultsmembersareparticularlyafraidofortakesspecialcaretoavoid", "roll":[
        "Les lieux sacrés.",
        "Le clair de lune.",
        "La lumière du soleil.",
        "Traverser de l’eau courante.",
        "Les objets pointus en bois.",
        "L’ail.",
        "Les objets en argent.",
        "Les reliques divines.",
        "Dormir à la belle étoile.",
        "Le lait et le fromage.",
        "Manger de la viande.",
        "La sobriété.",
    ]},
    {"title": "d6 Le cultiste...", "id":"d6thecultist", "roll":[
        "Est un fervent croyant très vocal.",
        "Est un fou délirant.",
        "Est un croyant silencieux et fervent.",
        "A des doutes mais reste loyal au chef du culte.",
        "A des doutes mais a trop peur pour les exprimer.",
        "Se fiche de la religion, il est là pour d’autres raisons.",
    ]},
    {"title": "d10 Le cultiste porte...", "id":"d10thecultistwears", "roll":[
        "Un bandage au pouce.",
        "Un tatouage de symbole sacré sur le visage.",
        "Un tatouage représentant une icône maléfique.",
        "Une corde d’ail autour du cou.",
        "Une robe déchirée au genou.",
        "Une robe en soie fine.",
        "Une grosse bague en or à un doigt.",
        "Une robe à capuche.",
        "Une robe ornée d’un symbole sacré.",
        "Une barbe fournie.",
    ]},
    {"title": "d10 Le cultiste a...", "id":"d10thecultisthas", "roll":[
        "Une dague cérémonielle à la main.",
        "Un livre qui dépasse de sa poche.",
        "Une grande cicatrice à la gorge.",
        "Les cheveux sales et emmêlés.",
        "La tête rasée.",
        "Des cicatrices aux poignets.",
        "Un menton proéminent.",
        "Un sourire maniaque.",
        "Une moue dédaigneuse.",
        "Un trou entre les deux dents de devant.",
    ]},
    {"title": "d10 Le cultiste est...", "id":"d10thecultistis", "roll":[
        "En train de fredonner une incantation inquiétante.",
        "En sueur.",
        "À bout de souffle.",
        "Pris de tics nerveux.",
        "En train de rire hystériquement.",
        "En train de marmonner.",
        "Pris d’une quinte de toux.",
        "En train de murmurer une prière.",
        "Boitant.",
        "Empestant le vin.",
    ]},
    {"title": "d10 Le cultiste cherche...", "id":"d10thecultistislookingfor", "roll":[
        "Des moyens d’impressionner le chef du culte.",
        "Des astuces pour séduire le chef du culte.",
        "Un moyen d’assassiner le chef du culte.",
        "Quelque chose qui plaira à son dieu.",
        "Quelque chose à manger.",
        "Quelque chose à tuer.",
        "Des moyens de faire progresser les objectifs du culte.",
        "De nouveaux recrues.",
        "Des érudits religieux pour débattre.",
        "Une bouteille de vin.",
    ]},
    {"title": "d12 Les couleurs de la troupe de mercenaires sont...", "id":"d12themercenarytroopscolorsare", "roll":[
        "Noir.",
        "Rouge / écarlate.",
        "Or.",
        "Vert forêt.",
        "Bleu royal.",
        "Brun / castor.",
        "Gris foncé / acier.",
        "Bordeaux.",
        "Bleu marine.",
        "Brun foncé / chocolat.",
        "Gris bleuté / acier.",
        "Vert olive.",
    ]},
    {"title": "d20 La bannière de la troupe de mercenaires arbore...", "id":"d20themercenarytroopsbannerfeatures", "roll":[
        "Un crâne.",
        "Un fantôme.",
        "Un poing serré.",
        "Une flamme.",
        "Une flèche.",
        "Une dague.",
        "Une épée.",
        "Un marteau.",
        "Le soleil.",
        "La lune.",
        "Une chauve-souris.",
        "Un taureau.",
        "Un dragon.",
        "Un faucon.",
        "Un lion.",
        "Un corbeau.",
        "Un scorpion.",
        "Un serpent.",
        "Un vautour.",
        "Un loup.",
    ]},
    {"title": "d10 Le commandant de la troupe de mercenaires est...", "id":"d10themercenarytroopscommanderis", "roll":[
        "Un hors-la-loi téméraire.",
        "Un démagogue charismatique.",
        "Un étranger mystérieux.",
        "Un paria issu d’une famille noble.",
        "Un tueur impitoyable.",
        "Un bretteur flamboyant.",
        "Une brute épaisse.",
        "Un héros de guerre célébré.",
        "Un chevalier déchu.",
        "Un ancien champion d’arène.",
    ]},
    {"title": "d6 L’attitude de la troupe envers son commandant est...", "id":"d6themercenarytroopsattitudetowardtheircommanderis", "roll":[
        "Amicale et loyale.",
        "Respectueuse et professionnelle.",
        "Prudente et incertaine.",
        "Terrifiée et muette.",
        "Déçue et impolie.",
        "En colère et rebelle.",
    ]},
    {"title": "d6 La troupe de mercenaires est actuellement...", "id":"d6themercenarytroopiscurrently", "roll":[
        "Employée comme gardes.",
        "Employée dans une guerre.",
        "Sous contrat avec des criminels.",
        "Sous contrat avec des marchands.",
        "Sous contrat avec des nobles.",
        "En recherche de travail.",
    ]},
    {"title": "d10 La troupe de mercenaires est spécialisée en...", "id":"d10themercenarytroopspecializesin", "roll":[
        "Rupture de siège.",
        "Défense de fortifications.",
        "Assauts frontaux.",
        "Infiltration.",
        "Escarmouches.",
        "Tactiques d’embuscade.",
        "Patrouille.",
        "Manœuvres de contournement.",
        "Guérilla.",
        "Razzia et pillage.",
    ]},
    {"title": "d8 La troupe de mercenaires est réputée pour...", "id":"d8themercenarytroopisnotoriousfor", "roll":[
        "Ne faire aucun prisonnier.",
        "Laisser les cadavres aux bêtes.",
        "Tatouer ou marquer les prisonniers.",
        "Scalper ou écorcher les prisonniers.",
        "Brûler les villages et les champs.",
        "Trahir leurs employeurs.",
        "Chanter des chansons paillardes.",
        "Boire trop de bière et de vin.",
    ]},
{"title": "d8 La troupe de mercenaires se bat avec...", "id":"d8themercenarytroopfightswith", "roll":[
"Des tactiques de harcèlement.",
"Une attaque frontale directe.",
"Des mouvements élégants.",
"Des charges imprévisibles.",
"Des manœuvres de combat maîtrisées.",
"Aucune pitié.",
"Beaucoup de railleries et moqueries.",
"Des tactiques vicieuses."
]},
{"title": "d8 De nombreux mercenaires de la troupe portent...", "id":"d8manyofthemercenariesinthetrooparearmoredin", "roll":[
"Des robes exotiques.",
"Une armure de cuir.",
"Une armure de cuir cloutée.",
"Une armure en peau.",
"Une cotte d’anneaux.",
"Une cotte de mailles.",
"Une armure d’écailles.",
"Une armure de plates."
]},
{"title": "d12 De nombreux mercenaires de la troupe sont armés de...", "id":"d12manyofthemercenariesinthetrooparewielding", "roll":[
"Épées longues.",
"Épées longues et boucliers.",
"Épées courtes et lances.",
"Épées courtes et boucliers.",
"Épées longues et arbalètes.",
"Épées à deux mains.",
"Lances et boucliers.",
"Haches de guerre.",
"Haches de guerre et boucliers.",
"Marteaux de guerre.",
"Scimitars.",
"Scimitars et boucliers."
]},
{"title": "d8 La guilde est dirigée par...", "id":"d8theguildiscontrolledby", "roll":[
"Un caïd pragmatique qui déteste la bureaucratie.",
"Un petit gnome à la mine pincée obsédé par l'argent.",
"Un jeune noble inexpérimenté au besoin capricieux d’une bourse bien remplie.",
"Un conseil composé des chefs des guildes d'artisanat locales.",
"Une démocratie houleuse de tous les marchands de la ville.",
"Une charte ancienne appliquée par la milice locale.",
"Le marchand le plus riche de la ville.",
"Un moine nommé par la ville, ayant renoncé aux richesses."
]},
{"title": "d8 Les affaires illicites de cette guilde comprennent...", "id":"d8thisguildsillicitaffairscomprise", "roll":[
"Absolument rien, ce sont des parangons de moralité.",
"Quelques erreurs fiscales involontaires, bien sûr.",
"Des faveurs politiques subtiles et bien négociées.",
"Des prix fixés à l'avantage des dirigeants.",
"Des pots-de-vin réguliers pour ignorer certains délits mineurs.",
"Des pots-de-vin en haut lieu, quelques escroqueries et la réprobation des prêtres.",
"Une corruption endémique, des accords avec des voleurs et parfois des assassins.",
"Des pactes démoniaques, de la contrefaçon à grande échelle et des activités de trahison."
]},
{"title": "d8 Le statut et le contrôle de cette guilde sont...", "id":"d8thisguildsstatusandcontrolis", "roll":[
"Faibles ; autrefois grande, la guilde lutte à présent.",
"Tout juste fondée et en recrutement actif.",
"En forte croissance après un coup de chance.",
"En déclin, concurrencée par un rival émergent.",
"Absolus, elle domine totalement son domaine.",
"Irréguliers, variant selon les marchés.",
"Indiscutés, elle domine toutes les autres guildes locales.",
"Contestés, son autorité est minée de l’intérieur."
]},
{"title": "d8 Quête mineure : La guilde a des problèmes avec...", "id":"d8minorquesttheguildhasbeenhavingsometroublewith", "roll":[
"Un marchand récemment menacé par un vaurien.",
"Ses coffres d’or... un don de 500 pièces d’or serait apprécié.",
"Le transport d’un objet magique vers une succursale.",
"Une caravane réticente à emprunter un nouveau chemin.",
"Un membre de la milice trop curieux.",
"Une guilde d'artisan sceptique face au programme de fidélité.",
"Une infestation de rats.",
"Une infestation de rats (qui est en fait une faille vers le Plan des Rats)."
]},
{"title": "d8 Quête standard : La guilde a besoin de vous pour gérer...", "id":"d8standardquesttheguildneedsyoutohandle", "roll":[
"Une caravane disparue dans une région proche.",
"Une guilde de voleurs récalcitrante.",
"Un officiel anti-capitaliste.",
"Une guilde marchande concurrente en plein essor.",
"Un blocus commercial à résoudre.",
"Des rumeurs d’aberrations nocturnes effrayant les clients.",
"Un membre du conseil devenu voleur de fonds.",
"Une invasion de rats (la faille est maintenant un portail permanent)."
]},
{"title": "d8 Quête majeure : Une affaire critique, la guilde est confrontée à...", "id":"d8majorquestamatterofgreatimporttheguildisfacedwith", "roll":[
"Une armée de mercenaires assiégeant la ville !",
"Une corruption interne : moitié du conseil = flagelleurs mentaux.",
"Une ferveur religieuse poussant le peuple à rejeter la richesse.",
"Un roi-momie tenant en otage une caravane pleine d’investissements.",
"Une révolution menaçant les coffres de la guilde. Ne blessez aucun civil.",
"Une enquête du maître espion royal sur les activités de la guilde.",
"Un être planaire a remplacé le maître de guilde.",
"Un déluge de rats : un avatar du dieu des rats s'est installé dans la cave."
]},
{"title": "d6 La spécialité ou mission principale de cette compagnie commerciale est...", "id":"d6thistradingcompanysspecificspecialtyorpurposeis", "roll":[
"Le commerce maritime à longue distance, l’exploration et le transport.",
"Le commerce aérien à longue distance ; grâce à des dirigeables, messagers aarakocra, voire parfois un roc ou un dragon.",
"La chasse et le piégeage de monstres et animaux exotiques.",
"Servir de façade à un royaume local manipulant le commerce mondial.",
"La sécurisation et l’organisation de caravanes longues distances, ainsi que la lente construction de routes (et peut-être même de voies ferrées).",
"L’exploration et l’exploitation de terres ou de plans nouvellement découverts."
]},
{"title": "d8 Cette compagnie commerciale est dirigée par...", "id":"d8thistradingcompanyiscontrolledby", "roll":[
"Un être planaire déguisé en riche marchand (voir jet des activités illicites pour l’origine : bas = céleste, moyen = neutre, haut = infernal).",
"Un conseil commun de Maîtres de la Monnaie issus de tous les royaumes civilisés.",
"Un gobelin savant devenu immortel grâce à une bénédiction divine.",
"Un ancien aventurier aguerri.",
"Un conseil d’investisseurs.",
"Une démocratie turbulente réunissant tous les marchands de la compagnie.",
"Un maître caravanier immensément riche ayant découvert une cité d’or perdue.",
"Un grand et grotesque maître esclavagiste."
]},
{"title": "d4 Le commerçant est...", "id":"d4theshopkeeperis", "roll":[
"Las.",
"Enthousiaste à aider.",
"Visiblement agacé.",
"Très nerveux."
]},
{"title": "d4 Le commerçant cherche quelqu’un pour...", "id":"d4theshopkeeperseekssomeoneto", "roll":[
"Acheter des marchandises défectueuses.",
"Acquérir un grand stock de biens.",
"Écouter ses jérémiades.",
"Partager un verre de vin et discuter."
]},
{"title": "d6 Le marchand est...", "id":"d6themerchantis", "roll":[
"Membre d’un clan de commerçants.",
"Un petit seigneur ou dame.",
"Un commerçant ambitieux.",
"Membre d’une famille influente.",
"De naissance modeste.",
"Le représentant d’un marchand plus puissant."
]},
{"title": "d4 Le marchand porte...", "id":"d4themerchantwears", "roll":[
"Un sourire désagréable.",
"Un rictus arrogant.",
"Beaucoup trop de parfum.",
"Une chemise ample dissimulant un ventre rond."
]},
{"title": "d4 Le marchand cherche quelqu’un pour...", "id":"d4themerchantseekssomeoneto", "roll":[
"Mettre la main sur un artefact mystérieux.",
"Négocier un contrat commercial.",
"Saboter un marchand rival.",
"Passer un bon moment avec lui."
]},
{"title": "d6 Le marchand transporte...", "id":"d6themerchantcarries", "roll":[
"Un héritage familial.",
"Plusieurs inventaires et factures.",
"Des joyaux de grande valeur.",
"Une lettre d’amour compromettante.",
"Un petit couteau.",
"Une fiole de potion de soin, au cas où."
]},
{"title": "d6 Devise : en plus des pièces, le marchand accepte aussi...", "id":"d6currencybesidescointhemerchantwilltradein", "roll":[
"Des gemmes et bijoux.",
"Des lingots d’or et d’argent.",
"De l’eau, des provisions et autres biens.",
"Des coquillages, perles et breloques.",
"Des faveurs.",
"Des informations scandaleuses."
]},
{"title": "d20 Les couleurs de la compagnie sont...", "id":"d20thecompanyscolorsare", "roll":[
"Noir.",
"Rouge / écarlate.",
"Or.",
"Vert forêt.",
"Bleu royal.",
"Violet.",
"Argent / gris clair.",
"Bronze.",
"Beige / kaki.",
"Marron / castor.",
"Gris foncé / canon.",
"Blanc.",
"Bordeaux.",
"Bleu ciel.",
"Bleu marine.",
"Marron foncé / chocolat.",
"Sarcelle / turquoise.",
"Jaune.",
"Orange.",
"Vert olive."
]},
{"title": "d20 L’emblème de la compagnie représente...", "id":"d20thecompanysbannerfeatures", "roll":[
"Un crâne.",
"Un poing fermé.",
"Une flamme.",
"Un bouclier.",
"Une flèche.",
"Une hache.",
"Un marteau.",
"Une épée.",
"Le soleil.",
"La lune.",
"Un ours.",
"Un taureau.",
"Un dragon.",
"Un faucon.",
"Un lion.",
"Un corbeau.",
"Un scorpion.",
"Un serpent.",
"Un cerf.",
"Un loup."
]},
{"title": "d10 Le commandant de la compagnie est...", "id":"d10thecompanyscommanderis", "roll":[
"Un stratège brillant.",
"Un héritier d’une grande famille.",
"Un paria issu d’une grande famille.",
"Un fringant bretteur.",
"Un brute épaisse.",
"Un héros de guerre célébré.",
"Un chevalier déchu.",
"Un chevalier sacré.",
"Un soldat de carrière.",
"Un ancien champion d’arène."
]},
{"title": "d6 L’attitude de la compagnie envers son commandant est...", "id":"d6thecompanysattitudetowardtheircommanderis", "roll":[
"Amicale et loyale.",
"Respectueuse et professionnelle.",
"Prudente et incertaine.",
"Terrifiée et silencieuse.",
"Déçue et irrespectueuse.",
"Agitée et nerveuse."
]},
{"title": "d8 La spécialité de la compagnie est...", "id":"d8thecompanyspecializesin", "roll":[
"Briser les sièges.",
"Défendre les fortins.",
"Les assauts frontaux.",
"Les escarmouches.",
"Les patrouilles.",
"Les manœuvres de contournement.",
"La guérilla.",
"La collecte de vivres."
]},
{"title": "d8 La compagnie est tristement célèbre pour...", "id":"d8thecompanyisnotoriousfor", "roll":[
"Ne faire aucun prisonnier.",
"Marquer ou mutiler les prisonniers.",
"L’incompétence.",
"La lâcheté.",
"Chanter des chansons grivoises.",
"Ses aventures amoureuses.",
"Manger tout ce qui est disponible.",
"Boire trop de bière et de vin."
]},
{"title": "d6 La plupart des soldats de la compagnie sont équipés de...", "id":"d6mostsoldiersinthecompanyareoutfittedwith", "roll":[
"Armure de cuir rapiécée.",
"Armure de cuir marquée du symbole de leur seigneur.",
"Casques et cuirasses portant le symbole de leur seigneur.",
"Cotte de mailles bien entretenue.",
"Armure d’écailles usée.",
"Armure d’écailles toute neuve."
]},
{"title": "d12 La plupart des soldats de la compagnie sont armés de...", "id":"d12mostsoldiersinthecompanyareequippedwith", "roll":[
"Épées longues et arcs courts.",
"Épées longues et arbalètes.",
"Épées longues et boucliers.",
"Épées courtes et arcs longs.",
"Épées courtes et boucliers.",
"Étoiles du matin et arbalètes.",
"Haches de bataille et haches à main.",
"Marteaux de guerre et boucliers.",
"Lances et boucliers.",
"Lances longues et épées courtes.",
"Piques et épées courtes.",
"Hallebardes et haches à main."
]},
{"title": "d8 La plupart des soldats de la compagnie sont...", "id":"d8mostsoldiersinthecompanyare", "roll":[
"Des hommes d’armes entraînés.",
"Des miliciens.",
"Des vétérans de guerre.",
"Des prisonniers de guerre.",
"Des conscrits urbains.",
"Des conscrits villageois.",
"Des criminels condamnés.",
"De jeunes recrues inexpérimentées."
]},
{"title": "d12 Le soldat est...", "id":"d12thesoldieris", "roll":[
"Un garçon de ferme.",
"Le fils d’un mineur ou pêcheur.",
"Un vétéran des arènes.",
"Un vétéran de guerre.",
"Un prisonnier de guerre.",
"Un dissident politique.",
"Le fils d’un homme pauvre.",
"Un ivrogne.",
"Un criminel en fuite.",
"Un ancien pirate.",
"Un artisan raté.",
"Un chouchou des dames."
]},
{"title": "d12 Le soldat se bat pour...", "id":"d12thesoldierfightsfor", "roll":[
"Un salaire stable.",
"L’amour de quelqu’un qu’il ne peut avoir.",
"Le goût du sang.",
"La joie du tourment sadique.",
"Une vengeance personnelle.",
"De l’or pour rembourser des dettes.",
"Aider un membre de sa famille.",
"Éviter la prison à vie.",
"Une chance de rédemption.",
"Dieu et patrie.",
"La fortune et la gloire.",
"La force et l’honneur."
]},
{"title": "d12 Sur le visage du soldat, on voit...", "id":"d12onthesoldiersfaceis", "roll":[
"Une grosse verrue.",
"Un cache-œil.",
"Une vilaine cicatrice.",
"Un rictus hautain.",
"Un air de tristesse.",
"Un sourire niais.",
"Un sourire impatient.",
"Une cascade de cheveux magnifiques.",
"Des favoris féroces.",
"Un bouc bien taillé.",
"Une barbe en désordre.",
"Une moustache fournie."
]},
{"title": "d10 Le soldat porte...", "id":"d10thesoldiercarries", "roll":[
"Une lame ornée de franges en cuir souple.",
"Une lame avec un pommeau sculpté (d6) : 1. ivoire ; 2. jade ; 3. stéatite ; 4. ébène ; 5. acajou ; 6. chêne.",
"Une lame dont la garde est décorée de bêtes (d6) : 1. dragons ; 2. lions ; 3. scorpions ; 4. serpents ; 5. araignées ; 6. loups.",
"Une lame en acier noirci.",
"Une lame soigneusement polie.",
"Un talisman offert par un(e) amoureux(se).",
"Un souvenir offert par un parent.",
"Une lettre d’un camarade tombé au combat.",
"Un trophée prélevé sur un ennemi.",
"Un ruban provenant d’une jeune fille lointaine."
]},
{"title": "d6 La maison est...", "id":"d6thehouseis", "roll":[
"Ancienne et respectée par toutes les maisons, grandes et petites.",
"Ancienne et grandement déchue par rapport à ce qu’elle fut autrefois.",
"Vieille et respectée par de nombreuses maisons.",
"Vieille et peinant à conserver le respect des autres maisons.",
"Vieille mais souvent éclipsée par d’autres maisons.",
"Récemment élevée à la noblesse."
]},
{"title": "d20 Les couleurs de la maison sont...", "id":"d20thehousescolorsare", "roll":[
"Noir.",
"Rouge / écarlate.",
"Or.",
"Vert forêt.",
"Bleu royal.",
"Violet.",
"Argent / gris clair.",
"Bronze.",
"Beige / kaki.",
"Marron / castor.",
"Gris foncé / canon de fusil.",
"Blanc.",
"Bordeaux.",
"Bleu ciel.",
"Bleu marine.",
"Brun foncé / chocolat.",
"Sarcelle / turquoise.",
"Jaune.",
"Orange.",
"Vert olive."
]},
{"title": "d8 Le symbole de la maison est...", "id":"d8thehousessymbolis", "roll":[
"Une arme (d8) : 1. flèche ; 2. hache ; 3. dague ; 4. marteau ; 5. masse ; 6. lance ; 7. bâton ; 8. épée.",
"Une pièce d’armure (d4) : 1. cuirasse ; 2. gantelet ; 3. casque ; 4. bouclier.",
"Un astre (d4) : 1. soleil ; 2. lune ; 3. étoile ; 4. comète.",
"Une plante ou une partie de plante (d12) : 1. pomme ; 2. orge ; 3. ronce ; 4. figue ; 5. raisin ; 6. lys ; 7. érable ; 8. chêne ; 9. olive ; 10. pin ; 11. rose ; 12. blé.",
"Une créature aquatique (d6) : 1. crabe ; 2. crocodile ; 3. grenouille ; 4. poisson ; 5. pieuvre ; 6. baleine.",
"Une petite bête (d12) : 1. blaireau ; 2. chauve-souris ; 3. castor ; 4. chien ; 5. furet ; 6. renard ; 7. hérisson ; 8. lézard ; 9. rat ; 10. scorpion ; 11. serpent ; 12. araignée.",
"Une grande bête (d8) : 1. ours ; 2. sanglier ; 3. taureau ; 4. dragon ; 5. lion ; 6. bœuf ; 7. cerf ; 8. loup.",
"Un oiseau (d12) : 1. cardinal ; 2. colombe ; 3. aigle ; 4. faucon ; 5. moqueur ; 6. hibou ; 7. pélican ; 8. corbeau ; 9. coq ; 10. moineau ; 11. cygne ; 12. vautour."
]},
{"title": "d20 La devise de la maison défend les idéaux de...", "id":"d20thehousesmottochampionstheidealsof", "roll":[
"La compassion.",
"Le courage.",
"La courtoisie.",
"La détermination.",
"La discipline.",
"Le devoir.",
"L’excellence.",
"La foi.",
"La générosité.",
"L’honneur.",
"L’espérance.",
"L’intégrité.",
"La justice.",
"La loyauté.",
"La miséricorde.",
"La patience.",
"La droiture.",
"La force.",
"La confiance.",
"La sagesse."
]},
{"title": "d12 Le membre le plus célèbre de la maison est ou était...", "id":"d12thebestknownmemberofthehouseisorwas", "roll":[
"Un chevalier galant.",
"Une femme d’une grande beauté.",
"Un négociateur impitoyable.",
"Un diplomate habile.",
"Un célèbre explorateur ou voyageur.",
"Un brillant stratège militaire.",
"Un rebelle ou hors-la-loi notoire.",
"Un bretteur séduisant.",
"Un guerrier redoutable.",
"Un érudit de génie.",
"Un orateur hors pair.",
"Un souverain dangereux et fou."
]},
{"title": "d10 L’actuel chef de la maison est...", "id":"d10thecurrentheadofthehouseis", "roll":[
"Un vieil homme ou une vieille femme bienveillant(e).",
"Un(e) vieillard(e) impitoyable.",
"Un(e) vieillard(e) rusé(e).",
"Un homme ou une femme charmant(e).",
"Un vétéran des guerres.",
"Un politicien avisé.",
"Un fidèle religieux.",
"Un(e) veuf(ve) au cœur brisé.",
"Un(e) jeune impulsif(ve).",
"Un enfant."
]},
{"title": "d8 Les objectifs de la maison incluent (les membres peuvent avoir des objectifs différents)...", "id":"d8thehousesgoalsincludeindividualmembersmayhavedifferentgoals", "roll":[
"La domination politique de la ville ou région.",
"La domination commerciale de la ville ou région.",
"La vengeance sur une maison rivale locale.",
"La vengeance sur une maison rivale étrangère.",
"Le sabotage d’un groupe populaire : guilde, académie, foi ou société secrète.",
"Provoquer une rébellion contre la maison régnante.",
"Un mariage avec une maison alliée puissante.",
"Un mariage avec une maison rivale puissante."
]},
{"title": "d8 Un ou plusieurs membres de la maison cachent (le secret peut être ancien ou récent)...", "id":"d8oneormorehousememberskeepsecretthesecretmayinvolvepastorpresentevents", "roll":[
"Une romance scandaleuse de longue date.",
"L’existence d’un enfant illégitime.",
"Un meurtre dans l’un des châteaux ou domaines familiaux.",
"Un fanatisme religieux extrême.",
"La naissance d’un être difforme.",
"Une trahison envers le souverain.",
"La sénilité ou folie de certains membres.",
"Le sabotage criminel d’une maison rivale."
]},
{"title": "d10 Le siège de la maison est situé dans ou près de...", "id":"d10thehousesseatofpowerislocatedinornear", "roll":[
"Une ville portuaire.",
"Une chaîne de hautes montagnes.",
"Une vaste plaine fertile.",
"Une vallée fluviale prospère.",
"Une forêt ancienne.",
"Une côte déchiquetée.",
"Un marais détrempé.",
"Un lac cristallin.",
"Un plateau désertique.",
"Un paysage vallonné idyllique."
]},
{"title": "d6 Le noble est...", "id":"d6thenobleis", "roll":[
"Un chevalier.",
"Un vieux seigneur.",
"Un jeune seigneur.",
"Une vieille dame.",
"Une jeune dame.",
"Un riche marchand."
]},
{"title": "d8 Le noble cherche quelqu’un pour...", "id":"d8thenobleseekssomeoneto", "roll":[
"Éliminer un ennemi.",
"Négocier un contrat commercial.",
"Livrer une lettre.",
"Préparer une armée pour la guerre.",
"Saboter un rival.",
"Conclure un mariage avantageux pour lui/elle-même.",
"Conclure un mariage avantageux pour un proche.",
"Passer du bon temps."
]},
{"title": "d6 Le noble porte...", "id":"d6thenoblecarries", "roll":[
"Plusieurs titres de propriété.",
"Un héritage familial.",
"Des factures et inventaires.",
"Des bijoux très précieux.",
"Une lettre d’amour compromettante.",
"Une lettre d’un puissant seigneur ou dame."
]},
{"title": "d8 Le noble porte...", "id":"d8thenoblewears", "roll":[
"Un collier ou une chaîne en or voyante.",
"Des bottes en cuir brillantes.",
"Une bague chevalière ornée.",
"Des vêtements en soie fine.",
"Un sourire ravageur.",
"Un rictus extrêmement laid.",
"Un sourire arrogant.",
"Des cheveux et/ou une barbe soigneusement coiffés."
]},
{"title": "d8 Le noble a...", "id":"d8thenoblehas", "roll":[
"Un rire fort et profond.",
"Un rire aigu.",
"Un rire nerveux et saccadé.",
"Une manie de se tortiller.",
"Une langue d’argent.",
"Une présence imposante.",
"Un mépris total pour les roturiers.",
"Pas le moindre souci en tête."
]},
{"title": "d10 L’activité principale du groupe de hors-la-loi est...", "id":"d10theoutlawbandsprimarybusinessinvolves", "roll":[
"Le braconnage sur les terres d’un seigneur ou du souverain.",
"L’accueil de fugitifs.",
"Le harcèlement des nobles et officiels sur les routes.",
"Le pillage de caravanes transportant des biens de valeur.",
"Le braquage de navires ou charrettes.",
"Le trafic de drogues (d4) : 1. feuille-fumée ; 2. champignons hallucinogènes ; 3. sel-sommeil ; 4. sucre-tranchant.",
"Le trafic d’antiquités rares.",
"Le recel de biens volés.",
"Le trafic de créatures vivantes (d4) : 1. bêtes exotiques ; 2. courtisanes étrangères ; 3. fugitifs ; 4. esclaves.",
"Servir de gros bras pour des marchands ou tenanciers de bordels louches."
]},
{"title": "d10 Les couleurs du groupe de hors-la-loi sont...", "id":"d10theoutlawbandscolorsare", "roll":[
"Noir.",
"Or.",
"Vert forêt.",
"Bronze.",
"Beige / kaki.",
"Marron / castor.",
"Gris foncé / acier.",
"Bordeaux.",
"Brun foncé / chocolat.",
"Vert olive."
]},
{"title": "d12 Le symbole du groupe de hors-la-loi est...", "id":"d12theoutlawbandssymbolis", "roll":[
"Un crâne.",
"Une flèche.",
"Une dague.",
"Un gobelet.",
"La lune.",
"Une étoile.",
"Un serpent.",
"Un blaireau.",
"Une araignée.",
"Un rat.",
"Un loup.",
"Un ours."
]},
{"title": "d12 Le chef du groupe de hors-la-loi est...", "id":"d12theoutlawbandsleaderis", "roll":[
"Un dangereux mégalomane.",
"Un démagogue charismatique.",
"Un étranger mystérieux.",
"Un voleur talentueux.",
"Un membre d’une famille noble.",
"Un tueur impitoyable.",
"Une femme fatale.",
"Un voyou séduisant.",
"Un bretteur élégant.",
"Un brute épaisse.",
"Un prêtre dévoué.",
"Un fugitif bien connu."
]},
{"title": "d6 Les membres du groupe sont principalement...", "id":"d6theoutlawbandsmembersareprimarily", "roll":[
"Des artisans sans travail.",
"Des paysans déplacés.",
"Des paysans désespérés.",
"Des esclaves évadés.",
"Des vétérans de guerre.",
"Des réfugiés étrangers."
]},
{"title": "d8 Les objectifs du groupe de hors-la-loi incluent (les leaders et les membres peuvent différer)...", "id":"d8theoutlawbandsgoalsincludeleadershipandrankandfilememberscouldhavedifferentgoals", "roll":[
"La domination du commerce régional.",
"Le sabotage du commerce régional.",
"La vengeance contre une bande rivale.",
"La vengeance contre l’élite régionale.",
"La rébellion contre les puissants.",
"L’égalité et la liberté pour tous.",
"Une retraite riche et paisible.",
"La violence pour assouvir leur soif de sang."
]},
{"title": "d10 Les membres sont généralement armés de...", "id":"d10membersoftheoutlawbandtypicallyarmthemselveswith", "roll":[
"Masses de bois.",
"Dagues surdimensionnées.",
"Arcs courts et flèches.",
"Arcs longs et flèches.",
"Dagues et arbalètes.",
"Haches et couteaux.",
"Bâtons et pierres.",
"Épées courtes.",
"Poings américains.",
"Dagues et frondes."
]},
{"title": "d10 Le repaire du groupe est caché dans ou près de...", "id":"d10theoutlawbandsheadquartersishiddeninornear", "roll":[
"La demeure d’un noble influent.",
"La place du marché du village.",
"Une auberge de route.",
"Une taverne.",
"Un bordel.",
"Un vieux phare.",
"Une cabane abandonnée.",
"Une cascade.",
"Une grotte.",
"Une forêt dense."
]},
{"title": "d10 Le groupe est craint ou respecté par...", "id":"d10theoutlawbandisfearedorrespectedby", "roll":[
"Les ambassadeurs et percepteurs.",
"Les marchands et colporteurs.",
"Les politiciens et magistrats.",
"Les gardes et shérifs.",
"Les soldats et guerriers.",
"Les nobles et voyageurs riches.",
"Les chevaliers et loyalistes.",
"Les paysans et fermiers.",
"Les prêtres et sages.",
"Les femmes et les enfants."
]},
{"title": "d12 Trait distinctif d’un membre : Le hors-la-loi a...", "id":"d12distinguishingfeatureforanindividualtheoutlawhas", "roll":[
"Une boucle d’oreille voyante.",
"Des bottes en cuir brillantes.",
"Un trou dans la pointe d’une botte.",
"Une dague dans chaque botte.",
"Un masque sur le visage.",
"Un chapeau à large bord.",
"Un tatouage de dragon sur l’avant-bras.",
"Un tatouage de flammes autour du bras.",
"Un rire dément.",
"Un nez cassé et tordu.",
"Une chemise ouverte révélant une poitrine velue.",
"De longues et extravagantes moustaches."
]},
{"title": "d8. Les proies préférées des braconniers incluent...", "id":"d8thepoachersfavoritepreyincludes", "roll":[
"Des ours.",
"Oiseaux de proie (d4) : 1. aigles ; 2. faucons ; 3. buses ; 4. hiboux.",
"Des sangliers.",
"Cervidés (d4) : 1. élans ; 2. cerfs ; 3. orignaux ; 4. daims.",
"Bêtes exotiques (d8) : 1. béhémoths ; 2. éléphants ; 3. griffons ; 4. hippogriffes ; 5. lions ; 6. ours-hiboux ; 7. tigres ; 8. vouivres.",
"Gibier à plumes (d6) : 1. colombes ; 2. gélinottes ; 3. perdrix ; 4. faisans ; 5. cailles ; 6. dindes.",
"Oiseaux aquatiques (d6) : 1. canards ; 2. oies ; 3. hérons ; 4. macareux ; 5. bécassines ; 6. cygnes.",
"Petites bêtes à fourrure (d6) : 1. castors ; 2. hermines ; 3. loutres ; 4. ratons laveurs ; 5. zibelines ; 6. moufettes.",
"Petits prédateurs (d4) : 1. blaireaux ; 2. coyotes ; 3. renards ; 4. gloutons.",
"Des loups."
]},
{"title": "d6. Les braconniers chassent...", "id":"d6thepoachershunt", "roll":[
"Pour le sport.",
"Pour nourrir leur famille.",
"Pour nourrir les paysans pauvres.",
"Par vengeance envers le propriétaire des terres.",
"Pour vendre la viande.",
"Pour vendre les peaux."
]},
{"title": "d6 Les voleurs frappent généralement avec...", "id":"d6therobberstypicallystrikewith", "roll":[
"Des attaques en meute.",
"Des attaques éclair.",
"Des embuscades.",
"Des manœuvres chorégraphiées.",
"Des tactiques imprévisibles.",
"Beaucoup de pas dansants."
]},
{"title": "d8 Les voleurs sont notoires pour...", "id":"d8therobbersarenotoriousfor", "roll":[
"Ne jamais laisser de survivants.",
"Marquer leurs prisonniers.",
"Scalper leurs captifs.",
"Brûler des chariots et navires.",
"Utiliser des explosifs.",
"Leurs aventures amoureuses.",
"Chanter des chansons grivoises.",
"Boire trop de bière."
]},
{"title": "d6 Le mode opératoire principal du réseau de contrebande implique...", "id":"d6thesmugglingringsprimarymodusoperandiinvolves", "roll":[
"Des tunnels souterrains.",
"Des compartiments secrets.",
"Des embarcations furtives.",
"Des mules humanoïdes.",
"La corruption des officiels.",
"Un réseau de planques."
]},
{"title": "d8 Le réseau est soutenu par...", "id":"d8theringissupportedby", "roll":[
"Un marchand influent.",
"Un ministre ou magistrat important.",
"Un grand chef criminel.",
"Un capitaine pirate.",
"Un amiral.",
"Un groupe de subversifs.",
"Le capitaine de la garde ou un shérif local.",
"Le principal rival du souverain."
]},
{"title": "d10 Le navire des pirates est...", "id":"d10thepiratesshipis", "roll":[
"Guère plus qu’un radeau.",
"Une galère.",
"Un drakkar.",
"Un catamaran.",
"Un cogge.",
"Un hulk.",
"Une caraque.",
"Une caravelle.",
"Une goélette.",
"Un cuirassé."
]},
{"title": "d8 Actuellement, le navire des pirates est...", "id":"d8presentlythepiratesshipis", "roll":[
"Chargé de trésors.",
"Rempli de marchandises volées.",
"Bien approvisionné.",
"En parfait état.",
"\“Emprunté\” à d’autres pirates.",
"En réparation.",
"À peine à flot.",
"Reposant sous les flots."
]},
{"title": "d20 Le pavillon du navire arbore...", "id":"d20theshipsbannerfeatures", "roll":[
"Un crâne.",
"Deux os croisés.",
"Un crâne avec os croisés.",
"Une main squelettique.",
"Un poisson squelettique.",
"Un crâne enflammé.",
"Un poing fermé.",
"Un fantôme.",
"Une sirène.",
"Deux coutelas croisés.",
"Une dague.",
"Une dague ensanglantée.",
"Un albatros.",
"Un pélican.",
"Une baleine.",
"Une pieuvre.",
"Un espadon.",
"Un crabe.",
"Une tortue de mer.",
"Un gros thon."
]},
{"title": "d20 La mascotte du navire est...", "id":"d20theshipsmascotis", "roll":[
"Un perroquet",
"Un perroquet",
"Un perroquet",
"Un perroquet",
"Une perruche (qui dit souvent « Sales fripouilles ! » ou « Aye, capitaine ! »).",
"Un cacatoès (qui dit souvent « Pièces d’or ! » ou « C’est la semaine des requins ! »).",
"Un conure (qui dit souvent « Les morts ne parlent pas ! » ou « Terre en vue ! »).",
"Un ara (qui dit souvent « Montre-moi le butin ! » ou « Terre ho ! »).",
"Un singe",
"Un singe",
"Un singe",
"Un singe",
"Un capucin (avec ou sans cache-œil).",
"Un macaque (avec ou sans gilet).",
"Un singe-araignée (avec ou sans bandana).",
"Un tamarin (avec ou sans moustaches).",
"Une vieille tortue.",
"Un chat de mer paresseux.",
"Un cochon ventru.",
"Un chien de berger hyperactif."
]},
{"title": "d10 Le capitaine du navire est...", "id":"d10theshipscaptainis", "roll":[
"Un dangereux mégalomane.",
"Un démagogue charismatique.",
"Un étranger mystérieux.",
"Un voleur talentueux.",
"Un membre d’une famille influente.",
"Un tueur impitoyable.",
"Une femme fatale.",
"Un voyou séduisant.",
"Un bretteur flamboyant.",
"Un brute épaisse.",
"Un vieux loup de mer.",
"Un héros naval célébré."
]},
{"title": "d8 L’attitude de l’équipage envers son capitaine est...", "id":"d8thecrewsattitudetowardtheircaptainis", "roll":[
"Adoratrice et loyale.",
"Amicale et satisfaite.",
"Respectueuse et professionnelle.",
"Mercenaire et motivée.",
"Terrifiée et muette.",
"Déçue et indifférente.",
"Agitée et rebelle.",
"En colère et prête à se mutiner."
]},
{"title": "d10 Les membres d’équipage portent souvent les mêmes...", "id":"d10crewmembersoftensportmatching", "roll":[
"Chemises bouffantes.",
"Culottes.",
"Écharpes.",
"Gilets.",
"Bandanas.",
"Bottes.",
"Tatouages.",
"Chapeaux.",
"Cicatrices.",
"Moustaches."
]},
{"title": "d8 Les objectifs de l’équipage incluent (le capitaine et l’équipage peuvent avoir des buts différents)...", "id":"d8thecrewsgoalsincludecaptainandcrewmemberscouldhavedifferentgoals", "roll":[
"La découverte d’un trésor légendaire caché.",
"La domination du commerce maritime de la région.",
"La vengeance contre un héros naval.",
"La vengeance contre un équipage pirate rival.",
"La rébellion contre les marchands dominants.",
"Une retraite paisible et riche.",
"La violence pour étancher leur soif de sang.",
"Boire tout le rhum."
]},
{"title": "d10 Les membres d’équipage s’arment généralement avec...", "id":"d10crewmemberstypicallyarmthemselveswith", "roll":[
"Des cabillots (gourdin en bois).",
"Des couteaux de lancer.",
"Des dagues surdimensionnées.",
"Des dagues dentelées.",
"Des coutelas.",
"Des gourdins et des dagues.",
"Des poings américains.",
"Leurs poings nus.",
"Des filets et des tridents.",
"Des harpons."
]},
{"title": "d10 L’équipage pirate combat généralement avec...", "id":"d10thepiratecrewtypicallyfightswith", "roll":[
"Des tactiques de groupe.",
"Des attaques éclair.",
"Des embuscades.",
"Des manœuvres chorégraphiées.",
"Des manœuvres imprévisibles.",
"Beaucoup de sourires et de plaisanteries.",
"Beaucoup de pas de danse.",
"Beaucoup de cris et de hurlements.",
"Des coups de pied et des piétinements.",
"Beaucoup de coups de tête."
]},
{"title": "d10 Le repaire de l’équipage est caché dans ou près de...", "id":"d10thecrewsheadquartersishiddeninornear", "roll":[
"Une falaise côtière accidentée.",
"Une lagune cachée.",
"Une île isolée.",
"L’embouchure d’une rivière marécageuse.",
"Une grotte côtière.",
"Une taverne.",
"Un bordel.",
"Un entrepôt ou un chantier naval.",
"Un village de pêcheurs pauvre.",
"Un vieux phare."
]},
{"title": "d12 L’équipage est tristement célèbre pour...", "id":"d12thecrewisnotoriousfor", "roll":[
"Ne jamais laisser de survivants.",
"Donner leurs captifs en pâture aux requins.",
"Tatouer ou marquer au fer rouge les captifs.",
"Scalper les captifs.",
"Écorcher les captifs.",
"Brûler les villages côtiers.",
"Piller les navires d’un tyran fortuné.",
"Utiliser beaucoup d’explosifs.",
"Communiquer avec les fantômes.",
"Leurs aventures amoureuses.",
"Chanter des chansons grivoises.",
"Boire trop de rhum."
]},
{"title": "d12 Tatouage : Le pirate a...", "id":"d12tattoothepiratehas", "roll":[
"Un tatouage de dague.",
"Un tatouage d’ancre.",
"Un tatouage de crâne.",
"Un tatouage d’os croisés.",
"Un tatouage de serpent.",
"Un tatouage de poisson.",
"Un tatouage de toile d’araignée.",
"Un tatouage de pieuvre.",
"Un tatouage de baleine.",
"Un tatouage de homard.",
"Un tatouage de sirène.",
"Un tatouage de dragon."
]},
{"title": "d12 Signe distinctif : Le pirate a...", "id":"d12distinguishingfeaturethepiratehas", "roll":[
"Un anneau au nez.",
"Des bottes en cuir brillant.",
"Des dents en or.",
"Une énorme dague à la ceinture.",
"Une lourde chaîne en or autour du cou.",
"Un large chapeau à bord.",
"Un cache-œil.",
"Une longue barbe noire.",
"Un rire dément.",
"Un long nez crochu.",
"Une chemise ouverte et un torse très poilu.",
"Des moustaches extravagantes."
]},
{"title": "d6 Les barbares sont...", "id":"d6thebarbariansare", "roll":[
"Une tribu de nomades suivant le gibier.",
"Une tribu qui a commencé à piller après avoir été chassée de ses terres natales.",
"Un clan exilé de ses terres natales.",
"Un clan au service d’un souverain.",
"Une confédération de tribus ou de clans liés.",
"Les survivants dégénérés d’une armée brisée."
]},
{"title": "d6 Les barbares voyagent...", "id":"d6thebarbarianstravel", "roll":[
"À pied.",
"À pied avec de petites charrettes.",
"À pied avec des éclaireurs montés.",
"À dos de montures.",
"À dos de montures avec des chariots.",
"En petites embarcations."
]},
{"title": "d8 Les barbares valorisent...", "id":"d8thebarbariansvalue", "roll":[
"Le courage.",
"La force.",
"La sagesse.",
"La virilité.",
"L’honneur envers les dieux.",
"L’honneur envers leurs ancêtres."
]},
{"title": "d4 L’iconographie barbare représente...", "id":"d4thebarbariansiconographyfeatures", "roll":[
"Des symboles de mort et de destruction (d8) : 1. chauves-souris ; 2. os ; 3. corbeaux ; 4. flammes ; 5. fantômes ; 6. scorpions ; 7. crânes ; 8. vautours.",
"Des symboles célestes (d6) : 1. nuages ; 2. foudre ; 3. lune ; 4. neige ; 5. étoiles ; 6. soleil.",
"Des symboles de force et d’armement (d6) : 1. flèches ; 2. haches ; 3. poings ; 4. lances ; 5. pierres ; 6. épées.",
"Des bêtes totémiques (d8) : 1. ours ; 2. sangliers ; 3. aigles ; 4. chevaux ; 5. lions ; 6. hiboux ; 7. serpents ; 8. loups."
]},
{"title": "d10 Le chef des barbares est...", "id":"d10thebarbariansleaderis", "roll":[
"Un chef respecté.",
"Un seigneur de guerre charismatique.",
"Un prophète mystérieux.",
"Un descendant d’un héros vénéré.",
"Un tueur impitoyable.",
"Un brute sans finesse.",
"Un jeune guerrier impatient.",
"Un vieil homme sage.",
"Un héros de guerre célèbre.",
"Un amant prolifique."
]},
{"title": "d10 Les barbares craignent...", "id":"d10thebarbariansfear", "roll":[
"Les étrangers portant une certaine couleur (d8) : 1. rouge ; 2. or ; 3. vert ; 4. bleu ; 5. violet ; 6. blanc ; 7. noir ; 8. gris.",
"Les étrangers en armure d’acier.",
"Les étrangers avec une pilosité faciale.",
"Les femmes étrangères.",
"Tous les étrangers.",
"Les membres d’une race particulière (d4) : 1. nains ; 2. elfes ; 3. gobelinoïdes ; 4. humanoïdes reptiliens.",
"Un phénomène naturel (d6) : 1. tempêtes de neige ; 2. tremblements de terre ; 3. inondations ; 4. orages ; 5. volcans ; 6. typhons.",
"Les lanceurs de sorts.",
"Les dieux.",
"Les dragons."
]},
{"title": "d10 Les barbares sont tristement célèbres pour...", "id":"d10thebarbariansarenotoriousfor", "roll":[
"Ne jamais laisser de survivants.",
"Donner les prisonniers aux bêtes sauvages.",
"Tatouer ou marquer les prisonniers.",
"Scalper leurs ennemis.",
"Écorcher leurs ennemis.",
"Piller et brûler des villages.",
"Attaquer les caravanes de marchands.",
"Manger les prisonniers.",
"Réduire les prisonniers en esclavage.",
"Prendre des prisonniers comme épouses, concubines ou mignons."
]},
{"title": "d10 Les barbares sont connus pour...", "id":"d10thebarbariansareknownfor", "roll":[
"Crier et hurler pendant la bataille.",
"Communiquer avec les fantômes et les esprits.",
"Des sacrifices rituels d’animaux.",
"Des sacrifices humains rituels.",
"Des saignées rituelles.",
"Des actes sexuels rituels.",
"Manger des viandes inhabituelles.",
"Boire en grande quantité.",
"Ne jamais se couper les cheveux.",
"Se raser la tête et le corps.",
"Ne jamais se laver.",
"Se laver et se parfumer le corps."
]},
{"title": "d6 L’attitude des barbares est...", "id":"d6thebarbariansattitudeis", "roll":[
"Turbulente et festive.",
"Joyeuse et impatiente de combattre.",
"Détendue et insouciante.",
"Apeurée et méfiante.",
"Hostile et méfiante.",
"Hostile et belliqueuse."
]},
{"title": "d6 L’objectif principal de la société est de...", "id":"d6thesocietysmaingoalisto", "roll":[
"Contrecarrer les plans d’une autre société secrète.",
"Provoquer la destruction de la ville, de la région ou du monde.",
"Encourager la rébellion contre la classe dirigeante.",
"Pourchasser et éliminer une race ou classe spécifique.",
"Protéger les gens du peuple contre la tyrannie.",
"Protéger la ville, la région ou le monde contre des influences extérieures malveillantes."
]},
{"title": "d12 La société est dirigée par...", "id":"d12thesocietyisledby", "roll":[
"Un conseil dont les membres héritent de leur place.",
"Un conseil composé d’anciens expérimentés.",
"Un conseil élu.",
"Un mégalomane dangereux.",
"Une femme fatale.",
"Un chevalier altruiste.",
"Un voleur audacieux.",
"Un fanatique religieux.",
"Un vieux prêtre ou mage sage.",
"Un héros de guerre célèbre.",
"Un riche marchand ou noble.",
"Un fugitif recherché."
]},
{"title": "d8 Les membres de la société se reconnaissent par...", "id":"d8membersofthesocietyrecognizeeachotherby", "roll":[
"Une poignée de main secrète.",
"Un geste secret.",
"Un mot de passe secret.",
"Des phrases codées et réponses précises.",
"Une broche ou bijou subtil.",
"Un style vestimentaire discret.",
"Un signal donné par un autre membre.",
"La manière dont ils stylisent leur pilosité faciale."
]},
{"title": "d20 Les couleurs de la société sont...", "id":"d20thesocietyscolorsare", "roll":[
"Noir.",
"Rouge / écarlate.",
"Or.",
"Vert forêt.",
"Bleu royal.",
"Violet.",
"Argent / gris clair.",
"Bronze.",
"Beige / kaki.",
"Marron / castor.",
"Gris foncé / canon de fusil.",
"Blanc.",
"Bordeaux.",
"Bleu ciel.",
"Bleu marine.",
"Brun foncé / chocolat.",
"Turquoise.",
"Jaune.",
"Orange.",
"Vert olive."
]},
{  "title": "d10 Le symbole de la société est...", "id":"d10thesocietyssymbolis", "roll":[
    "Une arme (d8) : 1. flèche ; 2. hache ; 3. dague ; 4. marteau ; 5. masse ; 6. lance ; 7. bâton ; 8. épée.",
    "Un morceau d'armure (d4) : 1. plastron ; 2. gantelet ; 3. casque ; 4. bouclier.",
    "Un astre céleste (d4) : 1. soleil ; 2. lune ; 3. étoile ; 4. comète.",
    "Une plante ou une partie de plante (d12) : 1. pomme ; 2. orge ; 3. ronce ; 4. figue ; 5. raisin ; 6. lys ; 7. érable ; 8. chêne ; 9. olive ; 10. pin ; 11. rose ; 12. blé.",
    "Une créature aquatique (d6) : 1. crabe ; 2. crocodile ; 3. grenouille ; 4. poisson ; 5. pieuvre ; 6. baleine.",
    "Une petite bête (d12) : 1. blaireau ; 2. chauve-souris ; 3. castor ; 4. chien ; 5. furet ; 6. renard ; 7. hérisson ; 8. lézard ; 9. rat ; 10. scorpion ; 11. serpent ; 12. araignée.",
    "Une grande bête (d8) : 1. ours ; 2. sanglier ; 3. taureau ; 4. dragon ; 5. lion ; 6. bœuf ; 7. cerf ; 8. loup.",
    "Un oiseau (d12) : 1. cardinal ; 2. colombe ; 3. aigle ; 4. faucon ; 5. oiseau moqueur ; 6. hibou ; 7. pélican ; 8. corbeau ; 9. coq ; 10. moineau ; 11. cygne ; 12. vautour.",
    "Une rune ou un élément élémentaire (d8) : 1. nuage ; 2. flamme ; 3. glace ; 4. éclair ; 5. neige ; 6. pierre ; 7. vague ; 8. tourbillon.",
    "Un symbole de mort (d4) : 1. os croisés ; 2. fantôme ; 3. crâne ; 4. main spectrale."
  ]},
{  "title": "d20 La devise de la société prône les idéaux de...", "id":"d20thesocietysmottochampionstheidealsof", "roll":[
    "Compassion.",
    "Courage.",
    "Discipline.",
    "Domination.",
    "Devoir.",
    "Excellence.",
    "Foi.",
    "Honneur.",
    "Espoir.",
    "Intégrité.",
    "Savoir.",
    "Justice.",
    "Loyauté.",
    "Miséricorde.",
    "Patience.",
    "Pouvoir.",
    "Droiture.",
    "Force.",
    "Victoire.",
    "Sagesse."
  ]},
{  "title": "d6 Les membres de la société agissent généralement...", "id":"d6membersofthesocietytypicallyoperate", "roll":[
    "Seuls et en secret.",
    "Par deux, en secret.",
    "En petits groupes, en secret.",
    "Seuls, mais ouvertement.",
    "Par deux, mais ouvertement.",
    "En petits groupes, mais ouvertement."
  ]},
{  "title": "d6 Les membres de la société connaissent généralement...", "id":"d6membersofthesocietytypicallyknow", "roll":[
    "Très peu d'autres membres.",
    "Plusieurs autres membres.",
    "Les détails de l'organisation.",
    "Rien du tout sur les dirigeants.",
    "Le nom des dirigeants sans les avoir jamais rencontrés.",
    "Un seul dirigeant et aucun autre membre."
  ]},
{  "title": "d12 Les membres se réunissent parfois dans...", "id":"d12membersofthesocietyoccasionallygathertomeetin", "roll":[
    "Une pièce secrète d’un temple connu.",
    "La cave d’une taverne populaire.",
    "Une salle cachée dans une guilde réputée.",
    "La cave d’un riche marchand.",
    "Les égouts de la ville.",
    "Les catacombes anciennes sous la ville.",
    "La résidence du chef ou d’un membre senior.",
    "Le bureau d’un marchand aisé.",
    "Une salle privée d’une taverne miteuse.",
    "Un bordel.",
    "Un entrepôt ou un chantier naval.",
    "Les égouts de la ville."
  ]},
{  "title": "d8 Les membres de la société sont principalement issus de...", "id":"d8thesocietysmembershipisprimarilymadeupof", "roll":[
    "La classe basse (esclaves, mendiants, orphelins, ouvriers, serviteurs...).",
    "L'élite riche (marchands, nobles...).",
    "Une religion particulière (temple, culte, secte...).",
    "Un métier spécifique (forgerons, charpentiers, pêcheurs, tisserands...).",
    "Une classe d’aventuriers (bardes, guerriers, mages, prêtres, rôdeurs, voleurs...).",
    "Une race particulière (nains, elfes, gnomes, halfelins...).",
    "Anciennes lignées spécifiques (maisons nobles, descendants de héros...).",
    "Un mélange éclectique de la société."
  ]},
{"title": "d12 La bande est crainte ou respectée par...", "id":"d12thegangisfearedorrespectedby", "roll":[
"Pêcheurs et marins.",
"Mendiants et voleurs.",
"Marchands et changeurs.",
"Bijoutiers et tailleurs de gemmes.",
"Politiciens et magistrats.",
"Gardes et shérifs.",
"Soldats et guerriers.",
"Gladiateurs et pugilistes.",
"Paysans et fermiers.",
"Serviteurs et esclaves.",
"Prêtres et sages.",
"Femmes et enfants."
]},
{"title": "d12 Trait distinctif d’un membre : Le membre de la bande a...", "id":"d12distinguishingfeatureforanindividualthegangmemberhas", "roll":[
"Un anneau dans le nez.",
"Des bottes en cuir brillantes.",
"Un trou dans la pointe d’une botte.",
"Une dague dans chaque botte.",
"Une lourde chaîne en or autour du cou.",
"Un large chapeau à larges bords.",
"Un tatouage de dague sur l’avant-bras.",
"Un tatouage de serpent autour du bras.",
"Un rire maniaque.",
"Un long nez crochu.",
"Une chemise ouverte révélant une poitrine très poilue.",
"Des moustaches extravagantes."
]},
{"title": "d12 Les couleurs de la garde sont...", "id":"d12thewatchscolorsare", "roll":[
"Noir.",
"Rouge / écarlate.",
"Or.",
"Vert forêt.",
"Bleu royal.",
"Argent / gris clair.",
"Marron / castor.",
"Blanc.",
"Bordeaux.",
"Bleu ciel.",
"Bleu marine.",
"Marron foncé / chocolat."
]},
{"title": "d12 Le symbole de la garde est...", "id":"d12thewatchssymbolis", "roll":[
"Une flamme.",
"Un gantelet.",
"Un bouclier.",
"Une épée.",
"Le soleil.",
"Un œil.",
"Un aigle.",
"Un hibou.",
"Un dragon.",
"Un lion.",
"Un corbeau.",
"Un loup."
]},
{"title": "d12 Le capitaine de la garde est...", "id":"d12thewatchscaptainis", "roll":[
"Un fanatique religieux.",
"Un héritier d’une famille éminente.",
"Un paria issu d’une famille éminente.",
"Un élégant bretteur.",
"Un brute épaisse.",
"Un héros de guerre célébré.",
"Un chevalier consacré.",
"Un soldat de carrière.",
"Un vétéran aguerri.",
"Un enquêteur expérimenté.",
"Un détective érudit.",
"Un serviteur public dévoué."
]},
{"title": "d6 L’attitude de la garde envers son capitaine est...", "id":"d6thewatchsattitudetowardtheircaptainis", "roll":[
"Amicale et loyale.",
"Respectueuse et professionnelle.",
"Totalement indifférente.",
"Prudente et incertaine.",
"Terrifiée et silencieuse.",
"Déçue et irrespectueuse."
]},
{"title": "d10 La garde est réputée pour...", "id":"d10thewatchhasareputationfor", "roll":[
"Sa haute moralité.",
"Son efficacité.",
"Sa fiabilité.",
"Sa brutalité.",
"Accepter des pots-de-vin.",
"Racketter les commerçants et artisans.",
"Fréquenter les bordels.",
"Sa lâcheté.",
"Son incompétence.",
"Son ivrognerie."
]},
{"title": "d6 La plupart des membres de la garde sont équipés de...", "id":"d6mostmembersofthewatchareoutfittedwith", "roll":[
"Capes grossières en laine.",
"Ce qu’ils peuvent trouver comme armure.",
"Armures de cuir avec le symbole de la garde.",
"Armures de cuir avec le symbole de leur ville ou seigneur.",
"Casques et cuirasses arborant le symbole de leur ville ou seigneur.",
"Cottes de mailles bien entretenues."
]},
{"title": "d10 La plupart des membres de la garde sont armés de...", "id":"d10mostmembersofthewatchareequippedwith", "roll":[
"Épées longues et arcs courts.",
"Épées longues et arbalètes.",
"Épées longues et boucliers.",
"Épées courtes et boucliers.",
"Masses et arbalètes.",
"Masses et boucliers.",
"Masses et dagues.",
"Piques et épées courtes.",
"Hallebardes et dagues.",
"Hallebardes et arbalètes."
]},
{"title": "d10 Le constable est...", "id":"d10theconstableis", "roll":[
"Un prêtre ou moine.",
"Un moine stoïque.",
"Un ancien soldat.",
"Un étranger mystérieux.",
"Un beau parleur pompeux.",
"Un érudit accompli.",
"Un ivrogne violent.",
"Un homme de main criminel.",
"Un habitué populaire de la taverne.",
"D'une beauté rude."
]},
{"title": "d6 Le constable travaille pour...", "id":"d6theconstableworksfor", "roll":[
"Un salaire stable.",
"La justice contre les criminels.",
"De l’or pour rembourser ses dettes.",
"De l’or pour financer son addiction (d4) : 1. boisson ; 2. jeu ; 3. prostituées ; 4. fumées.",
"Le plaisir de résoudre des mystères.",
"Une vengeance personnelle."
]},
{"title": "d12 Sur le visage du constable, il y a...", "id":"d12ontheconstablesfaceis", "roll":[
"Une cicatrice de brûlure.",
"Une cicatrice irrégulière.",
"Une mâchoire crispée.",
"Un sourire amical.",
"Un regard lointain.",
"Un front plissé.",
"Une paire d’yeux perçants.",
"Un nez cassé.",
"Des sourcils broussailleux.",
"Une barbe de quelques jours.",
"Une barbe soigneusement taillée.",
"Une moustache intimidante."
]},
{"title": "d10 Le constable porte...", "id":"d10theconstablecarries", "roll":[
"Une loupe.",
"Une lame au manche sculpté (d6) : 1. ivoire ; 2. jade ; 3. stéatite ; 4. ébène ; 5. acajou ; 6. chêne.",
"Une lame avec des bêtes sculptées sur la garde (d6) : 1. dragons ; 2. lions ; 3. scorpions ; 4. serpents ; 5. araignées ; 6. loups.",
"Une lame en acier noirci.",
"Un chapeau inhabituel.",
"Un indice d’un crime non résolu.",
"Un souvenir d’un amour perdu.",
"Des accessoires pour plusieurs déguisements.",
"Un manuel de référence alchimique.",
"Un almanach de poche."
]},
{"title": "d10 Le garde est...", "id":"d10theguardis", "roll":[
"Un fils de fermier.",
"Le fils d’un mineur ou d’un pêcheur.",
"Un vétéran de la guerre.",
"Un étranger.",
"Le fils d’un homme pauvre.",
"Un ivrogne.",
"Un criminel repenti.",
"Un voyou.",
"Un artisan raté.",
"Un favori des dames."
]},
{"title": "d6 Le garde travaille pour...", "id":"d6theguardworksfor", "roll":[
"Un salaire régulier.",
"La possibilité d’infliger des punitions sadiques.",
"De l’or pour rembourser ses dettes.",
"De l’or pour aider un membre de sa famille.",
"La possibilité d’échapper à l’emprisonnement à vie.",
"Un dévouement patriotique."
]},
{"title": "d12 Sur le visage du garde, il y a...", "id":"d12ontheguardsfaceis", "roll":[
"Une grande verrue.",
"Une cicatrice disgracieuse.",
"Un regard déterminé.",
"Un sourire niais.",
"Un regard idiot.",
"Un air confus.",
"Un nez bulbuleux.",
"Des sourcils broussailleux.",
"Des favoris imposants.",
"Une barbe hirsute.",
"Une moustache soigneusement taillée.",
"Une moustache cirée."
]},
{"title": "d10 Le garde porte...", "id":"d10theguardcarries", "roll":[
"Une lame avec des lanières en cuir souple au pommeau.",
"Une lame avec une inscription.",
"Une lame très bien polie.",
"Un souvenir d’une prostituée préférée.",
"Un trophée pris à un criminel.",
"Un ruban d’une noble demoiselle.",
"Un mouchoir en soie.",
"Une flasque de vin.",
"Un porte-bonheur (d4) : 1. patte de lapin ; 2. vieille pièce ; 3. pièce brillante ; 4. trèfle à quatre feuilles.",
"Une liste de courses."
]},




// end of factions

];
